<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Shared/LessonPolicies/**/*.cs" Link="Shared/LessonPolicies/%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
