<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
    <Page Include="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="backend/**/*.cs" />
    <EmbeddedResource Remove="backend/**/*" />
    <None Remove="backend/**/*" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets/Avatars/**/*.gif" />
    <None Remove="Assets/Welcome/**/*.png" />
    <Resource Include="Assets/Avatars/**/*.gif" />
    <Resource Include="Assets/Welcome/**/*.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Content/**/*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="Velopack" Version="1.2.0" />
    <PackageReference Include="XamlAnimatedGif" Version="2.3.1" />
  </ItemGroup>

</Project>
