using EnglishVoiceTutor.Desktop.Models;
using EnglishVoiceTutor.Shared.NativeLanguages;

namespace EnglishVoiceTutor.Desktop.Localization;

public static class AppLocalization
{
    private static readonly Lazy<IReadOnlyDictionary<string, AppLocalizedText>> TextByLanguageId = new(BuildTextByLanguageId);

    public static AppLocalizedText GetText(string? languageId)
    {
        var normalizedLanguageId = NormalizeLanguageId(languageId);
        return TextByLanguageId.Value.TryGetValue(normalizedLanguageId, out var text) ? text : TextByLanguageId.Value[InterfaceLanguageOptions.EnglishId];
    }

    public static SettingsLocalizedText GetSettingsText(string? languageId) => GetText(languageId).Settings;

    public static string NormalizeLanguageId(string? languageId)
    {
        return NativeLanguageCatalog.GetByIdOrName(languageId).Id;
    }

    private static IReadOnlyDictionary<string, AppLocalizedText> BuildTextByLanguageId()
    {
        var result = new Dictionary<string, AppLocalizedText>(StringComparer.OrdinalIgnoreCase);
        foreach (var language in NativeLanguageCatalog.All)
        {
            var terms = TermsByLanguageId.TryGetValue(language.Id, out var localizedTerms) ? localizedTerms : EnglishTerms;
            result[language.Id] = CreateText(language.Id, terms);
        }
        return result;
    }

    private static AppLocalizedText CreateText(string languageId, UiTerms t)
    {
        var settings = new SettingsLocalizedText(
            t.Settings,
            "Configure your learning preferences.",
            t.InterfaceLanguage,
            t.NativeLanguage,
            "Translations will use this language later.",
            "Connection",
            "Backend URL",
            "Used by the app to reach the local or remote backend.",
            "Your profile",
            "This helps your tutor personalize lessons.",
            "Your name",
            "Learning goal",
            t.TutorAvatar,
            "Choose who will guide your lesson chat.",
            "Avatar profile",
            "Age",
            "Location",
            "Role",
            "Interests",
            "Personality",
            "Speaking style",
            t.Progress,
            "Based on completed lessons on this device.",
            "Total completed lessons",
            "Lessons completed today",
            "Current streak",
            "Last completed lesson",
            "No completed lessons yet.",
            t.Save,
            t.Back,
            $"{t.Settings} {t.Success.ToLowerInvariant()}.",
            t.Audio,
            t.Microphone,
            "System default",
            t.TestMicrophone,
            t.RefreshMicrophones,
            "Microphone test completed.",
            "No microphone found.",
            "Selected microphone is unavailable. Using system default.",
            t.StudyLanguage,
            "Choose the language you want to practice. This does not change the app UI language.",
            t.Account,
            "Sign in or create an account to start lessons. A 7-day trial starts automatically after registration.",
            t.Email,
            t.Password,
            t.DisplayName,
            t.Register,
            t.Login,
            t.Logout,
            t.CurrentAccount,
            t.SettingsSource,
            t.SubscriptionStatus,
            t.Plan,
            t.Premium,
            t.Trial,
            "Free lesson today",
            "Enforcement",
            "Source",
            "Checked",
            t.Close,
            t.RefreshStatus,
            t.Upgrade,
            t.Diagnostics,
            t.Learning,
            t.Progress);

        return new AppLocalizedText(
            languageId, settings,
            "Practice spoken English with short AI-powered lessons.", "How the MVP works", "• Choose a topic", "• Practice by text or voice", "• Get soft corrections and hints", t.StartLesson, t.Settings, "MVP build — AI, voice, and avatar will be connected step by step.",
            t.ChooseLevel, "We will use this level later to adapt lessons and corrections.", $"{t.Level}:", "Please select a level before continuing.", t.Continue, t.Back,
            t.Home, "Start with a practical situation and practice step by step.", $"{t.Level}:", "Free MVP limit: 3 lessons today", "Lesson history", t.Settings,
            $"{t.ChooseSituation} for {{0}}", "Pick a realistic scenario for your short speaking lesson.", $"{t.Topic}:", $"{t.Situation}:", "Please choose a situation before starting the lesson.", t.StartLesson,
            t.LessonChat, $"{t.Topic}:", $"{t.Situation}:", $"{t.Level}:", t.Send, t.StartRecording, t.StopRecording, t.Hint, "Auto-send voice", "Send transcribed voice automatically after recording.", "Auto-play bot voice", "Play bot voice automatically after each reply.", t.FinishLesson, t.ConversationMode, "Back to chat", "Back to chat", t.ShowTranslation, t.HideTranslation, t.Translation, t.PlayVoice, "View feedback", t.Hint, "Click to close", "Feedback", "Corrected version", "Grammar tip", "Vocabulary tip", "Culture tip", "More natural version", "Translate feedback", "Hide feedback translation", "Feedback translation", "Bot status:", "Ready", "Thinking",
            "Recording... Click Stop recording when you finish.", "Could not start voice recording. Please check your microphone.", "Could not stop voice recording. Please try again.", "Transcribing your voice...", "Voice transcription is ready. Review the text and press Send.", "Could not transcribe the recording. Please try again or type your answer.", "No speech was recognized. Please try again.", "Please type your answer before sending.", "Playing AI-generated bot voice...", "Could not play bot voice. Please try again.", "Backend is unavailable. Please start the local backend and try again.", "Backend health check failed. Please start the local backend.", "Translating...", "Could not translate this text. Please try again.", "Hint: Try answering with a short complete sentence.",
            t.Summary, t.WhatWentWell, t.WhatToImprove, t.UsefulPhrases, t.BackToLessons, t.Back, "You completed a short practice dialogue and received AI feedback on your response.", "Keep practicing full sentences and apply the feedback tips to improve grammar and vocabulary.", ["Could you help me, please?", "I would like to...", "Could you repeat that, please?", "That sounds good to me."],
            "Lesson history", "Recent completed lessons on this device.", "No completed lessons yet. Finish a lesson to see it here.", BuildTopicDisplayText(t), BuildSubtopicDisplayText());
    }

    private static IReadOnlyDictionary<string, LocalizedDisplayText> BuildTopicDisplayText(UiTerms t)
    {
        return Map(("Daily Life", "Daily Life", "Small talk, introductions, and daily situations."), ("Travel", "Travel", "Airports, hotels, directions, and transport."), ("Work & Business", "Work & Business", "Meetings, emails, calls, and workplace conversations."), ("Job Interview", "Job Interview", "Practice common interview questions and answers."), ("Restaurant & Cafe", "Restaurant & Cafe", "Ordering food, booking tables, and polite requests."));
    }

    private static IReadOnlyDictionary<string, LocalizedDisplayText> BuildSubtopicDisplayText()
    {
        return Map(("Introductions", "Introductions", "Introduce yourself and ask basic personal questions."), ("Small talk with a neighbor", "Small talk with a neighbor", "Have a friendly short conversation near home."), ("Asking for help", "Asking for help", "Ask someone for help in a simple everyday situation."), ("Making plans", "Making plans", "Plan an activity and agree on time and place."), ("Talking about your day", "Talking about your day", "Describe your day and daily routine."), ("Airport check-in", "Airport check-in", "Check in for a flight and confirm travel details."), ("Hotel check-in", "Hotel check-in", "Check in at a hotel and ask common questions."), ("Asking for directions", "Asking for directions", "Ask for and understand directions in a new city."), ("Ordering transport", "Ordering transport", "Arrange a taxi or rideshare to your destination."), ("Lost luggage", "Lost luggage", "Report lost baggage and explain your situation."));
    }

    private static IReadOnlyDictionary<string, LocalizedDisplayText> Map(params (string Key, string Title, string Description)[] values)
    {
        return values.ToDictionary(value => value.Key, value => new LocalizedDisplayText(value.Title, value.Description), StringComparer.OrdinalIgnoreCase);
    }

    private sealed record UiTerms(string Settings, string Learning, string Account, string Audio, string Progress, string Diagnostics, string Save, string Back, string Continue, string Cancel, string Close, string Retry, string Loading, string Error, string Success, string StudyLanguage, string NativeLanguage, string InterfaceLanguage, string TutorAvatar, string LessonChat, string Topic, string Situation, string Level, string ConversationMode, string Send, string StartRecording, string StopRecording, string Hint, string Translation, string ShowTranslation, string HideTranslation, string PlayVoice, string FinishLesson, string Summary, string WhatWentWell, string WhatToImprove, string UsefulPhrases, string MistakesToReview, string NextSteps, string BackToLessons, string RepeatLesson, string Home, string ChooseLevel, string ChooseTopic, string ChooseSituation, string StartLesson, string Upgrade, string Premium, string Free, string RefreshStatus, string ContinueFree, string Login, string Register, string Logout, string Email, string Password, string DisplayName, string CurrentAccount, string SettingsSource, string SubscriptionStatus, string Plan, string Trial, string Microphone, string TestMicrophone, string RefreshMicrophones);

    private static readonly UiTerms EnglishTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms esTerms = new(
        "Ajustes", "Aprendizaje", "Cuenta", "Audio", "Progreso", "Diagnóstico", "Guardar", "Atrás", "Continuar", "Cancelar", "Cerrar", "Reintentar", "Cargando", "Error", "Correcto", "Idioma de estudio", "Idioma nativo", "Idioma de la interfaz", "Avatar del tutor", "Chat de la lección", "Tema", "Situación", "Nivel", "Modo conversación", "Enviar", "Iniciar grabación", "Detener grabación", "Pista", "Traducción", "Mostrar traducción", "Ocultar traducción", "Reproducir voz", "Terminar lección", "Resumen", "Lo que salió bien", "Qué mejorar", "Frases útiles", "Errores para revisar", "Siguientes pasos", "Volver a lecciones", "Repetir lección", "Inicio", "Elegir nivel", "Elegir tema", "Elegir situación", "Iniciar lección", "Mejorar", "Premium", "Gratis", "Actualizar estado", "Continuar gratis", "Iniciar sesión", "Registrarse", "Cerrar sesión", "Correo", "Contraseña", "Nombre visible", "Cuenta actual", "Origen de ajustes", "Estado de suscripción", "Plan", "Prueba", "Micrófono", "Probar micrófono", "Actualizar micrófonos");
    private static readonly UiTerms frTerms = new(
        "Paramètres", "Apprentissage", "Compte", "Audio", "Progrès", "Diagnostic", "Enregistrer", "Retour", "Continuer", "Annuler", "Fermer", "Réessayer", "Chargement", "Erreur", "Succès", "Langue d’étude", "Langue maternelle", "Langue de l’interface", "Avatar du tuteur", "Chat de leçon", "Sujet", "Situation", "Niveau", "Mode conversation", "Envoyer", "Démarrer l’enregistrement", "Arrêter l’enregistrement", "Indice", "Traduction", "Afficher la traduction", "Masquer la traduction", "Lire la voix", "Terminer la leçon", "Résumé", "Ce qui a bien marché", "À améliorer", "Phrases utiles", "Erreurs à revoir", "Étapes suivantes", "Retour aux leçons", "Répéter la leçon", "Accueil", "Choisir le niveau", "Choisir le sujet", "Choisir la situation", "Démarrer la leçon", "Mettre à niveau", "Premium", "Gratuit", "Actualiser le statut", "Continuer gratuitement", "Connexion", "Inscription", "Déconnexion", "E-mail", "Mot de passe", "Nom affiché", "Compte actuel", "Source des paramètres", "Statut de l’abonnement", "Forfait", "Essai", "Microphone", "Tester le microphone", "Actualiser les microphones");
    private static readonly UiTerms deTerms = new(
        "Einstellungen", "Lernen", "Konto", "Audio", "Fortschritt", "Diagnose", "Speichern", "Zurück", "Weiter", "Abbrechen", "Schließen", "Erneut versuchen", "Wird geladen", "Fehler", "Erfolg", "Lernsprache", "Muttersprache", "Sprache der Oberfläche", "Tutor-Avatar", "Lektionschat", "Thema", "Situation", "Niveau", "Konversationsmodus", "Senden", "Aufnahme starten", "Aufnahme stoppen", "Hinweis", "Übersetzung", "Übersetzung anzeigen", "Übersetzung ausblenden", "Stimme abspielen", "Lektion beenden", "Zusammenfassung", "Was gut lief", "Was verbessern", "Nützliche Sätze", "Fehler zum Wiederholen", "Nächste Schritte", "Zurück zu Lektionen", "Lektion wiederholen", "Start", "Niveau wählen", "Thema wählen", "Situation wählen", "Lektion starten", "Upgrade", "Premium", "Kostenlos", "Status aktualisieren", "Kostenlos fortfahren", "Anmelden", "Registrieren", "Abmelden", "E-Mail", "Passwort", "Anzeigename", "Aktuelles Konto", "Einstellungsquelle", "Abo-Status", "Tarif", "Testphase", "Mikrofon", "Mikrofon testen", "Mikrofone aktualisieren");
    private static readonly UiTerms itTerms = new(
        "Impostazioni", "Apprendimento", "Account", "Audio", "Progressi", "Diagnostica", "Salva", "Indietro", "Continua", "Annulla", "Chiudi", "Riprova", "Caricamento", "Errore", "Successo", "Lingua di studio", "Lingua madre", "Lingua dell’interfaccia", "Avatar del tutor", "Chat della lezione", "Argomento", "Situazione", "Livello", "Modalità conversazione", "Invia", "Avvia registrazione", "Ferma registrazione", "Suggerimento", "Traduzione", "Mostra traduzione", "Nascondi traduzione", "Riproduci voce", "Termina lezione", "Riepilogo", "Cosa è andato bene", "Da migliorare", "Frasi utili", "Errori da rivedere", "Prossimi passi", "Torna alle lezioni", "Ripeti lezione", "Home", "Scegli livello", "Scegli argomento", "Scegli situazione", "Avvia lezione", "Upgrade", "Premium", "Gratis", "Aggiorna stato", "Continua gratis", "Accedi", "Registrati", "Esci", "Email", "Password", "Nome visualizzato", "Account attuale", "Origine impostazioni", "Stato abbonamento", "Piano", "Prova", "Microfono", "Prova microfono", "Aggiorna microfoni");
    private static readonly UiTerms ptTerms = new(
        "Configurações", "Aprendizagem", "Conta", "Áudio", "Progresso", "Diagnóstico", "Salvar", "Voltar", "Continuar", "Cancelar", "Fechar", "Tentar novamente", "Carregando", "Erro", "Sucesso", "Idioma de estudo", "Idioma nativo", "Idioma da interface", "Avatar do tutor", "Chat da aula", "Tema", "Situação", "Nível", "Modo conversa", "Enviar", "Iniciar gravação", "Parar gravação", "Dica", "Tradução", "Mostrar tradução", "Ocultar tradução", "Reproduzir voz", "Concluir aula", "Resumo", "O que foi bem", "O que melhorar", "Frases úteis", "Erros para revisar", "Próximos passos", "Voltar às aulas", "Repetir aula", "Início", "Escolher nível", "Escolher tema", "Escolher situação", "Iniciar aula", "Upgrade", "Premium", "Grátis", "Atualizar status", "Continuar grátis", "Entrar", "Registrar", "Sair", "Email", "Senha", "Nome exibido", "Conta atual", "Origem das configurações", "Status da assinatura", "Plano", "Teste", "Microfone", "Testar microfone", "Atualizar microfones");
    private static readonly UiTerms ruTerms = new(
        "Настройки", "Обучение", "Аккаунт", "Аудио", "Прогресс", "Диагностика", "Сохранить", "Назад", "Продолжить", "Отмена", "Закрыть", "Повторить", "Загрузка", "Ошибка", "Успешно", "Язык обучения", "Родной язык", "Язык интерфейса", "Аватар наставника", "Чат урока", "Тема", "Ситуация", "Уровень", "Режим разговора", "Отправить", "Начать запись", "Остановить запись", "Подсказка", "Перевод", "Показать перевод", "Скрыть перевод", "Воспроизвести голос", "Завершить урок", "Итоги", "Что получилось", "Что улучшить", "Полезные фразы", "Ошибки для повтора", "Следующие шаги", "К урокам", "Повторить урок", "Главная", "Выберите уровень", "Выберите тему", "Выберите ситуацию", "Начать урок", "Улучшить", "Премиум", "Бесплатно", "Обновить статус", "Продолжить бесплатно", "Войти", "Регистрация", "Выйти", "Email", "Пароль", "Отображаемое имя", "Текущий аккаунт", "Источник настроек", "Статус подписки", "План", "Пробный период", "Микрофон", "Проверить микрофон", "Обновить микрофоны");
    private static readonly UiTerms ukTerms = new(
        "Настройки", "Обучение", "Аккаунт", "Аудио", "Прогресс", "Диагностика", "Сохранить", "Назад", "Продолжить", "Отмена", "Закрыть", "Повторить", "Загрузка", "Ошибка", "Успешно", "Язык обучения", "Родной язык", "Язык интерфейса", "Аватар наставника", "Чат урока", "Тема", "Ситуация", "Уровень", "Режим разговора", "Отправить", "Начать запись", "Остановить запись", "Подсказка", "Перевод", "Показать перевод", "Скрыть перевод", "Воспроизвести голос", "Завершить урок", "Итоги", "Что получилось", "Что улучшить", "Полезные фразы", "Ошибки для повтора", "Следующие шаги", "К урокам", "Повторить урок", "Главная", "Выберите уровень", "Выберите тему", "Выберите ситуацию", "Начать урок", "Улучшить", "Премиум", "Бесплатно", "Обновить статус", "Продолжить бесплатно", "Войти", "Регистрация", "Выйти", "Email", "Пароль", "Отображаемое имя", "Текущий аккаунт", "Источник настроек", "Статус подписки", "План", "Пробный период", "Микрофон", "Проверить микрофон", "Обновить микрофоны");
    private static readonly UiTerms plTerms = new(
        "Ustawienia", "Nauka", "Konto", "Audio", "Postępy", "Diagnostyka", "Zapisz", "Wstecz", "Kontynuuj", "Anuluj", "Zamknij", "Spróbuj ponownie", "Ładowanie", "Błąd", "Sukces", "Język nauki", "Język ojczysty", "Język interfejsu", "Awatar tutora", "Czat lekcji", "Temat", "Sytuacja", "Poziom", "Tryb rozmowy", "Wyślij", "Rozpocznij nagrywanie", "Zatrzymaj nagrywanie", "Wskazówka", "Tłumaczenie", "Pokaż tłumaczenie", "Ukryj tłumaczenie", "Odtwórz głos", "Zakończ lekcję", "Podsumowanie", "Co poszło dobrze", "Co poprawić", "Przydatne zwroty", "Błędy do powtórki", "Następne kroki", "Wróć do lekcji", "Powtórz lekcję", "Strona główna", "Wybierz poziom", "Wybierz temat", "Wybierz sytuację", "Rozpocznij lekcję", "Ulepsz", "Premium", "Bezpłatnie", "Odśwież status", "Kontynuuj bezpłatnie", "Zaloguj", "Zarejestruj", "Wyloguj", "E-mail", "Hasło", "Nazwa wyświetlana", "Bieżące konto", "Źródło ustawień", "Status subskrypcji", "Plan", "Okres próbny", "Mikrofon", "Testuj mikrofon", "Odśwież mikrofony");
    private static readonly UiTerms nlTerms = new(
        "Einstellungen", "Lernen", "Konto", "Audio", "Fortschritt", "Diagnose", "Speichern", "Zurück", "Weiter", "Abbrechen", "Schließen", "Erneut versuchen", "Wird geladen", "Fehler", "Erfolg", "Lernsprache", "Muttersprache", "Sprache der Oberfläche", "Tutor-Avatar", "Lektionschat", "Thema", "Situation", "Niveau", "Konversationsmodus", "Senden", "Aufnahme starten", "Aufnahme stoppen", "Hinweis", "Übersetzung", "Übersetzung anzeigen", "Übersetzung ausblenden", "Stimme abspielen", "Lektion beenden", "Zusammenfassung", "Was gut lief", "Was verbessern", "Nützliche Sätze", "Fehler zum Wiederholen", "Nächste Schritte", "Zurück zu Lektionen", "Lektion wiederholen", "Start", "Niveau wählen", "Thema wählen", "Situation wählen", "Lektion starten", "Upgrade", "Premium", "Kostenlos", "Status aktualisieren", "Kostenlos fortfahren", "Anmelden", "Registrieren", "Abmelden", "E-Mail", "Passwort", "Anzeigename", "Aktuelles Konto", "Einstellungsquelle", "Abo-Status", "Tarif", "Testphase", "Mikrofon", "Mikrofon testen", "Mikrofone aktualisieren");
    private static readonly UiTerms trTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms arTerms = new(
        "الإعدادات", "التعلّم", "الحساب", "الصوت", "التقدّم", "التشخيص", "حفظ", "رجوع", "متابعة", "إلغاء", "إغلاق", "إعادة المحاولة", "جارٍ التحميل", "خطأ", "نجاح", "لغة الدراسة", "اللغة الأم", "لغة الواجهة", "صورة المعلّم", "دردشة الدرس", "الموضوع", "الموقف", "المستوى", "وضع المحادثة", "إرسال", "بدء التسجيل", "إيقاف التسجيل", "تلميح", "ترجمة", "إظهار الترجمة", "إخفاء الترجمة", "تشغيل الصوت", "إنهاء الدرس", "ملخص", "ما سار جيدًا", "ما يجب تحسينه", "عبارات مفيدة", "أخطاء للمراجعة", "الخطوات التالية", "العودة إلى الدروس", "إعادة الدرس", "الرئيسية", "اختر المستوى", "اختر الموضوع", "اختر الموقف", "ابدأ الدرس", "ترقية", "مميز", "مجاني", "تحديث الحالة", "المتابعة بالخطة المجانية", "تسجيل الدخول", "تسجيل", "تسجيل الخروج", "البريد الإلكتروني", "كلمة المرور", "اسم العرض", "الحساب الحالي", "مصدر الإعدادات", "حالة الاشتراك", "الخطة", "تجربة", "الميكروفون", "اختبار الميكروفون", "تحديث الميكروفونات");
    private static readonly UiTerms hiTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms zh_HansTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms jaTerms = new(
        "設定", "学習", "アカウント", "音声", "進捗", "診断", "保存", "戻る", "続ける", "キャンセル", "閉じる", "再試行", "読み込み中", "エラー", "成功", "学習言語", "母語", "表示言語", "チューターアバター", "レッスンチャット", "トピック", "場面", "レベル", "会話モード", "送信", "録音開始", "録音停止", "ヒント", "翻訳", "翻訳を表示", "翻訳を非表示", "音声を再生", "レッスン終了", "まとめ", "良かった点", "改善点", "便利なフレーズ", "復習する間違い", "次のステップ", "レッスンに戻る", "レッスンを繰り返す", "ホーム", "レベルを選ぶ", "トピックを選ぶ", "場面を選ぶ", "レッスン開始", "アップグレード", "プレミアム", "無料", "状態を更新", "無料プランで続ける", "ログイン", "登録", "ログアウト", "メール", "パスワード", "表示名", "現在のアカウント", "設定元", "サブスクリプション状態", "プラン", "トライアル", "マイク", "マイクをテスト", "マイクを更新");
    private static readonly UiTerms koTerms = new(
        "設定", "学習", "アカウント", "音声", "進捗", "診断", "保存", "戻る", "続ける", "キャンセル", "閉じる", "再試行", "読み込み中", "エラー", "成功", "学習言語", "母語", "表示言語", "チューターアバター", "レッスンチャット", "トピック", "場面", "レベル", "会話モード", "送信", "録音開始", "録音停止", "ヒント", "翻訳", "翻訳を表示", "翻訳を非表示", "音声を再生", "レッスン終了", "まとめ", "良かった点", "改善点", "便利なフレーズ", "復習する間違い", "次のステップ", "レッスンに戻る", "レッスンを繰り返す", "ホーム", "レベルを選ぶ", "トピックを選ぶ", "場面を選ぶ", "レッスン開始", "アップグレード", "プレミアム", "無料", "状態を更新", "無料プランで続ける", "ログイン", "登録", "ログアウト", "メール", "パスワード", "表示名", "現在のアカウント", "設定元", "サブスクリプション状態", "プラン", "トライアル", "マイク", "マイクをテスト", "マイクを更新");
    private static readonly UiTerms viTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms idTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms faTerms = new(
        "الإعدادات", "التعلّم", "الحساب", "الصوت", "التقدّم", "التشخيص", "حفظ", "رجوع", "متابعة", "إلغاء", "إغلاق", "إعادة المحاولة", "جارٍ التحميل", "خطأ", "نجاح", "لغة الدراسة", "اللغة الأم", "لغة الواجهة", "صورة المعلّم", "دردشة الدرس", "الموضوع", "الموقف", "المستوى", "وضع المحادثة", "إرسال", "بدء التسجيل", "إيقاف التسجيل", "تلميح", "ترجمة", "إظهار الترجمة", "إخفاء الترجمة", "تشغيل الصوت", "إنهاء الدرس", "ملخص", "ما سار جيدًا", "ما يجب تحسينه", "عبارات مفيدة", "أخطاء للمراجعة", "الخطوات التالية", "العودة إلى الدروس", "إعادة الدرس", "الرئيسية", "اختر المستوى", "اختر الموضوع", "اختر الموقف", "ابدأ الدرس", "ترقية", "مميز", "مجاني", "تحديث الحالة", "المتابعة بالخطة المجانية", "تسجيل الدخول", "تسجيل", "تسجيل الخروج", "البريد الإلكتروني", "كلمة المرور", "اسم العرض", "الحساب الحالي", "مصدر الإعدادات", "حالة الاشتراك", "الخطة", "تجربة", "الميكروفون", "اختبار الميكروفون", "تحديث الميكروفونات");
    private static readonly UiTerms urTerms = new(
        "الإعدادات", "التعلّم", "الحساب", "الصوت", "التقدّم", "التشخيص", "حفظ", "رجوع", "متابعة", "إلغاء", "إغلاق", "إعادة المحاولة", "جارٍ التحميل", "خطأ", "نجاح", "لغة الدراسة", "اللغة الأم", "لغة الواجهة", "صورة المعلّم", "دردشة الدرس", "الموضوع", "الموقف", "المستوى", "وضع المحادثة", "إرسال", "بدء التسجيل", "إيقاف التسجيل", "تلميح", "ترجمة", "إظهار الترجمة", "إخفاء الترجمة", "تشغيل الصوت", "إنهاء الدرس", "ملخص", "ما سار جيدًا", "ما يجب تحسينه", "عبارات مفيدة", "أخطاء للمراجعة", "الخطوات التالية", "العودة إلى الدروس", "إعادة الدرس", "الرئيسية", "اختر المستوى", "اختر الموضوع", "اختر الموقف", "ابدأ الدرس", "ترقية", "مميز", "مجاني", "تحديث الحالة", "المتابعة بالخطة المجانية", "تسجيل الدخول", "تسجيل", "تسجيل الخروج", "البريد الإلكتروني", "كلمة المرور", "اسم العرض", "الحساب الحالي", "مصدر الإعدادات", "حالة الاشتراك", "الخطة", "تجربة", "الميكروفون", "اختبار الميكروفون", "تحديث الميكروفونات");
    private static readonly UiTerms bnTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms taTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms teTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms mrTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms guTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms thTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms svTerms = new(
        "Einstellungen", "Lernen", "Konto", "Audio", "Fortschritt", "Diagnose", "Speichern", "Zurück", "Weiter", "Abbrechen", "Schließen", "Erneut versuchen", "Wird geladen", "Fehler", "Erfolg", "Lernsprache", "Muttersprache", "Sprache der Oberfläche", "Tutor-Avatar", "Lektionschat", "Thema", "Situation", "Niveau", "Konversationsmodus", "Senden", "Aufnahme starten", "Aufnahme stoppen", "Hinweis", "Übersetzung", "Übersetzung anzeigen", "Übersetzung ausblenden", "Stimme abspielen", "Lektion beenden", "Zusammenfassung", "Was gut lief", "Was verbessern", "Nützliche Sätze", "Fehler zum Wiederholen", "Nächste Schritte", "Zurück zu Lektionen", "Lektion wiederholen", "Start", "Niveau wählen", "Thema wählen", "Situation wählen", "Lektion starten", "Upgrade", "Premium", "Kostenlos", "Status aktualisieren", "Kostenlos fortfahren", "Anmelden", "Registrieren", "Abmelden", "E-Mail", "Passwort", "Anzeigename", "Aktuelles Konto", "Einstellungsquelle", "Abo-Status", "Tarif", "Testphase", "Mikrofon", "Mikrofon testen", "Mikrofone aktualisieren");
    private static readonly UiTerms noTerms = new(
        "Einstellungen", "Lernen", "Konto", "Audio", "Fortschritt", "Diagnose", "Speichern", "Zurück", "Weiter", "Abbrechen", "Schließen", "Erneut versuchen", "Wird geladen", "Fehler", "Erfolg", "Lernsprache", "Muttersprache", "Sprache der Oberfläche", "Tutor-Avatar", "Lektionschat", "Thema", "Situation", "Niveau", "Konversationsmodus", "Senden", "Aufnahme starten", "Aufnahme stoppen", "Hinweis", "Übersetzung", "Übersetzung anzeigen", "Übersetzung ausblenden", "Stimme abspielen", "Lektion beenden", "Zusammenfassung", "Was gut lief", "Was verbessern", "Nützliche Sätze", "Fehler zum Wiederholen", "Nächste Schritte", "Zurück zu Lektionen", "Lektion wiederholen", "Start", "Niveau wählen", "Thema wählen", "Situation wählen", "Lektion starten", "Upgrade", "Premium", "Kostenlos", "Status aktualisieren", "Kostenlos fortfahren", "Anmelden", "Registrieren", "Abmelden", "E-Mail", "Passwort", "Anzeigename", "Aktuelles Konto", "Einstellungsquelle", "Abo-Status", "Tarif", "Testphase", "Mikrofon", "Mikrofon testen", "Mikrofone aktualisieren");
    private static readonly UiTerms daTerms = new(
        "Einstellungen", "Lernen", "Konto", "Audio", "Fortschritt", "Diagnose", "Speichern", "Zurück", "Weiter", "Abbrechen", "Schließen", "Erneut versuchen", "Wird geladen", "Fehler", "Erfolg", "Lernsprache", "Muttersprache", "Sprache der Oberfläche", "Tutor-Avatar", "Lektionschat", "Thema", "Situation", "Niveau", "Konversationsmodus", "Senden", "Aufnahme starten", "Aufnahme stoppen", "Hinweis", "Übersetzung", "Übersetzung anzeigen", "Übersetzung ausblenden", "Stimme abspielen", "Lektion beenden", "Zusammenfassung", "Was gut lief", "Was verbessern", "Nützliche Sätze", "Fehler zum Wiederholen", "Nächste Schritte", "Zurück zu Lektionen", "Lektion wiederholen", "Start", "Niveau wählen", "Thema wählen", "Situation wählen", "Lektion starten", "Upgrade", "Premium", "Kostenlos", "Status aktualisieren", "Kostenlos fortfahren", "Anmelden", "Registrieren", "Abmelden", "E-Mail", "Passwort", "Anzeigename", "Aktuelles Konto", "Einstellungsquelle", "Abo-Status", "Tarif", "Testphase", "Mikrofon", "Mikrofon testen", "Mikrofone aktualisieren");
    private static readonly UiTerms csTerms = new(
        "Ustawienia", "Nauka", "Konto", "Audio", "Postępy", "Diagnostyka", "Zapisz", "Wstecz", "Kontynuuj", "Anuluj", "Zamknij", "Spróbuj ponownie", "Ładowanie", "Błąd", "Sukces", "Język nauki", "Język ojczysty", "Język interfejsu", "Awatar tutora", "Czat lekcji", "Temat", "Sytuacja", "Poziom", "Tryb rozmowy", "Wyślij", "Rozpocznij nagrywanie", "Zatrzymaj nagrywanie", "Wskazówka", "Tłumaczenie", "Pokaż tłumaczenie", "Ukryj tłumaczenie", "Odtwórz głos", "Zakończ lekcję", "Podsumowanie", "Co poszło dobrze", "Co poprawić", "Przydatne zwroty", "Błędy do powtórki", "Następne kroki", "Wróć do lekcji", "Powtórz lekcję", "Strona główna", "Wybierz poziom", "Wybierz temat", "Wybierz sytuację", "Rozpocznij lekcję", "Ulepsz", "Premium", "Bezpłatnie", "Odśwież status", "Kontynuuj bezpłatnie", "Zaloguj", "Zarejestruj", "Wyloguj", "E-mail", "Hasło", "Nazwa wyświetlana", "Bieżące konto", "Źródło ustawień", "Status subskrypcji", "Plan", "Okres próbny", "Mikrofon", "Testuj mikrofon", "Odśwież mikrofony");
    private static readonly UiTerms roTerms = new(
        "Impostazioni", "Apprendimento", "Account", "Audio", "Progressi", "Diagnostica", "Salva", "Indietro", "Continua", "Annulla", "Chiudi", "Riprova", "Caricamento", "Errore", "Successo", "Lingua di studio", "Lingua madre", "Lingua dell’interfaccia", "Avatar del tutor", "Chat della lezione", "Argomento", "Situazione", "Livello", "Modalità conversazione", "Invia", "Avvia registrazione", "Ferma registrazione", "Suggerimento", "Traduzione", "Mostra traduzione", "Nascondi traduzione", "Riproduci voce", "Termina lezione", "Riepilogo", "Cosa è andato bene", "Da migliorare", "Frasi utili", "Errori da rivedere", "Prossimi passi", "Torna alle lezioni", "Ripeti lezione", "Home", "Scegli livello", "Scegli argomento", "Scegli situazione", "Avvia lezione", "Upgrade", "Premium", "Gratis", "Aggiorna stato", "Continua gratis", "Accedi", "Registrati", "Esci", "Email", "Password", "Nome visualizzato", "Account attuale", "Origine impostazioni", "Stato abbonamento", "Piano", "Prova", "Microfono", "Prova microfono", "Aggiorna microfoni");
    private static readonly UiTerms elTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms heTerms = new(
        "الإعدادات", "التعلّم", "الحساب", "الصوت", "التقدّم", "التشخيص", "حفظ", "رجوع", "متابعة", "إلغاء", "إغلاق", "إعادة المحاولة", "جارٍ التحميل", "خطأ", "نجاح", "لغة الدراسة", "اللغة الأم", "لغة الواجهة", "صورة المعلّم", "دردشة الدرس", "الموضوع", "الموقف", "المستوى", "وضع المحادثة", "إرسال", "بدء التسجيل", "إيقاف التسجيل", "تلميح", "ترجمة", "إظهار الترجمة", "إخفاء الترجمة", "تشغيل الصوت", "إنهاء الدرس", "ملخص", "ما سار جيدًا", "ما يجب تحسينه", "عبارات مفيدة", "أخطاء للمراجعة", "الخطوات التالية", "العودة إلى الدروس", "إعادة الدرس", "الرئيسية", "اختر المستوى", "اختر الموضوع", "اختر الموقف", "ابدأ الدرس", "ترقية", "مميز", "مجاني", "تحديث الحالة", "المتابعة بالخطة المجانية", "تسجيل الدخول", "تسجيل", "تسجيل الخروج", "البريد الإلكتروني", "كلمة المرور", "اسم العرض", "الحساب الحالي", "مصدر الإعدادات", "حالة الاشتراك", "الخطة", "تجربة", "الميكروفون", "اختبار الميكروفون", "تحديث الميكروفونات");
    private static readonly UiTerms srTerms = new(
        "Podešavanja", "Učenje", "Nalog", "Audio", "Napredak", "Dijagnostika", "Sačuvaj", "Nazad", "Nastavi", "Otkaži", "Zatvori", "Pokušaj ponovo", "Učitavanje", "Greška", "Uspeh", "Jezik učenja", "Maternji jezik", "Jezik interfejsa", "Avatar tutora", "Čet lekcije", "Tema", "Situacija", "Nivo", "Režim razgovora", "Pošalji", "Pokreni snimanje", "Zaustavi snimanje", "Nagoveštaj", "Prevod", "Prikaži prevod", "Sakrij prevod", "Pusti glas", "Završi lekciju", "Sažetak", "Šta je bilo dobro", "Šta poboljšati", "Korisne fraze", "Greške za pregled", "Sledeći koraci", "Nazad na lekcije", "Ponovi lekciju", "Početna", "Izaberi nivo", "Izaberi temu", "Izaberi situaciju", "Počni lekciju", "Nadogradi", "Premium", "Besplatno", "Osveži status", "Nastavi besplatno", "Prijava", "Registracija", "Odjava", "E-pošta", "Lozinka", "Prikazano ime", "Trenutni nalog", "Izvor podešavanja", "Status pretplate", "Plan", "Probni period", "Mikrofon", "Testiraj mikrofon", "Osveži mikrofone");
    private static readonly UiTerms hrTerms = new(
        "Postavke", "Učenje", "Račun", "Audio", "Napredak", "Dijagnostika", "Spremi", "Natrag", "Nastavi", "Odustani", "Zatvori", "Pokušaj ponovno", "Učitavanje", "Pogreška", "Uspjeh", "Jezik učenja", "Materinski jezik", "Jezik sučelja", "Avatar tutora", "Chat lekcije", "Tema", "Situacija", "Razina", "Način razgovora", "Pošalji", "Pokreni snimanje", "Zaustavi snimanje", "Savjet", "Prijevod", "Prikaži prijevod", "Sakrij prijevod", "Pusti glas", "Završi lekciju", "Sažetak", "Što je bilo dobro", "Što poboljšati", "Korisne fraze", "Pogreške za pregled", "Sljedeći koraci", "Natrag na lekcije", "Ponovi lekciju", "Početna", "Odaberi razinu", "Odaberi temu", "Odaberi situaciju", "Pokreni lekciju", "Nadogradi", "Premium", "Besplatno", "Osvježi status", "Nastavi besplatno", "Prijava", "Registracija", "Odjava", "E-pošta", "Lozinka", "Prikazano ime", "Trenutni račun", "Izvor postavki", "Status pretplate", "Plan", "Probno", "Mikrofon", "Testiraj mikrofon", "Osvježi mikrofone");
    private static readonly UiTerms bsTerms = new(
        "Postavke", "Učenje", "Račun", "Audio", "Napredak", "Dijagnostika", "Spremi", "Natrag", "Nastavi", "Odustani", "Zatvori", "Pokušaj ponovno", "Učitavanje", "Pogreška", "Uspjeh", "Jezik učenja", "Materinski jezik", "Jezik sučelja", "Avatar tutora", "Chat lekcije", "Tema", "Situacija", "Razina", "Način razgovora", "Pošalji", "Pokreni snimanje", "Zaustavi snimanje", "Savjet", "Prijevod", "Prikaži prijevod", "Sakrij prijevod", "Pusti glas", "Završi lekciju", "Sažetak", "Što je bilo dobro", "Što poboljšati", "Korisne fraze", "Pogreške za pregled", "Sljedeći koraci", "Natrag na lekcije", "Ponovi lekciju", "Početna", "Odaberi razinu", "Odaberi temu", "Odaberi situaciju", "Pokreni lekciju", "Nadogradi", "Premium", "Besplatno", "Osvježi status", "Nastavi besplatno", "Prijava", "Registracija", "Odjava", "E-pošta", "Lozinka", "Prikazano ime", "Trenutni račun", "Izvor postavki", "Status pretplate", "Plan", "Probno", "Mikrofon", "Testiraj mikrofon", "Osvježi mikrofone");
    private static readonly UiTerms slTerms = new(
        "Postavke", "Učenje", "Račun", "Audio", "Napredak", "Dijagnostika", "Spremi", "Natrag", "Nastavi", "Odustani", "Zatvori", "Pokušaj ponovno", "Učitavanje", "Pogreška", "Uspjeh", "Jezik učenja", "Materinski jezik", "Jezik sučelja", "Avatar tutora", "Chat lekcije", "Tema", "Situacija", "Razina", "Način razgovora", "Pošalji", "Pokreni snimanje", "Zaustavi snimanje", "Savjet", "Prijevod", "Prikaži prijevod", "Sakrij prijevod", "Pusti glas", "Završi lekciju", "Sažetak", "Što je bilo dobro", "Što poboljšati", "Korisne fraze", "Pogreške za pregled", "Sljedeći koraci", "Natrag na lekcije", "Ponovi lekciju", "Početna", "Odaberi razinu", "Odaberi temu", "Odaberi situaciju", "Pokreni lekciju", "Nadogradi", "Premium", "Besplatno", "Osvježi status", "Nastavi besplatno", "Prijava", "Registracija", "Odjava", "E-pošta", "Lozinka", "Prikazano ime", "Trenutni račun", "Izvor postavki", "Status pretplate", "Plan", "Probno", "Mikrofon", "Testiraj mikrofon", "Osvježi mikrofone");
    private static readonly UiTerms skTerms = new(
        "Ustawienia", "Nauka", "Konto", "Audio", "Postępy", "Diagnostyka", "Zapisz", "Wstecz", "Kontynuuj", "Anuluj", "Zamknij", "Spróbuj ponownie", "Ładowanie", "Błąd", "Sukces", "Język nauki", "Język ojczysty", "Język interfejsu", "Awatar tutora", "Czat lekcji", "Temat", "Sytuacja", "Poziom", "Tryb rozmowy", "Wyślij", "Rozpocznij nagrywanie", "Zatrzymaj nagrywanie", "Wskazówka", "Tłumaczenie", "Pokaż tłumaczenie", "Ukryj tłumaczenie", "Odtwórz głos", "Zakończ lekcję", "Podsumowanie", "Co poszło dobrze", "Co poprawić", "Przydatne zwroty", "Błędy do powtórki", "Następne kroki", "Wróć do lekcji", "Powtórz lekcję", "Strona główna", "Wybierz poziom", "Wybierz temat", "Wybierz sytuację", "Rozpocznij lekcję", "Ulepsz", "Premium", "Bezpłatnie", "Odśwież status", "Kontynuuj bezpłatnie", "Zaloguj", "Zarejestruj", "Wyloguj", "E-mail", "Hasło", "Nazwa wyświetlana", "Bieżące konto", "Źródło ustawień", "Status subskrypcji", "Plan", "Okres próbny", "Mikrofon", "Testuj mikrofon", "Odśwież mikrofony");
    private static readonly UiTerms bgTerms = new(
        "Настройки", "Учене", "Акаунт", "Аудио", "Напредък", "Диагностика", "Запази", "Назад", "Продължи", "Отказ", "Затвори", "Опитай пак", "Зареждане", "Грешка", "Успех", "Език за учене", "Роден език", "Език на интерфейса", "Аватар на тутора", "Чат на урока", "Тема", "Ситуация", "Ниво", "Режим разговор", "Изпрати", "Започни запис", "Спри запис", "Подсказка", "Превод", "Покажи превод", "Скрий превод", "Пусни глас", "Завърши урока", "Обобщение", "Какво беше добре", "Какво да подобриш", "Полезни фрази", "Грешки за преглед", "Следващи стъпки", "Назад към уроците", "Повтори урока", "Начало", "Избери ниво", "Избери тема", "Избери ситуация", "Започни урок", "Надгради", "Премиум", "Безплатно", "Обнови статус", "Продължи безплатно", "Вход", "Регистрация", "Изход", "Имейл", "Парола", "Показвано име", "Текущ акаунт", "Източник на настройки", "Статус на абонамента", "План", "Пробен период", "Микрофон", "Тествай микрофона", "Обнови микрофоните");
    private static readonly UiTerms huTerms = new(
        "Einstellungen", "Lernen", "Konto", "Audio", "Fortschritt", "Diagnose", "Speichern", "Zurück", "Weiter", "Abbrechen", "Schließen", "Erneut versuchen", "Wird geladen", "Fehler", "Erfolg", "Lernsprache", "Muttersprache", "Sprache der Oberfläche", "Tutor-Avatar", "Lektionschat", "Thema", "Situation", "Niveau", "Konversationsmodus", "Senden", "Aufnahme starten", "Aufnahme stoppen", "Hinweis", "Übersetzung", "Übersetzung anzeigen", "Übersetzung ausblenden", "Stimme abspielen", "Lektion beenden", "Zusammenfassung", "Was gut lief", "Was verbessern", "Nützliche Sätze", "Fehler zum Wiederholen", "Nächste Schritte", "Zurück zu Lektionen", "Lektion wiederholen", "Start", "Niveau wählen", "Thema wählen", "Situation wählen", "Lektion starten", "Upgrade", "Premium", "Kostenlos", "Status aktualisieren", "Kostenlos fortfahren", "Anmelden", "Registrieren", "Abmelden", "E-Mail", "Passwort", "Anzeigename", "Aktuelles Konto", "Einstellungsquelle", "Abo-Status", "Tarif", "Testphase", "Mikrofon", "Mikrofon testen", "Mikrofone aktualisieren");
    private static readonly UiTerms fiTerms = new(
        "Einstellungen", "Lernen", "Konto", "Audio", "Fortschritt", "Diagnose", "Speichern", "Zurück", "Weiter", "Abbrechen", "Schließen", "Erneut versuchen", "Wird geladen", "Fehler", "Erfolg", "Lernsprache", "Muttersprache", "Sprache der Oberfläche", "Tutor-Avatar", "Lektionschat", "Thema", "Situation", "Niveau", "Konversationsmodus", "Senden", "Aufnahme starten", "Aufnahme stoppen", "Hinweis", "Übersetzung", "Übersetzung anzeigen", "Übersetzung ausblenden", "Stimme abspielen", "Lektion beenden", "Zusammenfassung", "Was gut lief", "Was verbessern", "Nützliche Sätze", "Fehler zum Wiederholen", "Nächste Schritte", "Zurück zu Lektionen", "Lektion wiederholen", "Start", "Niveau wählen", "Thema wählen", "Situation wählen", "Lektion starten", "Upgrade", "Premium", "Kostenlos", "Status aktualisieren", "Kostenlos fortfahren", "Anmelden", "Registrieren", "Abmelden", "E-Mail", "Passwort", "Anzeigename", "Aktuelles Konto", "Einstellungsquelle", "Abo-Status", "Tarif", "Testphase", "Mikrofon", "Mikrofon testen", "Mikrofone aktualisieren");
    private static readonly UiTerms etTerms = new(
        "Einstellungen", "Lernen", "Konto", "Audio", "Fortschritt", "Diagnose", "Speichern", "Zurück", "Weiter", "Abbrechen", "Schließen", "Erneut versuchen", "Wird geladen", "Fehler", "Erfolg", "Lernsprache", "Muttersprache", "Sprache der Oberfläche", "Tutor-Avatar", "Lektionschat", "Thema", "Situation", "Niveau", "Konversationsmodus", "Senden", "Aufnahme starten", "Aufnahme stoppen", "Hinweis", "Übersetzung", "Übersetzung anzeigen", "Übersetzung ausblenden", "Stimme abspielen", "Lektion beenden", "Zusammenfassung", "Was gut lief", "Was verbessern", "Nützliche Sätze", "Fehler zum Wiederholen", "Nächste Schritte", "Zurück zu Lektionen", "Lektion wiederholen", "Start", "Niveau wählen", "Thema wählen", "Situation wählen", "Lektion starten", "Upgrade", "Premium", "Kostenlos", "Status aktualisieren", "Kostenlos fortfahren", "Anmelden", "Registrieren", "Abmelden", "E-Mail", "Passwort", "Anzeigename", "Aktuelles Konto", "Einstellungsquelle", "Abo-Status", "Tarif", "Testphase", "Mikrofon", "Mikrofon testen", "Mikrofone aktualisieren");
    private static readonly UiTerms lvTerms = new(
        "Ustawienia", "Nauka", "Konto", "Audio", "Postępy", "Diagnostyka", "Zapisz", "Wstecz", "Kontynuuj", "Anuluj", "Zamknij", "Spróbuj ponownie", "Ładowanie", "Błąd", "Sukces", "Język nauki", "Język ojczysty", "Język interfejsu", "Awatar tutora", "Czat lekcji", "Temat", "Sytuacja", "Poziom", "Tryb rozmowy", "Wyślij", "Rozpocznij nagrywanie", "Zatrzymaj nagrywanie", "Wskazówka", "Tłumaczenie", "Pokaż tłumaczenie", "Ukryj tłumaczenie", "Odtwórz głos", "Zakończ lekcję", "Podsumowanie", "Co poszło dobrze", "Co poprawić", "Przydatne zwroty", "Błędy do powtórki", "Następne kroki", "Wróć do lekcji", "Powtórz lekcję", "Strona główna", "Wybierz poziom", "Wybierz temat", "Wybierz sytuację", "Rozpocznij lekcję", "Ulepsz", "Premium", "Bezpłatnie", "Odśwież status", "Kontynuuj bezpłatnie", "Zaloguj", "Zarejestruj", "Wyloguj", "E-mail", "Hasło", "Nazwa wyświetlana", "Bieżące konto", "Źródło ustawień", "Status subskrypcji", "Plan", "Okres próbny", "Mikrofon", "Testuj mikrofon", "Odśwież mikrofony");
    private static readonly UiTerms ltTerms = new(
        "Ustawienia", "Nauka", "Konto", "Audio", "Postępy", "Diagnostyka", "Zapisz", "Wstecz", "Kontynuuj", "Anuluj", "Zamknij", "Spróbuj ponownie", "Ładowanie", "Błąd", "Sukces", "Język nauki", "Język ojczysty", "Język interfejsu", "Awatar tutora", "Czat lekcji", "Temat", "Sytuacja", "Poziom", "Tryb rozmowy", "Wyślij", "Rozpocznij nagrywanie", "Zatrzymaj nagrywanie", "Wskazówka", "Tłumaczenie", "Pokaż tłumaczenie", "Ukryj tłumaczenie", "Odtwórz głos", "Zakończ lekcję", "Podsumowanie", "Co poszło dobrze", "Co poprawić", "Przydatne zwroty", "Błędy do powtórki", "Następne kroki", "Wróć do lekcji", "Powtórz lekcję", "Strona główna", "Wybierz poziom", "Wybierz temat", "Wybierz sytuację", "Rozpocznij lekcję", "Ulepsz", "Premium", "Bezpłatnie", "Odśwież status", "Kontynuuj bezpłatnie", "Zaloguj", "Zarejestruj", "Wyloguj", "E-mail", "Hasło", "Nazwa wyświetlana", "Bieżące konto", "Źródło ustawień", "Status subskrypcji", "Plan", "Okres próbny", "Mikrofon", "Testuj mikrofon", "Odśwież mikrofony");
    private static readonly UiTerms sqTerms = new(
        "Impostazioni", "Apprendimento", "Account", "Audio", "Progressi", "Diagnostica", "Salva", "Indietro", "Continua", "Annulla", "Chiudi", "Riprova", "Caricamento", "Errore", "Successo", "Lingua di studio", "Lingua madre", "Lingua dell’interfaccia", "Avatar del tutor", "Chat della lezione", "Argomento", "Situazione", "Livello", "Modalità conversazione", "Invia", "Avvia registrazione", "Ferma registrazione", "Suggerimento", "Traduzione", "Mostra traduzione", "Nascondi traduzione", "Riproduci voce", "Termina lezione", "Riepilogo", "Cosa è andato bene", "Da migliorare", "Frasi utili", "Errori da rivedere", "Prossimi passi", "Torna alle lezioni", "Ripeti lezione", "Home", "Scegli livello", "Scegli argomento", "Scegli situazione", "Avvia lezione", "Upgrade", "Premium", "Gratis", "Aggiorna stato", "Continua gratis", "Accedi", "Registrati", "Esci", "Email", "Password", "Nome visualizzato", "Account attuale", "Origine impostazioni", "Stato abbonamento", "Piano", "Prova", "Microfono", "Prova microfono", "Aggiorna microfoni");
    private static readonly UiTerms mkTerms = new(
        "Настройки", "Учене", "Акаунт", "Аудио", "Напредък", "Диагностика", "Запази", "Назад", "Продължи", "Отказ", "Затвори", "Опитай пак", "Зареждане", "Грешка", "Успех", "Език за учене", "Роден език", "Език на интерфейса", "Аватар на тутора", "Чат на урока", "Тема", "Ситуация", "Ниво", "Режим разговор", "Изпрати", "Започни запис", "Спри запис", "Подсказка", "Превод", "Покажи превод", "Скрий превод", "Пусни глас", "Завърши урока", "Обобщение", "Какво беше добре", "Какво да подобриш", "Полезни фрази", "Грешки за преглед", "Следващи стъпки", "Назад към уроците", "Повтори урока", "Начало", "Избери ниво", "Избери тема", "Избери ситуация", "Започни урок", "Надгради", "Премиум", "Безплатно", "Обнови статус", "Продължи безплатно", "Вход", "Регистрация", "Изход", "Имейл", "Парола", "Показвано име", "Текущ акаунт", "Източник на настройки", "Статус на абонамента", "План", "Пробен период", "Микрофон", "Тествай микрофона", "Обнови микрофоните");
    private static readonly UiTerms beTerms = new(
        "Настройки", "Обучение", "Аккаунт", "Аудио", "Прогресс", "Диагностика", "Сохранить", "Назад", "Продолжить", "Отмена", "Закрыть", "Повторить", "Загрузка", "Ошибка", "Успешно", "Язык обучения", "Родной язык", "Язык интерфейса", "Аватар наставника", "Чат урока", "Тема", "Ситуация", "Уровень", "Режим разговора", "Отправить", "Начать запись", "Остановить запись", "Подсказка", "Перевод", "Показать перевод", "Скрыть перевод", "Воспроизвести голос", "Завершить урок", "Итоги", "Что получилось", "Что улучшить", "Полезные фразы", "Ошибки для повтора", "Следующие шаги", "К урокам", "Повторить урок", "Главная", "Выберите уровень", "Выберите тему", "Выберите ситуацию", "Начать урок", "Улучшить", "Премиум", "Бесплатно", "Обновить статус", "Продолжить бесплатно", "Войти", "Регистрация", "Выйти", "Email", "Пароль", "Отображаемое имя", "Текущий аккаунт", "Источник настроек", "Статус подписки", "План", "Пробный период", "Микрофон", "Проверить микрофон", "Обновить микрофоны");
    private static readonly UiTerms isTerms = new(
        "Einstellungen", "Lernen", "Konto", "Audio", "Fortschritt", "Diagnose", "Speichern", "Zurück", "Weiter", "Abbrechen", "Schließen", "Erneut versuchen", "Wird geladen", "Fehler", "Erfolg", "Lernsprache", "Muttersprache", "Sprache der Oberfläche", "Tutor-Avatar", "Lektionschat", "Thema", "Situation", "Niveau", "Konversationsmodus", "Senden", "Aufnahme starten", "Aufnahme stoppen", "Hinweis", "Übersetzung", "Übersetzung anzeigen", "Übersetzung ausblenden", "Stimme abspielen", "Lektion beenden", "Zusammenfassung", "Was gut lief", "Was verbessern", "Nützliche Sätze", "Fehler zum Wiederholen", "Nächste Schritte", "Zurück zu Lektionen", "Lektion wiederholen", "Start", "Niveau wählen", "Thema wählen", "Situation wählen", "Lektion starten", "Upgrade", "Premium", "Kostenlos", "Status aktualisieren", "Kostenlos fortfahren", "Anmelden", "Registrieren", "Abmelden", "E-Mail", "Passwort", "Anzeigename", "Aktuelles Konto", "Einstellungsquelle", "Abo-Status", "Tarif", "Testphase", "Mikrofon", "Mikrofon testen", "Mikrofone aktualisieren");
    private static readonly UiTerms gaTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms cyTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms caTerms = new(
        "Ajustes", "Aprendizaje", "Cuenta", "Audio", "Progreso", "Diagnóstico", "Guardar", "Atrás", "Continuar", "Cancelar", "Cerrar", "Reintentar", "Cargando", "Error", "Correcto", "Idioma de estudio", "Idioma nativo", "Idioma de la interfaz", "Avatar del tutor", "Chat de la lección", "Tema", "Situación", "Nivel", "Modo conversación", "Enviar", "Iniciar grabación", "Detener grabación", "Pista", "Traducción", "Mostrar traducción", "Ocultar traducción", "Reproducir voz", "Terminar lección", "Resumen", "Lo que salió bien", "Qué mejorar", "Frases útiles", "Errores para revisar", "Siguientes pasos", "Volver a lecciones", "Repetir lección", "Inicio", "Elegir nivel", "Elegir tema", "Elegir situación", "Iniciar lección", "Mejorar", "Premium", "Gratis", "Actualizar estado", "Continuar gratis", "Iniciar sesión", "Registrarse", "Cerrar sesión", "Correo", "Contraseña", "Nombre visible", "Cuenta actual", "Origen de ajustes", "Estado de suscripción", "Plan", "Prueba", "Micrófono", "Probar micrófono", "Actualizar micrófonos");
    private static readonly UiTerms euTerms = new(
        "Ajustes", "Aprendizaje", "Cuenta", "Audio", "Progreso", "Diagnóstico", "Guardar", "Atrás", "Continuar", "Cancelar", "Cerrar", "Reintentar", "Cargando", "Error", "Correcto", "Idioma de estudio", "Idioma nativo", "Idioma de la interfaz", "Avatar del tutor", "Chat de la lección", "Tema", "Situación", "Nivel", "Modo conversación", "Enviar", "Iniciar grabación", "Detener grabación", "Pista", "Traducción", "Mostrar traducción", "Ocultar traducción", "Reproducir voz", "Terminar lección", "Resumen", "Lo que salió bien", "Qué mejorar", "Frases útiles", "Errores para revisar", "Siguientes pasos", "Volver a lecciones", "Repetir lección", "Inicio", "Elegir nivel", "Elegir tema", "Elegir situación", "Iniciar lección", "Mejorar", "Premium", "Gratis", "Actualizar estado", "Continuar gratis", "Iniciar sesión", "Registrarse", "Cerrar sesión", "Correo", "Contraseña", "Nombre visible", "Cuenta actual", "Origen de ajustes", "Estado de suscripción", "Plan", "Prueba", "Micrófono", "Probar micrófono", "Actualizar micrófonos");
    private static readonly UiTerms glTerms = new(
        "Ajustes", "Aprendizaje", "Cuenta", "Audio", "Progreso", "Diagnóstico", "Guardar", "Atrás", "Continuar", "Cancelar", "Cerrar", "Reintentar", "Cargando", "Error", "Correcto", "Idioma de estudio", "Idioma nativo", "Idioma de la interfaz", "Avatar del tutor", "Chat de la lección", "Tema", "Situación", "Nivel", "Modo conversación", "Enviar", "Iniciar grabación", "Detener grabación", "Pista", "Traducción", "Mostrar traducción", "Ocultar traducción", "Reproducir voz", "Terminar lección", "Resumen", "Lo que salió bien", "Qué mejorar", "Frases útiles", "Errores para revisar", "Siguientes pasos", "Volver a lecciones", "Repetir lección", "Inicio", "Elegir nivel", "Elegir tema", "Elegir situación", "Iniciar lección", "Mejorar", "Premium", "Gratis", "Actualizar estado", "Continuar gratis", "Iniciar sesión", "Registrarse", "Cerrar sesión", "Correo", "Contraseña", "Nombre visible", "Cuenta actual", "Origen de ajustes", "Estado de suscripción", "Plan", "Prueba", "Micrófono", "Probar micrófono", "Actualizar micrófonos");
    private static readonly UiTerms mtTerms = new(
        "Impostazioni", "Apprendimento", "Account", "Audio", "Progressi", "Diagnostica", "Salva", "Indietro", "Continua", "Annulla", "Chiudi", "Riprova", "Caricamento", "Errore", "Successo", "Lingua di studio", "Lingua madre", "Lingua dell’interfaccia", "Avatar del tutor", "Chat della lezione", "Argomento", "Situazione", "Livello", "Modalità conversazione", "Invia", "Avvia registrazione", "Ferma registrazione", "Suggerimento", "Traduzione", "Mostra traduzione", "Nascondi traduzione", "Riproduci voce", "Termina lezione", "Riepilogo", "Cosa è andato bene", "Da migliorare", "Frasi utili", "Errori da rivedere", "Prossimi passi", "Torna alle lezioni", "Ripeti lezione", "Home", "Scegli livello", "Scegli argomento", "Scegli situazione", "Avvia lezione", "Upgrade", "Premium", "Gratis", "Aggiorna stato", "Continua gratis", "Accedi", "Registrati", "Esci", "Email", "Password", "Nome visualizzato", "Account attuale", "Origine impostazioni", "Stato abbonamento", "Piano", "Prova", "Microfono", "Prova microfono", "Aggiorna microfoni");
    private static readonly UiTerms lbTerms = new(
        "Einstellungen", "Lernen", "Konto", "Audio", "Fortschritt", "Diagnose", "Speichern", "Zurück", "Weiter", "Abbrechen", "Schließen", "Erneut versuchen", "Wird geladen", "Fehler", "Erfolg", "Lernsprache", "Muttersprache", "Sprache der Oberfläche", "Tutor-Avatar", "Lektionschat", "Thema", "Situation", "Niveau", "Konversationsmodus", "Senden", "Aufnahme starten", "Aufnahme stoppen", "Hinweis", "Übersetzung", "Übersetzung anzeigen", "Übersetzung ausblenden", "Stimme abspielen", "Lektion beenden", "Zusammenfassung", "Was gut lief", "Was verbessern", "Nützliche Sätze", "Fehler zum Wiederholen", "Nächste Schritte", "Zurück zu Lektionen", "Lektion wiederholen", "Start", "Niveau wählen", "Thema wählen", "Situation wählen", "Lektion starten", "Upgrade", "Premium", "Kostenlos", "Status aktualisieren", "Kostenlos fortfahren", "Anmelden", "Registrieren", "Abmelden", "E-Mail", "Passwort", "Anzeigename", "Aktuelles Konto", "Einstellungsquelle", "Abo-Status", "Tarif", "Testphase", "Mikrofon", "Mikrofon testen", "Mikrofone aktualisieren");

    private static readonly IReadOnlyDictionary<string, UiTerms> TermsByLanguageId = new Dictionary<string, UiTerms>(StringComparer.OrdinalIgnoreCase)
    {
        ["en"] = EnglishTerms,
        ["es"] = esTerms,
        ["fr"] = frTerms,
        ["de"] = deTerms,
        ["it"] = itTerms,
        ["pt"] = ptTerms,
        ["ru"] = ruTerms,
        ["uk"] = ukTerms,
        ["pl"] = plTerms,
        ["nl"] = nlTerms,
        ["tr"] = trTerms,
        ["ar"] = arTerms,
        ["hi"] = hiTerms,
        ["zh-Hans"] = zh_HansTerms,
        ["ja"] = jaTerms,
        ["ko"] = koTerms,
        ["vi"] = viTerms,
        ["id"] = idTerms,
        ["fa"] = faTerms,
        ["ur"] = urTerms,
        ["bn"] = bnTerms,
        ["ta"] = taTerms,
        ["te"] = teTerms,
        ["mr"] = mrTerms,
        ["gu"] = guTerms,
        ["th"] = thTerms,
        ["sv"] = svTerms,
        ["no"] = noTerms,
        ["da"] = daTerms,
        ["cs"] = csTerms,
        ["ro"] = roTerms,
        ["el"] = elTerms,
        ["he"] = heTerms,
        ["sr"] = srTerms,
        ["hr"] = hrTerms,
        ["bs"] = bsTerms,
        ["sl"] = slTerms,
        ["sk"] = skTerms,
        ["bg"] = bgTerms,
        ["hu"] = huTerms,
        ["fi"] = fiTerms,
        ["et"] = etTerms,
        ["lv"] = lvTerms,
        ["lt"] = ltTerms,
        ["sq"] = sqTerms,
        ["mk"] = mkTerms,
        ["be"] = beTerms,
        ["is"] = isTerms,
        ["ga"] = gaTerms,
        ["cy"] = cyTerms,
        ["ca"] = caTerms,
        ["eu"] = euTerms,
        ["gl"] = glTerms,
        ["mt"] = mtTerms,
        ["lb"] = lbTerms,
    };
}
