using EnglishVoiceTutor.Desktop.Models;
using EnglishVoiceTutor.Shared.NativeLanguages;

namespace EnglishVoiceTutor.Desktop.Localization;

public static class AppLocalization
{
    private static readonly Lazy<IReadOnlyDictionary<string, AppLocalizedText>> TextByLanguageId = new(BuildTextByLanguageId);

    public static AppLocalizedText GetText(string? languageId)
    {
        var normalizedLanguageId = NormalizeLanguageId(languageId);
        return TextByLanguageId.Value.TryGetValue(normalizedLanguageId, out var text) ? text : TextByLanguageId.Value[InterfaceLanguageOptions.EnglishId];
    }

    public static SettingsLocalizedText GetSettingsText(string? languageId) => GetText(languageId).Settings;

    public static LocalizedDisplayText GetTopicDisplayText(string? languageId, string title, string description)
    {
        return GetDisplayText(GetText(languageId).TopicDisplayTextByTitle, title, description);
    }

    public static LocalizedDisplayText GetSubtopicDisplayText(string? languageId, string title, string description)
    {
        return GetDisplayText(GetText(languageId).SubtopicDisplayTextByTitle, title, description);
    }

    public static string NormalizeLanguageId(string? languageId)
    {
        return NativeLanguageCatalog.GetByIdOrName(languageId).Id;
    }

    private static IReadOnlyDictionary<string, AppLocalizedText> BuildTextByLanguageId()
    {
        var result = new Dictionary<string, AppLocalizedText>(StringComparer.OrdinalIgnoreCase);
        foreach (var language in NativeLanguageCatalog.All)
        {
            var terms = TermsByLanguageId.TryGetValue(language.Id, out var localizedTerms) ? localizedTerms : EnglishTerms;
            result[language.Id] = CreateText(language.Id, terms);
        }
        return result;
    }

    private static AppLocalizedText CreateText(string languageId, UiTerms t)
    {
        var p = PhrasesByLanguageId.TryGetValue(languageId, out var localizedPhrases) ? localizedPhrases : EnglishPhrases;
        var settings = new SettingsLocalizedText(
            t.Settings,
            p.SettingsSubtitle,
            t.InterfaceLanguage,
            t.NativeLanguage,
            p.NativeLanguageSubtitle,
            "Connection",
            "Backend URL",
            "Used by the app to reach the local or remote backend.",
            "Your profile",
            "This helps your tutor personalize lessons.",
            "Your name",
            "Learning goal",
            t.TutorAvatar,
            p.TutorAvatarSubtitle,
            "Avatar profile",
            "Age",
            "Location",
            "Role",
            "Interests",
            "Personality",
            "Speaking style",
            t.Progress,
            "Based on completed lessons on this device.",
            "Total completed lessons",
            "Lessons completed today",
            "Current streak",
            "Last completed lesson",
            "No completed lessons yet.",
            t.Save,
            t.Back,
            p.SettingsSavedMessage,
            t.Audio,
            t.Microphone,
            "System default",
            t.TestMicrophone,
            t.RefreshMicrophones,
            "Microphone test completed.",
            "No microphone found.",
            "Selected microphone is unavailable. Using system default.",
            t.StudyLanguage,
            p.StudyLanguageSubtitle,
            t.Account,
            "Sign in or create an account to start lessons. A 7-day trial starts automatically after registration.",
            t.Email,
            t.Password,
            t.DisplayName,
            t.Register,
            t.Login,
            t.Logout,
            t.CurrentAccount,
            t.SettingsSource,
            t.SubscriptionStatus,
            t.Plan,
            t.Premium,
            t.Trial,
            "Free lesson today",
            "Enforcement",
            "Source",
            "Checked",
            t.Close,
            t.RefreshStatus,
            t.Upgrade,
            t.Diagnostics,
            t.Learning,
            t.Progress);

        return new AppLocalizedText(
            languageId, settings,
            "Practice spoken English with short AI-powered lessons.", "How the MVP works", "• Choose a topic", "• Practice by text or voice", "• Get soft corrections and hints", t.StartLesson, t.Settings, "MVP build — AI, voice, and avatar will be connected step by step.",
            t.ChooseLevel, "We will use this level later to adapt lessons and corrections.", $"{t.Level}:", "Please select a level before continuing.", t.Continue, t.Back,
            t.Home, p.HomeSubtitle, $"{t.Level}:", p.DailyLimitText, "Lesson history", t.Settings,
            $"{t.ChooseSituation} for {{0}}", "Pick a realistic scenario for your short speaking lesson.", $"{t.Topic}:", $"{t.Situation}:", "Please choose a situation before starting the lesson.", t.StartLesson,
            t.LessonChat, $"{t.Topic}:", $"{t.Situation}:", $"{t.Level}:", t.Send, t.StartRecording, t.StopRecording, t.Hint, p.AutoSendVoiceLabel, p.AutoSendVoiceToolTip, p.AutoPlayBotVoiceLabel, p.AutoPlayBotVoiceToolTip, t.FinishLesson, t.ConversationMode, "Back to chat", "Back to chat", t.ShowTranslation, t.HideTranslation, t.Translation, t.PlayVoice, "View feedback", t.Hint, "Click to close", "Feedback", "Corrected version", "Grammar tip", "Vocabulary tip", "Culture tip", "More natural version", "Translate feedback", "Hide feedback translation", "Feedback translation", "Bot status:", "Ready", "Thinking",
            "Recording... Click Stop recording when you finish.", "Could not start voice recording. Please check your microphone.", "Could not stop voice recording. Please try again.", "Transcribing your voice...", "Voice transcription is ready. Review the text and press Send.", "Could not transcribe the recording. Please try again or type your answer.", "No speech was recognized. Please try again.", "Please type your answer before sending.", "Playing AI-generated bot voice...", "Could not play bot voice. Please try again.", "Backend is unavailable. Please start the local backend and try again.", "Backend health check failed. Please start the local backend.", "Translating...", "Could not translate this text. Please try again.", "Hint: Try answering with a short complete sentence.",
            t.Summary, t.WhatWentWell, t.WhatToImprove, t.UsefulPhrases, t.BackToLessons, t.Back, "You completed a short practice dialogue and received AI feedback on your response.", "Keep practicing full sentences and apply the feedback tips to improve grammar and vocabulary.", ["Could you help me, please?", "I would like to...", "Could you repeat that, please?", "That sounds good to me."],
            "Lesson history", "Recent completed lessons on this device.", "No completed lessons yet. Finish a lesson to see it here.", BuildTopicDisplayText(t), BuildSubtopicDisplayText());
    }

    private static IReadOnlyDictionary<string, LocalizedDisplayText> BuildTopicDisplayText(UiTerms t)
    {
        return Map(("Daily Life", "Daily Life", "Small talk, introductions, and daily situations."), ("Travel", "Travel", "Airports, hotels, directions, and transport."), ("Work & Business", "Work & Business", "Meetings, emails, calls, and workplace conversations."), ("Job Interview", "Job Interview", "Practice common interview questions and answers."), ("Restaurant & Cafe", "Restaurant & Cafe", "Ordering food, booking tables, and polite requests."));
    }

    private static IReadOnlyDictionary<string, LocalizedDisplayText> BuildSubtopicDisplayText()
    {
        return Map(("Introductions", "Introductions", "Introduce yourself and ask basic personal questions."), ("Small talk with a neighbor", "Small talk with a neighbor", "Have a friendly short conversation near home."), ("Asking for help", "Asking for help", "Ask someone for help in a simple everyday situation."), ("Making plans", "Making plans", "Plan an activity and agree on time and place."), ("Talking about your day", "Talking about your day", "Describe your day and daily routine."), ("Airport check-in", "Airport check-in", "Check in for a flight and confirm travel details."), ("Hotel check-in", "Hotel check-in", "Check in at a hotel and ask common questions."), ("Asking for directions", "Asking for directions", "Ask for and understand directions in a new city."), ("Ordering transport", "Ordering transport", "Arrange a taxi or rideshare to your destination."), ("Lost luggage", "Lost luggage", "Report lost baggage and explain your situation."));
    }

    private static LocalizedDisplayText GetDisplayText(IReadOnlyDictionary<string, LocalizedDisplayText> displayTextByTitle, string title, string description)
    {
        if (!string.IsNullOrWhiteSpace(title) && displayTextByTitle.TryGetValue(title, out var displayText))
        {
            return displayText;
        }

        return new LocalizedDisplayText(title, description);
    }

    private static IReadOnlyDictionary<string, LocalizedDisplayText> Map(params (string Key, string Title, string Description)[] values)
    {
        return values.ToDictionary(value => value.Key, value => new LocalizedDisplayText(value.Title, value.Description), StringComparer.OrdinalIgnoreCase);
    }

    private sealed record UiTerms(string Settings, string Learning, string Account, string Audio, string Progress, string Diagnostics, string Save, string Back, string Continue, string Cancel, string Close, string Retry, string Loading, string Error, string Success, string StudyLanguage, string NativeLanguage, string InterfaceLanguage, string TutorAvatar, string LessonChat, string Topic, string Situation, string Level, string ConversationMode, string Send, string StartRecording, string StopRecording, string Hint, string Translation, string ShowTranslation, string HideTranslation, string PlayVoice, string FinishLesson, string Summary, string WhatWentWell, string WhatToImprove, string UsefulPhrases, string MistakesToReview, string NextSteps, string BackToLessons, string RepeatLesson, string Home, string ChooseLevel, string ChooseTopic, string ChooseSituation, string StartLesson, string Upgrade, string Premium, string Free, string RefreshStatus, string ContinueFree, string Login, string Register, string Logout, string Email, string Password, string DisplayName, string CurrentAccount, string SettingsSource, string SubscriptionStatus, string Plan, string Trial, string Microphone, string TestMicrophone, string RefreshMicrophones);

    private sealed record UiPhrases(string SettingsSubtitle, string NativeLanguageSubtitle, string TutorAvatarSubtitle, string SettingsSavedMessage, string StudyLanguageSubtitle, string HomeSubtitle, string DailyLimitText, string AutoSendVoiceLabel, string AutoSendVoiceToolTip, string AutoPlayBotVoiceLabel, string AutoPlayBotVoiceToolTip);

    private static readonly UiPhrases EnglishPhrases = new(
        "Configure your learning preferences.",
        "Translations will use this language later.",
        "Choose who will guide your lesson chat.",
        "Settings saved for this session.",
        "Choose the language you want to practice. This does not change the app UI language.",
        "Start with a practical situation and practice step by step.",
        "Free MVP limit: 3 lessons today",
        "Auto-send voice",
        "Send transcribed voice automatically after recording.",
        "Auto-play bot voice",
        "Play bot voice automatically after each reply.");

    private static readonly IReadOnlyDictionary<string, UiPhrases> PhrasesByLanguageId = new Dictionary<string, UiPhrases>(StringComparer.OrdinalIgnoreCase)
    {
        ["en"] = EnglishPhrases,
        ["es"] = new("Configura tus preferencias de aprendizaje.", "Las traducciones usarán este idioma más adelante.", "Elige quién guiará tu chat de lección.", "Ajustes guardados para esta sesión.", "Elige el idioma que quieres practicar. Esto no cambia el idioma de la interfaz.", "Empieza con una situación práctica y practica paso a paso.", "Límite gratis MVP: 3 lecciones hoy", "Enviar voz automáticamente", "Envía la voz transcrita automáticamente después de grabar.", "Reproducir voz del bot automáticamente", "Reproduce la voz del bot automáticamente después de cada respuesta."),
        ["fr"] = new("Configurez vos préférences d’apprentissage.", "Les traductions utiliseront cette langue plus tard.", "Choisissez qui guidera votre chat de leçon.", "Paramètres enregistrés pour cette session.", "Choisissez la langue à pratiquer. Cela ne change pas la langue de l’interface.", "Commencez par une situation pratique et entraînez-vous étape par étape.", "Limite MVP gratuite : 3 leçons aujourd’hui", "Envoi vocal auto", "Envoie automatiquement la voix transcrite après l’enregistrement.", "Lecture auto de la voix du bot", "Lit automatiquement la voix du bot après chaque réponse."),
        ["de"] = new("Konfiguriere deine Lernpräferenzen.", "Übersetzungen verwenden später diese Sprache.", "Wähle, wer deinen Lektionschat begleitet.", "Einstellungen für diese Sitzung gespeichert.", "Wähle die Sprache, die du üben möchtest. Das ändert nicht die Sprache der App-Oberfläche.", "Starte mit einer praktischen Situation und übe Schritt für Schritt.", "Kostenloses MVP-Limit: heute 3 Lektionen", "Sprache automatisch senden", "Sendet transkribierte Sprache nach der Aufnahme automatisch.", "Bot-Stimme automatisch abspielen", "Spielt die Bot-Stimme nach jeder Antwort automatisch ab."),
        ["it"] = new("Configura le tue preferenze di apprendimento.", "Le traduzioni useranno questa lingua più avanti.", "Scegli chi guiderà la chat della lezione.", "Impostazioni salvate per questa sessione.", "Scegli la lingua che vuoi praticare. Questo non cambia la lingua dell’interfaccia.", "Inizia con una situazione pratica e fai pratica passo dopo passo.", "Limite MVP gratis: 3 lezioni oggi", "Invio vocale automatico", "Invia automaticamente la voce trascritta dopo la registrazione.", "Riproduzione automatica voce bot", "Riproduce automaticamente la voce del bot dopo ogni risposta."),
        ["pt"] = new("Configure suas preferências de aprendizagem.", "As traduções usarão este idioma mais tarde.", "Escolha quem vai guiar o chat da lição.", "Configurações salvas para esta sessão.", "Escolha o idioma que você quer praticar. Isso não muda o idioma da interface.", "Comece com uma situação prática e pratique passo a passo.", "Limite grátis do MVP: 3 lições hoje", "Enviar voz automaticamente", "Envia a voz transcrita automaticamente após a gravação.", "Reproduzir voz do bot automaticamente", "Reproduz a voz do bot automaticamente após cada resposta."),
        ["ru"] = new("Настройте свои учебные предпочтения.", "Позже переводы будут использовать этот язык.", "Выберите, кто будет вести чат урока.", "Настройки сохранены для этой сессии.", "Выберите язык для практики. Это не меняет язык интерфейса приложения.", "Начните с практической ситуации и тренируйтесь шаг за шагом.", "Бесплатный лимит MVP: 3 урока сегодня", "Автоотправка голоса", "Автоматически отправляет распознанную речь после записи.", "Автовоспроизведение голоса бота", "Автоматически воспроизводит голос бота после каждого ответа."),
        ["pl"] = new("Skonfiguruj swoje preferencje nauki.", "Tłumaczenia będą później używać tego języka.", "Wybierz, kto poprowadzi czat lekcji.", "Ustawienia zapisane dla tej sesji.", "Wybierz język, który chcesz ćwiczyć. To nie zmienia języka interfejsu aplikacji.", "Zacznij od praktycznej sytuacji i ćwicz krok po kroku.", "Darmowy limit MVP: 3 lekcje dzisiaj", "Automatycznie wyślij głos", "Automatycznie wysyła transkrypcję głosu po nagraniu.", "Automatycznie odtwarzaj głos bota", "Automatycznie odtwarza głos bota po każdej odpowiedzi."),
        ["ar"] = new("اضبط تفضيلات التعلم الخاصة بك.", "ستستخدم الترجمات هذه اللغة لاحقًا.", "اختر من سيرشد دردشة الدرس.", "تم حفظ الإعدادات لهذه الجلسة.", "اختر اللغة التي تريد ممارستها. هذا لا يغيّر لغة واجهة التطبيق.", "ابدأ بموقف عملي وتدرّب خطوة بخطوة.", "حد MVP المجاني: 3 دروس اليوم", "إرسال الصوت تلقائيًا", "يرسل الصوت المكتوب تلقائيًا بعد التسجيل.", "تشغيل صوت البوت تلقائيًا", "يشغّل صوت البوت تلقائيًا بعد كل رد."),
        ["ja"] = new("学習設定を変更します。", "翻訳では後でこの言語を使用します。", "レッスンチャットを案内する相手を選びます。", "このセッションの設定を保存しました。", "練習したい言語を選びます。アプリの表示言語は変わりません。", "実用的な場面から始めて、段階的に練習します。", "無料MVP制限: 今日3レッスン", "音声を自動送信", "録音後、文字起こしした音声を自動で送信します。", "ボット音声を自動再生", "各返信後にボット音声を自動で再生します。"),
        ["ko"] = new("학습 설정을 구성하세요.", "번역은 나중에 이 언어를 사용합니다.", "레슨 채팅을 안내할 튜터를 선택하세요.", "이 세션의 설정이 저장되었습니다.", "연습할 언어를 선택하세요. 앱 UI 언어는 변경되지 않습니다.", "실용적인 상황으로 시작해 단계별로 연습하세요.", "무료 MVP 제한: 오늘 3개 레슨", "음성 자동 전송", "녹음 후 변환된 음성을 자동으로 보냅니다.", "봇 음성 자동 재생", "각 답변 후 봇 음성을 자동으로 재생합니다."),
        ["sr"] = new("Podesi svoje postavke učenja.", "Prevodi će kasnije koristiti ovaj jezik.", "Izaberi ko će voditi čet lekcije.", "Podešavanja su sačuvana za ovu sesiju.", "Izaberi jezik koji želiš da vežbaš. Ovo ne menja jezik interfejsa aplikacije.", "Počni sa praktičnom situacijom i vežbaj korak po korak.", "Besplatan MVP limit: 3 lekcije danas", "Automatski pošalji glas", "Automatski šalje transkribovani glas posle snimanja.", "Automatski pusti glas bota", "Automatski pušta glas bota posle svakog odgovora."),
        ["hr"] = new("Postavi svoje postavke učenja.", "Prijevodi će kasnije koristiti ovaj jezik.", "Odaberi tko će voditi chat lekcije.", "Postavke su spremljene za ovu sesiju.", "Odaberi jezik koji želiš vježbati. To ne mijenja jezik sučelja aplikacije.", "Započni s praktičnom situacijom i vježbaj korak po korak.", "Besplatni MVP limit: 3 lekcije danas", "Automatski pošalji glas", "Automatski šalje transkribirani glas nakon snimanja.", "Automatski pusti glas bota", "Automatski pušta glas bota nakon svakog odgovora."),
        ["bg"] = new("Настрой предпочитанията си за учене.", "Преводите ще използват този език по-късно.", "Избери кой ще води чата на урока.", "Настройките са запазени за тази сесия.", "Избери езика, който искаш да упражняваш. Това не променя езика на интерфейса.", "Започни с практическа ситуация и упражнявай стъпка по стъпка.", "Безплатен MVP лимит: 3 урока днес", "Автоматично изпращане на глас", "Автоматично изпраща транскрибирания глас след запис.", "Автоматично пускане на гласа на бота", "Автоматично пуска гласа на бота след всеки отговор.")
    };

    private static readonly UiTerms EnglishTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms esTerms = new(
        "Ajustes", "Aprendizaje", "Cuenta", "Audio", "Progreso", "Diagnóstico", "Guardar", "Atrás", "Continuar", "Cancelar", "Cerrar", "Reintentar", "Cargando", "Error", "Correcto", "Idioma de estudio", "Idioma nativo", "Idioma de la interfaz", "Avatar del tutor", "Chat de la lección", "Tema", "Situación", "Nivel", "Modo conversación", "Enviar", "Iniciar grabación", "Detener grabación", "Pista", "Traducción", "Mostrar traducción", "Ocultar traducción", "Reproducir voz", "Terminar lección", "Resumen", "Lo que salió bien", "Qué mejorar", "Frases útiles", "Errores para revisar", "Siguientes pasos", "Volver a lecciones", "Repetir lección", "Inicio", "Elegir nivel", "Elegir tema", "Elegir situación", "Iniciar lección", "Mejorar", "Premium", "Gratis", "Actualizar estado", "Continuar gratis", "Iniciar sesión", "Registrarse", "Cerrar sesión", "Correo", "Contraseña", "Nombre visible", "Cuenta actual", "Origen de ajustes", "Estado de suscripción", "Plan", "Prueba", "Micrófono", "Probar micrófono", "Actualizar micrófonos");
    private static readonly UiTerms frTerms = new(
        "Paramètres", "Apprentissage", "Compte", "Audio", "Progrès", "Diagnostic", "Enregistrer", "Retour", "Continuer", "Annuler", "Fermer", "Réessayer", "Chargement", "Erreur", "Succès", "Langue d’étude", "Langue maternelle", "Langue de l’interface", "Avatar du tuteur", "Chat de leçon", "Sujet", "Situation", "Niveau", "Mode conversation", "Envoyer", "Démarrer l’enregistrement", "Arrêter l’enregistrement", "Indice", "Traduction", "Afficher la traduction", "Masquer la traduction", "Lire la voix", "Terminer la leçon", "Résumé", "Ce qui a bien marché", "À améliorer", "Phrases utiles", "Erreurs à revoir", "Étapes suivantes", "Retour aux leçons", "Répéter la leçon", "Accueil", "Choisir le niveau", "Choisir le sujet", "Choisir la situation", "Démarrer la leçon", "Mettre à niveau", "Premium", "Gratuit", "Actualiser le statut", "Continuer gratuitement", "Connexion", "Inscription", "Déconnexion", "E-mail", "Mot de passe", "Nom affiché", "Compte actuel", "Source des paramètres", "Statut de l’abonnement", "Forfait", "Essai", "Microphone", "Tester le microphone", "Actualiser les microphones");
    private static readonly UiTerms deTerms = new(
        "Einstellungen", "Lernen", "Konto", "Audio", "Fortschritt", "Diagnose", "Speichern", "Zurück", "Weiter", "Abbrechen", "Schließen", "Erneut versuchen", "Wird geladen", "Fehler", "Erfolg", "Lernsprache", "Muttersprache", "Sprache der Oberfläche", "Tutor-Avatar", "Lektionschat", "Thema", "Situation", "Niveau", "Konversationsmodus", "Senden", "Aufnahme starten", "Aufnahme stoppen", "Hinweis", "Übersetzung", "Übersetzung anzeigen", "Übersetzung ausblenden", "Stimme abspielen", "Lektion beenden", "Zusammenfassung", "Was gut lief", "Was verbessern", "Nützliche Sätze", "Fehler zum Wiederholen", "Nächste Schritte", "Zurück zu Lektionen", "Lektion wiederholen", "Start", "Niveau wählen", "Thema wählen", "Situation wählen", "Lektion starten", "Upgrade", "Premium", "Kostenlos", "Status aktualisieren", "Kostenlos fortfahren", "Anmelden", "Registrieren", "Abmelden", "E-Mail", "Passwort", "Anzeigename", "Aktuelles Konto", "Einstellungsquelle", "Abo-Status", "Tarif", "Testphase", "Mikrofon", "Mikrofon testen", "Mikrofone aktualisieren");
    private static readonly UiTerms itTerms = new(
        "Impostazioni", "Apprendimento", "Account", "Audio", "Progressi", "Diagnostica", "Salva", "Indietro", "Continua", "Annulla", "Chiudi", "Riprova", "Caricamento", "Errore", "Successo", "Lingua di studio", "Lingua madre", "Lingua dell’interfaccia", "Avatar del tutor", "Chat della lezione", "Argomento", "Situazione", "Livello", "Modalità conversazione", "Invia", "Avvia registrazione", "Ferma registrazione", "Suggerimento", "Traduzione", "Mostra traduzione", "Nascondi traduzione", "Riproduci voce", "Termina lezione", "Riepilogo", "Cosa è andato bene", "Da migliorare", "Frasi utili", "Errori da rivedere", "Prossimi passi", "Torna alle lezioni", "Ripeti lezione", "Home", "Scegli livello", "Scegli argomento", "Scegli situazione", "Avvia lezione", "Upgrade", "Premium", "Gratis", "Aggiorna stato", "Continua gratis", "Accedi", "Registrati", "Esci", "Email", "Password", "Nome visualizzato", "Account attuale", "Origine impostazioni", "Stato abbonamento", "Piano", "Prova", "Microfono", "Prova microfono", "Aggiorna microfoni");
    private static readonly UiTerms ptTerms = new(
        "Configurações", "Aprendizagem", "Conta", "Áudio", "Progresso", "Diagnóstico", "Salvar", "Voltar", "Continuar", "Cancelar", "Fechar", "Tentar novamente", "Carregando", "Erro", "Sucesso", "Idioma de estudo", "Idioma nativo", "Idioma da interface", "Avatar do tutor", "Chat da aula", "Tema", "Situação", "Nível", "Modo conversa", "Enviar", "Iniciar gravação", "Parar gravação", "Dica", "Tradução", "Mostrar tradução", "Ocultar tradução", "Reproduzir voz", "Concluir aula", "Resumo", "O que foi bem", "O que melhorar", "Frases úteis", "Erros para revisar", "Próximos passos", "Voltar às aulas", "Repetir aula", "Início", "Escolher nível", "Escolher tema", "Escolher situação", "Iniciar aula", "Upgrade", "Premium", "Grátis", "Atualizar status", "Continuar grátis", "Entrar", "Registrar", "Sair", "Email", "Senha", "Nome exibido", "Conta atual", "Origem das configurações", "Status da assinatura", "Plano", "Teste", "Microfone", "Testar microfone", "Atualizar microfones");
    private static readonly UiTerms ruTerms = new(
        "Настройки", "Обучение", "Аккаунт", "Аудио", "Прогресс", "Диагностика", "Сохранить", "Назад", "Продолжить", "Отмена", "Закрыть", "Повторить", "Загрузка", "Ошибка", "Успешно", "Язык обучения", "Родной язык", "Язык интерфейса", "Аватар наставника", "Чат урока", "Тема", "Ситуация", "Уровень", "Режим разговора", "Отправить", "Начать запись", "Остановить запись", "Подсказка", "Перевод", "Показать перевод", "Скрыть перевод", "Воспроизвести голос", "Завершить урок", "Итоги", "Что получилось", "Что улучшить", "Полезные фразы", "Ошибки для повтора", "Следующие шаги", "К урокам", "Повторить урок", "Главная", "Выберите уровень", "Выберите тему", "Выберите ситуацию", "Начать урок", "Улучшить", "Премиум", "Бесплатно", "Обновить статус", "Продолжить бесплатно", "Войти", "Регистрация", "Выйти", "Email", "Пароль", "Отображаемое имя", "Текущий аккаунт", "Источник настроек", "Статус подписки", "План", "Пробный период", "Микрофон", "Проверить микрофон", "Обновить микрофоны");
    private static readonly UiTerms ukTerms = new(
        "Настройки", "Обучение", "Аккаунт", "Аудио", "Прогресс", "Диагностика", "Сохранить", "Назад", "Продолжить", "Отмена", "Закрыть", "Повторить", "Загрузка", "Ошибка", "Успешно", "Язык обучения", "Родной язык", "Язык интерфейса", "Аватар наставника", "Чат урока", "Тема", "Ситуация", "Уровень", "Режим разговора", "Отправить", "Начать запись", "Остановить запись", "Подсказка", "Перевод", "Показать перевод", "Скрыть перевод", "Воспроизвести голос", "Завершить урок", "Итоги", "Что получилось", "Что улучшить", "Полезные фразы", "Ошибки для повтора", "Следующие шаги", "К урокам", "Повторить урок", "Главная", "Выберите уровень", "Выберите тему", "Выберите ситуацию", "Начать урок", "Улучшить", "Премиум", "Бесплатно", "Обновить статус", "Продолжить бесплатно", "Войти", "Регистрация", "Выйти", "Email", "Пароль", "Отображаемое имя", "Текущий аккаунт", "Источник настроек", "Статус подписки", "План", "Пробный период", "Микрофон", "Проверить микрофон", "Обновить микрофоны");
    private static readonly UiTerms plTerms = new(
        "Ustawienia", "Nauka", "Konto", "Audio", "Postępy", "Diagnostyka", "Zapisz", "Wstecz", "Kontynuuj", "Anuluj", "Zamknij", "Spróbuj ponownie", "Ładowanie", "Błąd", "Sukces", "Język nauki", "Język ojczysty", "Język interfejsu", "Awatar tutora", "Czat lekcji", "Temat", "Sytuacja", "Poziom", "Tryb rozmowy", "Wyślij", "Rozpocznij nagrywanie", "Zatrzymaj nagrywanie", "Wskazówka", "Tłumaczenie", "Pokaż tłumaczenie", "Ukryj tłumaczenie", "Odtwórz głos", "Zakończ lekcję", "Podsumowanie", "Co poszło dobrze", "Co poprawić", "Przydatne zwroty", "Błędy do powtórki", "Następne kroki", "Wróć do lekcji", "Powtórz lekcję", "Strona główna", "Wybierz poziom", "Wybierz temat", "Wybierz sytuację", "Rozpocznij lekcję", "Ulepsz", "Premium", "Bezpłatnie", "Odśwież status", "Kontynuuj bezpłatnie", "Zaloguj", "Zarejestruj", "Wyloguj", "E-mail", "Hasło", "Nazwa wyświetlana", "Bieżące konto", "Źródło ustawień", "Status subskrypcji", "Plan", "Okres próbny", "Mikrofon", "Testuj mikrofon", "Odśwież mikrofony");
    private static readonly UiTerms nlTerms = new(
        "Einstellungen", "Lernen", "Konto", "Audio", "Fortschritt", "Diagnose", "Speichern", "Zurück", "Weiter", "Abbrechen", "Schließen", "Erneut versuchen", "Wird geladen", "Fehler", "Erfolg", "Lernsprache", "Muttersprache", "Sprache der Oberfläche", "Tutor-Avatar", "Lektionschat", "Thema", "Situation", "Niveau", "Konversationsmodus", "Senden", "Aufnahme starten", "Aufnahme stoppen", "Hinweis", "Übersetzung", "Übersetzung anzeigen", "Übersetzung ausblenden", "Stimme abspielen", "Lektion beenden", "Zusammenfassung", "Was gut lief", "Was verbessern", "Nützliche Sätze", "Fehler zum Wiederholen", "Nächste Schritte", "Zurück zu Lektionen", "Lektion wiederholen", "Start", "Niveau wählen", "Thema wählen", "Situation wählen", "Lektion starten", "Upgrade", "Premium", "Kostenlos", "Status aktualisieren", "Kostenlos fortfahren", "Anmelden", "Registrieren", "Abmelden", "E-Mail", "Passwort", "Anzeigename", "Aktuelles Konto", "Einstellungsquelle", "Abo-Status", "Tarif", "Testphase", "Mikrofon", "Mikrofon testen", "Mikrofone aktualisieren");
    private static readonly UiTerms trTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms arTerms = new(
        "الإعدادات", "التعلّم", "الحساب", "الصوت", "التقدّم", "التشخيص", "حفظ", "رجوع", "متابعة", "إلغاء", "إغلاق", "إعادة المحاولة", "جارٍ التحميل", "خطأ", "نجاح", "لغة الدراسة", "اللغة الأم", "لغة الواجهة", "صورة المعلّم", "دردشة الدرس", "الموضوع", "الموقف", "المستوى", "وضع المحادثة", "إرسال", "بدء التسجيل", "إيقاف التسجيل", "تلميح", "ترجمة", "إظهار الترجمة", "إخفاء الترجمة", "تشغيل الصوت", "إنهاء الدرس", "ملخص", "ما سار جيدًا", "ما يجب تحسينه", "عبارات مفيدة", "أخطاء للمراجعة", "الخطوات التالية", "العودة إلى الدروس", "إعادة الدرس", "الرئيسية", "اختر المستوى", "اختر الموضوع", "اختر الموقف", "ابدأ الدرس", "ترقية", "مميز", "مجاني", "تحديث الحالة", "المتابعة بالخطة المجانية", "تسجيل الدخول", "تسجيل", "تسجيل الخروج", "البريد الإلكتروني", "كلمة المرور", "اسم العرض", "الحساب الحالي", "مصدر الإعدادات", "حالة الاشتراك", "الخطة", "تجربة", "الميكروفون", "اختبار الميكروفون", "تحديث الميكروفونات");
    private static readonly UiTerms hiTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms zh_HansTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms jaTerms = new(
        "設定", "学習", "アカウント", "音声", "進捗", "診断", "保存", "戻る", "続ける", "キャンセル", "閉じる", "再試行", "読み込み中", "エラー", "成功", "学習言語", "母語", "表示言語", "チューターアバター", "レッスンチャット", "トピック", "場面", "レベル", "会話モード", "送信", "録音開始", "録音停止", "ヒント", "翻訳", "翻訳を表示", "翻訳を非表示", "音声を再生", "レッスン終了", "まとめ", "良かった点", "改善点", "便利なフレーズ", "復習する間違い", "次のステップ", "レッスンに戻る", "レッスンを繰り返す", "ホーム", "レベルを選ぶ", "トピックを選ぶ", "場面を選ぶ", "レッスン開始", "アップグレード", "プレミアム", "無料", "状態を更新", "無料プランで続ける", "ログイン", "登録", "ログアウト", "メール", "パスワード", "表示名", "現在のアカウント", "設定元", "サブスクリプション状態", "プラン", "トライアル", "マイク", "マイクをテスト", "マイクを更新");
    private static readonly UiTerms koTerms = new(
        "설정", "학습", "계정", "오디오", "진행률", "진단", "저장", "뒤로", "계속", "취소", "닫기", "다시 시도", "로딩 중", "오류", "성공", "학습 언어", "모국어", "인터페이스 언어", "튜터 아바타", "레슨 채팅", "주제", "상황", "레벨", "대화 모드", "보내기", "녹음 시작", "녹음 중지", "힌트", "번역", "번역 보기", "번역 숨기기", "음성 재생", "레슨 끝내기", "요약", "잘한 점", "개선할 점", "유용한 표현", "복습할 실수", "다음 단계", "레슨으로 돌아가기", "레슨 반복", "홈", "레벨 선택", "주제 선택", "상황 선택", "레슨 시작", "업그레이드", "프리미엄", "무료", "상태 새로고침", "무료 플랜으로 계속", "로그인", "가입", "로그아웃", "이메일", "비밀번호", "표시 이름", "현재 계정", "설정 원본", "구독 상태", "플랜", "체험", "마이크", "마이크 테스트", "마이크 새로고침");
    private static readonly UiTerms viTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms idTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms faTerms = new(
        "الإعدادات", "التعلّم", "الحساب", "الصوت", "التقدّم", "التشخيص", "حفظ", "رجوع", "متابعة", "إلغاء", "إغلاق", "إعادة المحاولة", "جارٍ التحميل", "خطأ", "نجاح", "لغة الدراسة", "اللغة الأم", "لغة الواجهة", "صورة المعلّم", "دردشة الدرس", "الموضوع", "الموقف", "المستوى", "وضع المحادثة", "إرسال", "بدء التسجيل", "إيقاف التسجيل", "تلميح", "ترجمة", "إظهار الترجمة", "إخفاء الترجمة", "تشغيل الصوت", "إنهاء الدرس", "ملخص", "ما سار جيدًا", "ما يجب تحسينه", "عبارات مفيدة", "أخطاء للمراجعة", "الخطوات التالية", "العودة إلى الدروس", "إعادة الدرس", "الرئيسية", "اختر المستوى", "اختر الموضوع", "اختر الموقف", "ابدأ الدرس", "ترقية", "مميز", "مجاني", "تحديث الحالة", "المتابعة بالخطة المجانية", "تسجيل الدخول", "تسجيل", "تسجيل الخروج", "البريد الإلكتروني", "كلمة المرور", "اسم العرض", "الحساب الحالي", "مصدر الإعدادات", "حالة الاشتراك", "الخطة", "تجربة", "الميكروفون", "اختبار الميكروفون", "تحديث الميكروفونات");
    private static readonly UiTerms urTerms = new(
        "الإعدادات", "التعلّم", "الحساب", "الصوت", "التقدّم", "التشخيص", "حفظ", "رجوع", "متابعة", "إلغاء", "إغلاق", "إعادة المحاولة", "جارٍ التحميل", "خطأ", "نجاح", "لغة الدراسة", "اللغة الأم", "لغة الواجهة", "صورة المعلّم", "دردشة الدرس", "الموضوع", "الموقف", "المستوى", "وضع المحادثة", "إرسال", "بدء التسجيل", "إيقاف التسجيل", "تلميح", "ترجمة", "إظهار الترجمة", "إخفاء الترجمة", "تشغيل الصوت", "إنهاء الدرس", "ملخص", "ما سار جيدًا", "ما يجب تحسينه", "عبارات مفيدة", "أخطاء للمراجعة", "الخطوات التالية", "العودة إلى الدروس", "إعادة الدرس", "الرئيسية", "اختر المستوى", "اختر الموضوع", "اختر الموقف", "ابدأ الدرس", "ترقية", "مميز", "مجاني", "تحديث الحالة", "المتابعة بالخطة المجانية", "تسجيل الدخول", "تسجيل", "تسجيل الخروج", "البريد الإلكتروني", "كلمة المرور", "اسم العرض", "الحساب الحالي", "مصدر الإعدادات", "حالة الاشتراك", "الخطة", "تجربة", "الميكروفون", "اختبار الميكروفون", "تحديث الميكروفونات");
    private static readonly UiTerms bnTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms taTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms teTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms mrTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms guTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms thTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms svTerms = new(
        "Einstellungen", "Lernen", "Konto", "Audio", "Fortschritt", "Diagnose", "Speichern", "Zurück", "Weiter", "Abbrechen", "Schließen", "Erneut versuchen", "Wird geladen", "Fehler", "Erfolg", "Lernsprache", "Muttersprache", "Sprache der Oberfläche", "Tutor-Avatar", "Lektionschat", "Thema", "Situation", "Niveau", "Konversationsmodus", "Senden", "Aufnahme starten", "Aufnahme stoppen", "Hinweis", "Übersetzung", "Übersetzung anzeigen", "Übersetzung ausblenden", "Stimme abspielen", "Lektion beenden", "Zusammenfassung", "Was gut lief", "Was verbessern", "Nützliche Sätze", "Fehler zum Wiederholen", "Nächste Schritte", "Zurück zu Lektionen", "Lektion wiederholen", "Start", "Niveau wählen", "Thema wählen", "Situation wählen", "Lektion starten", "Upgrade", "Premium", "Kostenlos", "Status aktualisieren", "Kostenlos fortfahren", "Anmelden", "Registrieren", "Abmelden", "E-Mail", "Passwort", "Anzeigename", "Aktuelles Konto", "Einstellungsquelle", "Abo-Status", "Tarif", "Testphase", "Mikrofon", "Mikrofon testen", "Mikrofone aktualisieren");
    private static readonly UiTerms noTerms = new(
        "Einstellungen", "Lernen", "Konto", "Audio", "Fortschritt", "Diagnose", "Speichern", "Zurück", "Weiter", "Abbrechen", "Schließen", "Erneut versuchen", "Wird geladen", "Fehler", "Erfolg", "Lernsprache", "Muttersprache", "Sprache der Oberfläche", "Tutor-Avatar", "Lektionschat", "Thema", "Situation", "Niveau", "Konversationsmodus", "Senden", "Aufnahme starten", "Aufnahme stoppen", "Hinweis", "Übersetzung", "Übersetzung anzeigen", "Übersetzung ausblenden", "Stimme abspielen", "Lektion beenden", "Zusammenfassung", "Was gut lief", "Was verbessern", "Nützliche Sätze", "Fehler zum Wiederholen", "Nächste Schritte", "Zurück zu Lektionen", "Lektion wiederholen", "Start", "Niveau wählen", "Thema wählen", "Situation wählen", "Lektion starten", "Upgrade", "Premium", "Kostenlos", "Status aktualisieren", "Kostenlos fortfahren", "Anmelden", "Registrieren", "Abmelden", "E-Mail", "Passwort", "Anzeigename", "Aktuelles Konto", "Einstellungsquelle", "Abo-Status", "Tarif", "Testphase", "Mikrofon", "Mikrofon testen", "Mikrofone aktualisieren");
    private static readonly UiTerms daTerms = new(
        "Einstellungen", "Lernen", "Konto", "Audio", "Fortschritt", "Diagnose", "Speichern", "Zurück", "Weiter", "Abbrechen", "Schließen", "Erneut versuchen", "Wird geladen", "Fehler", "Erfolg", "Lernsprache", "Muttersprache", "Sprache der Oberfläche", "Tutor-Avatar", "Lektionschat", "Thema", "Situation", "Niveau", "Konversationsmodus", "Senden", "Aufnahme starten", "Aufnahme stoppen", "Hinweis", "Übersetzung", "Übersetzung anzeigen", "Übersetzung ausblenden", "Stimme abspielen", "Lektion beenden", "Zusammenfassung", "Was gut lief", "Was verbessern", "Nützliche Sätze", "Fehler zum Wiederholen", "Nächste Schritte", "Zurück zu Lektionen", "Lektion wiederholen", "Start", "Niveau wählen", "Thema wählen", "Situation wählen", "Lektion starten", "Upgrade", "Premium", "Kostenlos", "Status aktualisieren", "Kostenlos fortfahren", "Anmelden", "Registrieren", "Abmelden", "E-Mail", "Passwort", "Anzeigename", "Aktuelles Konto", "Einstellungsquelle", "Abo-Status", "Tarif", "Testphase", "Mikrofon", "Mikrofon testen", "Mikrofone aktualisieren");
    private static readonly UiTerms csTerms = new(
        "Ustawienia", "Nauka", "Konto", "Audio", "Postępy", "Diagnostyka", "Zapisz", "Wstecz", "Kontynuuj", "Anuluj", "Zamknij", "Spróbuj ponownie", "Ładowanie", "Błąd", "Sukces", "Język nauki", "Język ojczysty", "Język interfejsu", "Awatar tutora", "Czat lekcji", "Temat", "Sytuacja", "Poziom", "Tryb rozmowy", "Wyślij", "Rozpocznij nagrywanie", "Zatrzymaj nagrywanie", "Wskazówka", "Tłumaczenie", "Pokaż tłumaczenie", "Ukryj tłumaczenie", "Odtwórz głos", "Zakończ lekcję", "Podsumowanie", "Co poszło dobrze", "Co poprawić", "Przydatne zwroty", "Błędy do powtórki", "Następne kroki", "Wróć do lekcji", "Powtórz lekcję", "Strona główna", "Wybierz poziom", "Wybierz temat", "Wybierz sytuację", "Rozpocznij lekcję", "Ulepsz", "Premium", "Bezpłatnie", "Odśwież status", "Kontynuuj bezpłatnie", "Zaloguj", "Zarejestruj", "Wyloguj", "E-mail", "Hasło", "Nazwa wyświetlana", "Bieżące konto", "Źródło ustawień", "Status subskrypcji", "Plan", "Okres próbny", "Mikrofon", "Testuj mikrofon", "Odśwież mikrofony");
    private static readonly UiTerms roTerms = new(
        "Impostazioni", "Apprendimento", "Account", "Audio", "Progressi", "Diagnostica", "Salva", "Indietro", "Continua", "Annulla", "Chiudi", "Riprova", "Caricamento", "Errore", "Successo", "Lingua di studio", "Lingua madre", "Lingua dell’interfaccia", "Avatar del tutor", "Chat della lezione", "Argomento", "Situazione", "Livello", "Modalità conversazione", "Invia", "Avvia registrazione", "Ferma registrazione", "Suggerimento", "Traduzione", "Mostra traduzione", "Nascondi traduzione", "Riproduci voce", "Termina lezione", "Riepilogo", "Cosa è andato bene", "Da migliorare", "Frasi utili", "Errori da rivedere", "Prossimi passi", "Torna alle lezioni", "Ripeti lezione", "Home", "Scegli livello", "Scegli argomento", "Scegli situazione", "Avvia lezione", "Upgrade", "Premium", "Gratis", "Aggiorna stato", "Continua gratis", "Accedi", "Registrati", "Esci", "Email", "Password", "Nome visualizzato", "Account attuale", "Origine impostazioni", "Stato abbonamento", "Piano", "Prova", "Microfono", "Prova microfono", "Aggiorna microfoni");
    private static readonly UiTerms elTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms heTerms = new(
        "الإعدادات", "التعلّم", "الحساب", "الصوت", "التقدّم", "التشخيص", "حفظ", "رجوع", "متابعة", "إلغاء", "إغلاق", "إعادة المحاولة", "جارٍ التحميل", "خطأ", "نجاح", "لغة الدراسة", "اللغة الأم", "لغة الواجهة", "صورة المعلّم", "دردشة الدرس", "الموضوع", "الموقف", "المستوى", "وضع المحادثة", "إرسال", "بدء التسجيل", "إيقاف التسجيل", "تلميح", "ترجمة", "إظهار الترجمة", "إخفاء الترجمة", "تشغيل الصوت", "إنهاء الدرس", "ملخص", "ما سار جيدًا", "ما يجب تحسينه", "عبارات مفيدة", "أخطاء للمراجعة", "الخطوات التالية", "العودة إلى الدروس", "إعادة الدرس", "الرئيسية", "اختر المستوى", "اختر الموضوع", "اختر الموقف", "ابدأ الدرس", "ترقية", "مميز", "مجاني", "تحديث الحالة", "المتابعة بالخطة المجانية", "تسجيل الدخول", "تسجيل", "تسجيل الخروج", "البريد الإلكتروني", "كلمة المرور", "اسم العرض", "الحساب الحالي", "مصدر الإعدادات", "حالة الاشتراك", "الخطة", "تجربة", "الميكروفون", "اختبار الميكروفون", "تحديث الميكروفونات");
    private static readonly UiTerms srTerms = new(
        "Podešavanja", "Učenje", "Nalog", "Audio", "Napredak", "Dijagnostika", "Sačuvaj", "Nazad", "Nastavi", "Otkaži", "Zatvori", "Pokušaj ponovo", "Učitavanje", "Greška", "Uspeh", "Jezik učenja", "Maternji jezik", "Jezik interfejsa", "Avatar tutora", "Čet lekcije", "Tema", "Situacija", "Nivo", "Režim razgovora", "Pošalji", "Pokreni snimanje", "Zaustavi snimanje", "Nagoveštaj", "Prevod", "Prikaži prevod", "Sakrij prevod", "Pusti glas", "Završi lekciju", "Sažetak", "Šta je bilo dobro", "Šta poboljšati", "Korisne fraze", "Greške za pregled", "Sledeći koraci", "Nazad na lekcije", "Ponovi lekciju", "Početna", "Izaberi nivo", "Izaberi temu", "Izaberi situaciju", "Počni lekciju", "Nadogradi", "Premium", "Besplatno", "Osveži status", "Nastavi besplatno", "Prijava", "Registracija", "Odjava", "E-pošta", "Lozinka", "Prikazano ime", "Trenutni nalog", "Izvor podešavanja", "Status pretplate", "Plan", "Probni period", "Mikrofon", "Testiraj mikrofon", "Osveži mikrofone");
    private static readonly UiTerms hrTerms = new(
        "Postavke", "Učenje", "Račun", "Audio", "Napredak", "Dijagnostika", "Spremi", "Natrag", "Nastavi", "Odustani", "Zatvori", "Pokušaj ponovno", "Učitavanje", "Pogreška", "Uspjeh", "Jezik učenja", "Materinski jezik", "Jezik sučelja", "Avatar tutora", "Chat lekcije", "Tema", "Situacija", "Razina", "Način razgovora", "Pošalji", "Pokreni snimanje", "Zaustavi snimanje", "Savjet", "Prijevod", "Prikaži prijevod", "Sakrij prijevod", "Pusti glas", "Završi lekciju", "Sažetak", "Što je bilo dobro", "Što poboljšati", "Korisne fraze", "Pogreške za pregled", "Sljedeći koraci", "Natrag na lekcije", "Ponovi lekciju", "Početna", "Odaberi razinu", "Odaberi temu", "Odaberi situaciju", "Pokreni lekciju", "Nadogradi", "Premium", "Besplatno", "Osvježi status", "Nastavi besplatno", "Prijava", "Registracija", "Odjava", "E-pošta", "Lozinka", "Prikazano ime", "Trenutni račun", "Izvor postavki", "Status pretplate", "Plan", "Probno", "Mikrofon", "Testiraj mikrofon", "Osvježi mikrofone");
    private static readonly UiTerms bsTerms = new(
        "Postavke", "Učenje", "Račun", "Audio", "Napredak", "Dijagnostika", "Spremi", "Natrag", "Nastavi", "Odustani", "Zatvori", "Pokušaj ponovno", "Učitavanje", "Pogreška", "Uspjeh", "Jezik učenja", "Materinski jezik", "Jezik sučelja", "Avatar tutora", "Chat lekcije", "Tema", "Situacija", "Razina", "Način razgovora", "Pošalji", "Pokreni snimanje", "Zaustavi snimanje", "Savjet", "Prijevod", "Prikaži prijevod", "Sakrij prijevod", "Pusti glas", "Završi lekciju", "Sažetak", "Što je bilo dobro", "Što poboljšati", "Korisne fraze", "Pogreške za pregled", "Sljedeći koraci", "Natrag na lekcije", "Ponovi lekciju", "Početna", "Odaberi razinu", "Odaberi temu", "Odaberi situaciju", "Pokreni lekciju", "Nadogradi", "Premium", "Besplatno", "Osvježi status", "Nastavi besplatno", "Prijava", "Registracija", "Odjava", "E-pošta", "Lozinka", "Prikazano ime", "Trenutni račun", "Izvor postavki", "Status pretplate", "Plan", "Probno", "Mikrofon", "Testiraj mikrofon", "Osvježi mikrofone");
    private static readonly UiTerms slTerms = new(
        "Postavke", "Učenje", "Račun", "Audio", "Napredak", "Dijagnostika", "Spremi", "Natrag", "Nastavi", "Odustani", "Zatvori", "Pokušaj ponovno", "Učitavanje", "Pogreška", "Uspjeh", "Jezik učenja", "Materinski jezik", "Jezik sučelja", "Avatar tutora", "Chat lekcije", "Tema", "Situacija", "Razina", "Način razgovora", "Pošalji", "Pokreni snimanje", "Zaustavi snimanje", "Savjet", "Prijevod", "Prikaži prijevod", "Sakrij prijevod", "Pusti glas", "Završi lekciju", "Sažetak", "Što je bilo dobro", "Što poboljšati", "Korisne fraze", "Pogreške za pregled", "Sljedeći koraci", "Natrag na lekcije", "Ponovi lekciju", "Početna", "Odaberi razinu", "Odaberi temu", "Odaberi situaciju", "Pokreni lekciju", "Nadogradi", "Premium", "Besplatno", "Osvježi status", "Nastavi besplatno", "Prijava", "Registracija", "Odjava", "E-pošta", "Lozinka", "Prikazano ime", "Trenutni račun", "Izvor postavki", "Status pretplate", "Plan", "Probno", "Mikrofon", "Testiraj mikrofon", "Osvježi mikrofone");
    private static readonly UiTerms skTerms = new(
        "Ustawienia", "Nauka", "Konto", "Audio", "Postępy", "Diagnostyka", "Zapisz", "Wstecz", "Kontynuuj", "Anuluj", "Zamknij", "Spróbuj ponownie", "Ładowanie", "Błąd", "Sukces", "Język nauki", "Język ojczysty", "Język interfejsu", "Awatar tutora", "Czat lekcji", "Temat", "Sytuacja", "Poziom", "Tryb rozmowy", "Wyślij", "Rozpocznij nagrywanie", "Zatrzymaj nagrywanie", "Wskazówka", "Tłumaczenie", "Pokaż tłumaczenie", "Ukryj tłumaczenie", "Odtwórz głos", "Zakończ lekcję", "Podsumowanie", "Co poszło dobrze", "Co poprawić", "Przydatne zwroty", "Błędy do powtórki", "Następne kroki", "Wróć do lekcji", "Powtórz lekcję", "Strona główna", "Wybierz poziom", "Wybierz temat", "Wybierz sytuację", "Rozpocznij lekcję", "Ulepsz", "Premium", "Bezpłatnie", "Odśwież status", "Kontynuuj bezpłatnie", "Zaloguj", "Zarejestruj", "Wyloguj", "E-mail", "Hasło", "Nazwa wyświetlana", "Bieżące konto", "Źródło ustawień", "Status subskrypcji", "Plan", "Okres próbny", "Mikrofon", "Testuj mikrofon", "Odśwież mikrofony");
    private static readonly UiTerms bgTerms = new(
        "Настройки", "Учене", "Акаунт", "Аудио", "Напредък", "Диагностика", "Запази", "Назад", "Продължи", "Отказ", "Затвори", "Опитай пак", "Зареждане", "Грешка", "Успех", "Език за учене", "Роден език", "Език на интерфейса", "Аватар на тутора", "Чат на урока", "Тема", "Ситуация", "Ниво", "Режим разговор", "Изпрати", "Започни запис", "Спри запис", "Подсказка", "Превод", "Покажи превод", "Скрий превод", "Пусни глас", "Завърши урока", "Обобщение", "Какво беше добре", "Какво да подобриш", "Полезни фрази", "Грешки за преглед", "Следващи стъпки", "Назад към уроците", "Повтори урока", "Начало", "Избери ниво", "Избери тема", "Избери ситуация", "Започни урок", "Надгради", "Премиум", "Безплатно", "Обнови статус", "Продължи безплатно", "Вход", "Регистрация", "Изход", "Имейл", "Парола", "Показвано име", "Текущ акаунт", "Източник на настройки", "Статус на абонамента", "План", "Пробен период", "Микрофон", "Тествай микрофона", "Обнови микрофоните");
    private static readonly UiTerms huTerms = new(
        "Einstellungen", "Lernen", "Konto", "Audio", "Fortschritt", "Diagnose", "Speichern", "Zurück", "Weiter", "Abbrechen", "Schließen", "Erneut versuchen", "Wird geladen", "Fehler", "Erfolg", "Lernsprache", "Muttersprache", "Sprache der Oberfläche", "Tutor-Avatar", "Lektionschat", "Thema", "Situation", "Niveau", "Konversationsmodus", "Senden", "Aufnahme starten", "Aufnahme stoppen", "Hinweis", "Übersetzung", "Übersetzung anzeigen", "Übersetzung ausblenden", "Stimme abspielen", "Lektion beenden", "Zusammenfassung", "Was gut lief", "Was verbessern", "Nützliche Sätze", "Fehler zum Wiederholen", "Nächste Schritte", "Zurück zu Lektionen", "Lektion wiederholen", "Start", "Niveau wählen", "Thema wählen", "Situation wählen", "Lektion starten", "Upgrade", "Premium", "Kostenlos", "Status aktualisieren", "Kostenlos fortfahren", "Anmelden", "Registrieren", "Abmelden", "E-Mail", "Passwort", "Anzeigename", "Aktuelles Konto", "Einstellungsquelle", "Abo-Status", "Tarif", "Testphase", "Mikrofon", "Mikrofon testen", "Mikrofone aktualisieren");
    private static readonly UiTerms fiTerms = new(
        "Einstellungen", "Lernen", "Konto", "Audio", "Fortschritt", "Diagnose", "Speichern", "Zurück", "Weiter", "Abbrechen", "Schließen", "Erneut versuchen", "Wird geladen", "Fehler", "Erfolg", "Lernsprache", "Muttersprache", "Sprache der Oberfläche", "Tutor-Avatar", "Lektionschat", "Thema", "Situation", "Niveau", "Konversationsmodus", "Senden", "Aufnahme starten", "Aufnahme stoppen", "Hinweis", "Übersetzung", "Übersetzung anzeigen", "Übersetzung ausblenden", "Stimme abspielen", "Lektion beenden", "Zusammenfassung", "Was gut lief", "Was verbessern", "Nützliche Sätze", "Fehler zum Wiederholen", "Nächste Schritte", "Zurück zu Lektionen", "Lektion wiederholen", "Start", "Niveau wählen", "Thema wählen", "Situation wählen", "Lektion starten", "Upgrade", "Premium", "Kostenlos", "Status aktualisieren", "Kostenlos fortfahren", "Anmelden", "Registrieren", "Abmelden", "E-Mail", "Passwort", "Anzeigename", "Aktuelles Konto", "Einstellungsquelle", "Abo-Status", "Tarif", "Testphase", "Mikrofon", "Mikrofon testen", "Mikrofone aktualisieren");
    private static readonly UiTerms etTerms = new(
        "Einstellungen", "Lernen", "Konto", "Audio", "Fortschritt", "Diagnose", "Speichern", "Zurück", "Weiter", "Abbrechen", "Schließen", "Erneut versuchen", "Wird geladen", "Fehler", "Erfolg", "Lernsprache", "Muttersprache", "Sprache der Oberfläche", "Tutor-Avatar", "Lektionschat", "Thema", "Situation", "Niveau", "Konversationsmodus", "Senden", "Aufnahme starten", "Aufnahme stoppen", "Hinweis", "Übersetzung", "Übersetzung anzeigen", "Übersetzung ausblenden", "Stimme abspielen", "Lektion beenden", "Zusammenfassung", "Was gut lief", "Was verbessern", "Nützliche Sätze", "Fehler zum Wiederholen", "Nächste Schritte", "Zurück zu Lektionen", "Lektion wiederholen", "Start", "Niveau wählen", "Thema wählen", "Situation wählen", "Lektion starten", "Upgrade", "Premium", "Kostenlos", "Status aktualisieren", "Kostenlos fortfahren", "Anmelden", "Registrieren", "Abmelden", "E-Mail", "Passwort", "Anzeigename", "Aktuelles Konto", "Einstellungsquelle", "Abo-Status", "Tarif", "Testphase", "Mikrofon", "Mikrofon testen", "Mikrofone aktualisieren");
    private static readonly UiTerms lvTerms = new(
        "Ustawienia", "Nauka", "Konto", "Audio", "Postępy", "Diagnostyka", "Zapisz", "Wstecz", "Kontynuuj", "Anuluj", "Zamknij", "Spróbuj ponownie", "Ładowanie", "Błąd", "Sukces", "Język nauki", "Język ojczysty", "Język interfejsu", "Awatar tutora", "Czat lekcji", "Temat", "Sytuacja", "Poziom", "Tryb rozmowy", "Wyślij", "Rozpocznij nagrywanie", "Zatrzymaj nagrywanie", "Wskazówka", "Tłumaczenie", "Pokaż tłumaczenie", "Ukryj tłumaczenie", "Odtwórz głos", "Zakończ lekcję", "Podsumowanie", "Co poszło dobrze", "Co poprawić", "Przydatne zwroty", "Błędy do powtórki", "Następne kroki", "Wróć do lekcji", "Powtórz lekcję", "Strona główna", "Wybierz poziom", "Wybierz temat", "Wybierz sytuację", "Rozpocznij lekcję", "Ulepsz", "Premium", "Bezpłatnie", "Odśwież status", "Kontynuuj bezpłatnie", "Zaloguj", "Zarejestruj", "Wyloguj", "E-mail", "Hasło", "Nazwa wyświetlana", "Bieżące konto", "Źródło ustawień", "Status subskrypcji", "Plan", "Okres próbny", "Mikrofon", "Testuj mikrofon", "Odśwież mikrofony");
    private static readonly UiTerms ltTerms = new(
        "Ustawienia", "Nauka", "Konto", "Audio", "Postępy", "Diagnostyka", "Zapisz", "Wstecz", "Kontynuuj", "Anuluj", "Zamknij", "Spróbuj ponownie", "Ładowanie", "Błąd", "Sukces", "Język nauki", "Język ojczysty", "Język interfejsu", "Awatar tutora", "Czat lekcji", "Temat", "Sytuacja", "Poziom", "Tryb rozmowy", "Wyślij", "Rozpocznij nagrywanie", "Zatrzymaj nagrywanie", "Wskazówka", "Tłumaczenie", "Pokaż tłumaczenie", "Ukryj tłumaczenie", "Odtwórz głos", "Zakończ lekcję", "Podsumowanie", "Co poszło dobrze", "Co poprawić", "Przydatne zwroty", "Błędy do powtórki", "Następne kroki", "Wróć do lekcji", "Powtórz lekcję", "Strona główna", "Wybierz poziom", "Wybierz temat", "Wybierz sytuację", "Rozpocznij lekcję", "Ulepsz", "Premium", "Bezpłatnie", "Odśwież status", "Kontynuuj bezpłatnie", "Zaloguj", "Zarejestruj", "Wyloguj", "E-mail", "Hasło", "Nazwa wyświetlana", "Bieżące konto", "Źródło ustawień", "Status subskrypcji", "Plan", "Okres próbny", "Mikrofon", "Testuj mikrofon", "Odśwież mikrofony");
    private static readonly UiTerms sqTerms = new(
        "Impostazioni", "Apprendimento", "Account", "Audio", "Progressi", "Diagnostica", "Salva", "Indietro", "Continua", "Annulla", "Chiudi", "Riprova", "Caricamento", "Errore", "Successo", "Lingua di studio", "Lingua madre", "Lingua dell’interfaccia", "Avatar del tutor", "Chat della lezione", "Argomento", "Situazione", "Livello", "Modalità conversazione", "Invia", "Avvia registrazione", "Ferma registrazione", "Suggerimento", "Traduzione", "Mostra traduzione", "Nascondi traduzione", "Riproduci voce", "Termina lezione", "Riepilogo", "Cosa è andato bene", "Da migliorare", "Frasi utili", "Errori da rivedere", "Prossimi passi", "Torna alle lezioni", "Ripeti lezione", "Home", "Scegli livello", "Scegli argomento", "Scegli situazione", "Avvia lezione", "Upgrade", "Premium", "Gratis", "Aggiorna stato", "Continua gratis", "Accedi", "Registrati", "Esci", "Email", "Password", "Nome visualizzato", "Account attuale", "Origine impostazioni", "Stato abbonamento", "Piano", "Prova", "Microfono", "Prova microfono", "Aggiorna microfoni");
    private static readonly UiTerms mkTerms = new(
        "Настройки", "Учене", "Акаунт", "Аудио", "Напредък", "Диагностика", "Запази", "Назад", "Продължи", "Отказ", "Затвори", "Опитай пак", "Зареждане", "Грешка", "Успех", "Език за учене", "Роден език", "Език на интерфейса", "Аватар на тутора", "Чат на урока", "Тема", "Ситуация", "Ниво", "Режим разговор", "Изпрати", "Започни запис", "Спри запис", "Подсказка", "Превод", "Покажи превод", "Скрий превод", "Пусни глас", "Завърши урока", "Обобщение", "Какво беше добре", "Какво да подобриш", "Полезни фрази", "Грешки за преглед", "Следващи стъпки", "Назад към уроците", "Повтори урока", "Начало", "Избери ниво", "Избери тема", "Избери ситуация", "Започни урок", "Надгради", "Премиум", "Безплатно", "Обнови статус", "Продължи безплатно", "Вход", "Регистрация", "Изход", "Имейл", "Парола", "Показвано име", "Текущ акаунт", "Източник на настройки", "Статус на абонамента", "План", "Пробен период", "Микрофон", "Тествай микрофона", "Обнови микрофоните");
    private static readonly UiTerms beTerms = new(
        "Настройки", "Обучение", "Аккаунт", "Аудио", "Прогресс", "Диагностика", "Сохранить", "Назад", "Продолжить", "Отмена", "Закрыть", "Повторить", "Загрузка", "Ошибка", "Успешно", "Язык обучения", "Родной язык", "Язык интерфейса", "Аватар наставника", "Чат урока", "Тема", "Ситуация", "Уровень", "Режим разговора", "Отправить", "Начать запись", "Остановить запись", "Подсказка", "Перевод", "Показать перевод", "Скрыть перевод", "Воспроизвести голос", "Завершить урок", "Итоги", "Что получилось", "Что улучшить", "Полезные фразы", "Ошибки для повтора", "Следующие шаги", "К урокам", "Повторить урок", "Главная", "Выберите уровень", "Выберите тему", "Выберите ситуацию", "Начать урок", "Улучшить", "Премиум", "Бесплатно", "Обновить статус", "Продолжить бесплатно", "Войти", "Регистрация", "Выйти", "Email", "Пароль", "Отображаемое имя", "Текущий аккаунт", "Источник настроек", "Статус подписки", "План", "Пробный период", "Микрофон", "Проверить микрофон", "Обновить микрофоны");
    private static readonly UiTerms isTerms = new(
        "Einstellungen", "Lernen", "Konto", "Audio", "Fortschritt", "Diagnose", "Speichern", "Zurück", "Weiter", "Abbrechen", "Schließen", "Erneut versuchen", "Wird geladen", "Fehler", "Erfolg", "Lernsprache", "Muttersprache", "Sprache der Oberfläche", "Tutor-Avatar", "Lektionschat", "Thema", "Situation", "Niveau", "Konversationsmodus", "Senden", "Aufnahme starten", "Aufnahme stoppen", "Hinweis", "Übersetzung", "Übersetzung anzeigen", "Übersetzung ausblenden", "Stimme abspielen", "Lektion beenden", "Zusammenfassung", "Was gut lief", "Was verbessern", "Nützliche Sätze", "Fehler zum Wiederholen", "Nächste Schritte", "Zurück zu Lektionen", "Lektion wiederholen", "Start", "Niveau wählen", "Thema wählen", "Situation wählen", "Lektion starten", "Upgrade", "Premium", "Kostenlos", "Status aktualisieren", "Kostenlos fortfahren", "Anmelden", "Registrieren", "Abmelden", "E-Mail", "Passwort", "Anzeigename", "Aktuelles Konto", "Einstellungsquelle", "Abo-Status", "Tarif", "Testphase", "Mikrofon", "Mikrofon testen", "Mikrofone aktualisieren");
    private static readonly UiTerms gaTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms cyTerms = new(
        "Settings", "Learning", "Account", "Audio", "Progress", "Diagnostics", "Save", "Back", "Continue", "Cancel", "Close", "Retry", "Loading", "Error", "Success", "Study language", "Native language", "Interface language", "Tutor avatar", "Lesson chat", "Topic", "Situation", "Level", "Conversation mode", "Send", "Start recording", "Stop recording", "Hint", "Translation", "Show translation", "Hide translation", "Play voice", "Finish lesson", "Summary", "What went well", "What to improve", "Useful phrases", "Mistakes to review", "Next steps", "Back to lessons", "Repeat lesson", "Home", "Choose level", "Choose topic", "Choose situation", "Start lesson", "Upgrade", "Premium", "Free", "Refresh status", "Continue with free plan", "Login", "Register", "Logout", "Email", "Password", "Display name", "Current account", "Settings source", "Subscription status", "Plan", "Trial", "Microphone", "Test microphone", "Refresh microphones");
    private static readonly UiTerms caTerms = new(
        "Ajustes", "Aprendizaje", "Cuenta", "Audio", "Progreso", "Diagnóstico", "Guardar", "Atrás", "Continuar", "Cancelar", "Cerrar", "Reintentar", "Cargando", "Error", "Correcto", "Idioma de estudio", "Idioma nativo", "Idioma de la interfaz", "Avatar del tutor", "Chat de la lección", "Tema", "Situación", "Nivel", "Modo conversación", "Enviar", "Iniciar grabación", "Detener grabación", "Pista", "Traducción", "Mostrar traducción", "Ocultar traducción", "Reproducir voz", "Terminar lección", "Resumen", "Lo que salió bien", "Qué mejorar", "Frases útiles", "Errores para revisar", "Siguientes pasos", "Volver a lecciones", "Repetir lección", "Inicio", "Elegir nivel", "Elegir tema", "Elegir situación", "Iniciar lección", "Mejorar", "Premium", "Gratis", "Actualizar estado", "Continuar gratis", "Iniciar sesión", "Registrarse", "Cerrar sesión", "Correo", "Contraseña", "Nombre visible", "Cuenta actual", "Origen de ajustes", "Estado de suscripción", "Plan", "Prueba", "Micrófono", "Probar micrófono", "Actualizar micrófonos");
    private static readonly UiTerms euTerms = new(
        "Ajustes", "Aprendizaje", "Cuenta", "Audio", "Progreso", "Diagnóstico", "Guardar", "Atrás", "Continuar", "Cancelar", "Cerrar", "Reintentar", "Cargando", "Error", "Correcto", "Idioma de estudio", "Idioma nativo", "Idioma de la interfaz", "Avatar del tutor", "Chat de la lección", "Tema", "Situación", "Nivel", "Modo conversación", "Enviar", "Iniciar grabación", "Detener grabación", "Pista", "Traducción", "Mostrar traducción", "Ocultar traducción", "Reproducir voz", "Terminar lección", "Resumen", "Lo que salió bien", "Qué mejorar", "Frases útiles", "Errores para revisar", "Siguientes pasos", "Volver a lecciones", "Repetir lección", "Inicio", "Elegir nivel", "Elegir tema", "Elegir situación", "Iniciar lección", "Mejorar", "Premium", "Gratis", "Actualizar estado", "Continuar gratis", "Iniciar sesión", "Registrarse", "Cerrar sesión", "Correo", "Contraseña", "Nombre visible", "Cuenta actual", "Origen de ajustes", "Estado de suscripción", "Plan", "Prueba", "Micrófono", "Probar micrófono", "Actualizar micrófonos");
    private static readonly UiTerms glTerms = new(
        "Ajustes", "Aprendizaje", "Cuenta", "Audio", "Progreso", "Diagnóstico", "Guardar", "Atrás", "Continuar", "Cancelar", "Cerrar", "Reintentar", "Cargando", "Error", "Correcto", "Idioma de estudio", "Idioma nativo", "Idioma de la interfaz", "Avatar del tutor", "Chat de la lección", "Tema", "Situación", "Nivel", "Modo conversación", "Enviar", "Iniciar grabación", "Detener grabación", "Pista", "Traducción", "Mostrar traducción", "Ocultar traducción", "Reproducir voz", "Terminar lección", "Resumen", "Lo que salió bien", "Qué mejorar", "Frases útiles", "Errores para revisar", "Siguientes pasos", "Volver a lecciones", "Repetir lección", "Inicio", "Elegir nivel", "Elegir tema", "Elegir situación", "Iniciar lección", "Mejorar", "Premium", "Gratis", "Actualizar estado", "Continuar gratis", "Iniciar sesión", "Registrarse", "Cerrar sesión", "Correo", "Contraseña", "Nombre visible", "Cuenta actual", "Origen de ajustes", "Estado de suscripción", "Plan", "Prueba", "Micrófono", "Probar micrófono", "Actualizar micrófonos");
    private static readonly UiTerms mtTerms = new(
        "Impostazioni", "Apprendimento", "Account", "Audio", "Progressi", "Diagnostica", "Salva", "Indietro", "Continua", "Annulla", "Chiudi", "Riprova", "Caricamento", "Errore", "Successo", "Lingua di studio", "Lingua madre", "Lingua dell’interfaccia", "Avatar del tutor", "Chat della lezione", "Argomento", "Situazione", "Livello", "Modalità conversazione", "Invia", "Avvia registrazione", "Ferma registrazione", "Suggerimento", "Traduzione", "Mostra traduzione", "Nascondi traduzione", "Riproduci voce", "Termina lezione", "Riepilogo", "Cosa è andato bene", "Da migliorare", "Frasi utili", "Errori da rivedere", "Prossimi passi", "Torna alle lezioni", "Ripeti lezione", "Home", "Scegli livello", "Scegli argomento", "Scegli situazione", "Avvia lezione", "Upgrade", "Premium", "Gratis", "Aggiorna stato", "Continua gratis", "Accedi", "Registrati", "Esci", "Email", "Password", "Nome visualizzato", "Account attuale", "Origine impostazioni", "Stato abbonamento", "Piano", "Prova", "Microfono", "Prova microfono", "Aggiorna microfoni");
    private static readonly UiTerms lbTerms = new(
        "Einstellungen", "Lernen", "Konto", "Audio", "Fortschritt", "Diagnose", "Speichern", "Zurück", "Weiter", "Abbrechen", "Schließen", "Erneut versuchen", "Wird geladen", "Fehler", "Erfolg", "Lernsprache", "Muttersprache", "Sprache der Oberfläche", "Tutor-Avatar", "Lektionschat", "Thema", "Situation", "Niveau", "Konversationsmodus", "Senden", "Aufnahme starten", "Aufnahme stoppen", "Hinweis", "Übersetzung", "Übersetzung anzeigen", "Übersetzung ausblenden", "Stimme abspielen", "Lektion beenden", "Zusammenfassung", "Was gut lief", "Was verbessern", "Nützliche Sätze", "Fehler zum Wiederholen", "Nächste Schritte", "Zurück zu Lektionen", "Lektion wiederholen", "Start", "Niveau wählen", "Thema wählen", "Situation wählen", "Lektion starten", "Upgrade", "Premium", "Kostenlos", "Status aktualisieren", "Kostenlos fortfahren", "Anmelden", "Registrieren", "Abmelden", "E-Mail", "Passwort", "Anzeigename", "Aktuelles Konto", "Einstellungsquelle", "Abo-Status", "Tarif", "Testphase", "Mikrofon", "Mikrofon testen", "Mikrofone aktualisieren");

    private static readonly IReadOnlyDictionary<string, UiTerms> TermsByLanguageId = new Dictionary<string, UiTerms>(StringComparer.OrdinalIgnoreCase)
    {
        ["en"] = EnglishTerms,
        ["es"] = esTerms,
        ["fr"] = frTerms,
        ["de"] = deTerms,
        ["it"] = itTerms,
        ["pt"] = ptTerms,
        ["ru"] = ruTerms,
        ["uk"] = ukTerms,
        ["pl"] = plTerms,
        ["nl"] = nlTerms,
        ["tr"] = trTerms,
        ["ar"] = arTerms,
        ["hi"] = hiTerms,
        ["zh-Hans"] = zh_HansTerms,
        ["ja"] = jaTerms,
        ["ko"] = koTerms,
        ["vi"] = viTerms,
        ["id"] = idTerms,
        ["fa"] = faTerms,
        ["ur"] = urTerms,
        ["bn"] = bnTerms,
        ["ta"] = taTerms,
        ["te"] = teTerms,
        ["mr"] = mrTerms,
        ["gu"] = guTerms,
        ["th"] = thTerms,
        ["sv"] = svTerms,
        ["no"] = noTerms,
        ["da"] = daTerms,
        ["cs"] = csTerms,
        ["ro"] = roTerms,
        ["el"] = elTerms,
        ["he"] = heTerms,
        ["sr"] = srTerms,
        ["hr"] = hrTerms,
        ["bs"] = bsTerms,
        ["sl"] = slTerms,
        ["sk"] = skTerms,
        ["bg"] = bgTerms,
        ["hu"] = huTerms,
        ["fi"] = fiTerms,
        ["et"] = etTerms,
        ["lv"] = lvTerms,
        ["lt"] = ltTerms,
        ["sq"] = sqTerms,
        ["mk"] = mkTerms,
        ["be"] = beTerms,
        ["is"] = isTerms,
        ["ga"] = gaTerms,
        ["cy"] = cyTerms,
        ["ca"] = caTerms,
        ["eu"] = euTerms,
        ["gl"] = glTerms,
        ["mt"] = mtTerms,
        ["lb"] = lbTerms,
    };
}
