namespace EnglishVoiceTutor.Desktop.Localization;

public sealed record BackendUxLocalizedText(
    string BackendUnavailable,
    string CouldNotConnect,
    string ActionNeedsBackend,
    string BackendReturnedError,
    string BackendValidationError,
    string BackendRequestTimedOut,
    string BackendUnexpectedResponse,
    string SettingsLoadUnavailable,
    string SettingsSaveUnavailable,
    string LoginFailed,
    string RegisterFailed,
    string SignedIn,
    string SignedOut,
    string SessionRestored,
    string SessionExpired,
    string CredentialsRequired,
    string DisplayNameRequired,
    string VoiceTakingTooLong,
    string VoicePlaybackUnavailable,
    string ActiveLessonExists,
    string ActiveLessonExistsTitle,
    string ActiveLessonExistsMessage,
    string EndOtherLessonAndContinue,
    string Cancel,
    string EndOtherLessonFailed,
    string LessonSessionEndedElsewhere,
    string EmailRequired = "Email is required.",
    string ResetCodeRequired = "Reset code is required.",
    string CurrentPasswordRequired = "Current password is required.",
    string PasswordTooShort = "Password must be at least 8 characters.",
    string PasswordResetRequested = "Password reset instructions were sent if this email is registered.",
    string PasswordResetRequestFailed = "Could not request password reset. Please try again.",
    string PasswordResetFieldsRequired = "Reset code and new password are required.",
    string PasswordsDoNotMatch = "New passwords do not match.",
    string PasswordResetConfirmed = "Password updated.",
    string PasswordResetConfirmFailed = "Password reset code is invalid or expired.",
    string SignInRequired = "Please sign in first.",
    string PasswordChangeFieldsRequired = "Current password, new password, and confirmation are required.",
    string PasswordChanged = "Password updated.",
    string PasswordChangeFailed = "Password could not be updated. Check your current password and try again.",
    string CurrentPasswordIncorrect = "Current password is incorrect.");
