using EnglishVoiceTutor.Desktop.Models;

namespace EnglishVoiceTutor.Desktop.Localization;

public static class BackendUxLocalization
{
    public static readonly IReadOnlyList<string> RequiredMessageKeys =
    [
        nameof(BackendUxLocalizedText.BackendUnavailable),
        nameof(BackendUxLocalizedText.CouldNotConnect),
        nameof(BackendUxLocalizedText.ActionNeedsBackend),
        nameof(BackendUxLocalizedText.BackendReturnedError),
        nameof(BackendUxLocalizedText.BackendValidationError),
        nameof(BackendUxLocalizedText.BackendRequestTimedOut),
        nameof(BackendUxLocalizedText.BackendUnexpectedResponse),
        nameof(BackendUxLocalizedText.SettingsLoadUnavailable),
        nameof(BackendUxLocalizedText.SettingsSaveUnavailable),
        nameof(BackendUxLocalizedText.LoginFailed),
        nameof(BackendUxLocalizedText.RegisterFailed),
        nameof(BackendUxLocalizedText.SignedIn),
        nameof(BackendUxLocalizedText.SignedOut),
        nameof(BackendUxLocalizedText.SessionRestored),
        nameof(BackendUxLocalizedText.SessionExpired),
        nameof(BackendUxLocalizedText.CredentialsRequired),
        nameof(BackendUxLocalizedText.DisplayNameRequired),
        nameof(BackendUxLocalizedText.VoiceTakingTooLong),
        nameof(BackendUxLocalizedText.VoicePlaybackUnavailable),
        nameof(BackendUxLocalizedText.ActiveLessonExists),
        nameof(BackendUxLocalizedText.ActiveLessonExistsTitle),
        nameof(BackendUxLocalizedText.ActiveLessonExistsMessage),
        nameof(BackendUxLocalizedText.EndOtherLessonAndContinue),
        nameof(BackendUxLocalizedText.Cancel),
        nameof(BackendUxLocalizedText.EndOtherLessonFailed)
    ];

    private static readonly IReadOnlyDictionary<string, BackendUxLocalizedText> TextByLanguageId = new Dictionary<string, BackendUxLocalizedText>(StringComparer.OrdinalIgnoreCase)
    {
        ["en"] = new(
            "Backend is unavailable. Please start the local backend and try again.",
            "Could not connect to the server. Please check that the backend is running.",
            "This action needs the backend. Please try again after the server is available.",
            "The server returned an error. Please try again.",
            "The request could not be completed. Please review your input and try again.",
            "The request took too long. Please try again.",
            "The server response could not be read. Please try again.",
            "Could not load settings from the backend. Local settings are still available.",
            "Local settings were saved, but the backend could not be updated.",
            "Login failed. Check your email and password.",
            "Registration failed. Please review your details and try again.",
            "Signed in.",
            "Signed out.",
            "Session restored.",
            "Session expired. Using local development settings.",
            "Email and password are required.",
            "Display name is required for registration.",
            "Voice is taking too long. Please try again.",
            "Voice playback is unavailable. You can continue by reading the message.",
            "You have not finished a lesson on another device yet. Finish that lesson and try again.",
            "Active lesson on another device",
            "You already have an active lesson on another device. To continue here, end the lesson on that device first.",
            "End lesson on another device and continue",
            "Cancel",
            "Could not end the lesson on another device. Please try again."),
        ["es"] = new(
            "El backend no está disponible. Inicia el backend local e inténtalo de nuevo.",
            "No se pudo conectar con el servidor. Comprueba que el backend esté en ejecución.",
            "Esta acción necesita el backend. Inténtalo de nuevo cuando el servidor esté disponible.",
            "El servidor devolvió un error. Inténtalo de nuevo.",
            "No se pudo completar la solicitud. Revisa los datos e inténtalo de nuevo.",
            "La solicitud tardó demasiado. Inténtalo de nuevo.",
            "No se pudo leer la respuesta del servidor. Inténtalo de nuevo.",
            "No se pudieron cargar los ajustes desde el backend. Los ajustes locales siguen disponibles.",
            "Los ajustes locales se guardaron, pero el backend no se pudo actualizar.",
            "No se pudo iniciar sesión. Revisa el correo y la contraseña.",
            "No se pudo registrar la cuenta. Revisa los datos e inténtalo de nuevo.",
            "Sesión iniciada.",
            "Sesión cerrada.",
            "Sesión restaurada.",
            "La sesión caducó. Usando ajustes locales de desarrollo.",
            "El correo y la contraseña son obligatorios.",
            "El nombre visible es obligatorio para registrarse.",
            "La voz está tardando demasiado. Inténtalo de nuevo.",
            "La reproducción de voz no está disponible. Puedes continuar leyendo el mensaje.",
            "Aún no has terminado una lección en otro dispositivo. Termina esa lección e inténtalo de nuevo.",
            "Lección activa en otro dispositivo",
            "Ya tienes una lección activa en otro dispositivo. Para continuar aquí, termina la lección en ese dispositivo primero.",
            "Terminar la lección en otro dispositivo y continuar",
            "Cancelar",
            "No se pudo terminar la lección en otro dispositivo. Inténtalo de nuevo."),
        ["fr"] = new(
            "Le backend est indisponible. Démarrez le backend local puis réessayez.",
            "Impossible de se connecter au serveur. Vérifiez que le backend fonctionne.",
            "Cette action nécessite le backend. Réessayez quand le serveur sera disponible.",
            "Le serveur a renvoyé une erreur. Réessayez.",
            "La demande n’a pas pu être terminée. Vérifiez vos informations puis réessayez.",
            "La demande a pris trop de temps. Réessayez.",
            "La réponse du serveur n’a pas pu être lue. Réessayez.",
            "Impossible de charger les paramètres depuis le backend. Les paramètres locaux restent disponibles.",
            "Les paramètres locaux ont été enregistrés, mais le backend n’a pas pu être mis à jour.",
            "Échec de la connexion. Vérifiez l’e-mail et le mot de passe.",
            "Échec de l’inscription. Vérifiez vos informations puis réessayez.",
            "Connecté.",
            "Déconnecté.",
            "Session restaurée.",
            "Session expirée. Utilisation des paramètres locaux de développement.",
            "L’e-mail et le mot de passe sont obligatoires.",
            "Le nom d’affichage est obligatoire pour l’inscription.",
            "La voix prend trop de temps. Réessayez.",
            "La lecture vocale est indisponible. Vous pouvez continuer en lisant le message.",
            "Vous n’avez pas encore terminé une leçon sur un autre appareil. Terminez cette leçon et réessayez.",
            "Leçon active sur un autre appareil",
            "Vous avez déjà une leçon active sur un autre appareil. Pour continuer ici, terminez d’abord la leçon sur cet appareil.",
            "Terminer la leçon sur un autre appareil et continuer",
            "Annuler",
            "Impossible de terminer la leçon sur un autre appareil. Réessayez."),
        ["de"] = new(
            "Das Backend ist nicht verfügbar. Starte das lokale Backend und versuche es erneut.",
            "Keine Verbindung zum Server möglich. Prüfe, ob das Backend läuft.",
            "Diese Aktion benötigt das Backend. Versuche es erneut, wenn der Server verfügbar ist.",
            "Der Server hat einen Fehler zurückgegeben. Versuche es erneut.",
            "Die Anfrage konnte nicht abgeschlossen werden. Prüfe deine Eingaben und versuche es erneut.",
            "Die Anfrage hat zu lange gedauert. Versuche es erneut.",
            "Die Serverantwort konnte nicht gelesen werden. Versuche es erneut.",
            "Einstellungen konnten nicht vom Backend geladen werden. Lokale Einstellungen bleiben verfügbar.",
            "Lokale Einstellungen wurden gespeichert, aber das Backend konnte nicht aktualisiert werden.",
            "Anmeldung fehlgeschlagen. Prüfe E-Mail und Passwort.",
            "Registrierung fehlgeschlagen. Prüfe deine Angaben und versuche es erneut.",
            "Angemeldet.",
            "Abgemeldet.",
            "Sitzung wiederhergestellt.",
            "Sitzung abgelaufen. Lokale Entwicklungseinstellungen werden verwendet.",
            "E-Mail und Passwort sind erforderlich.",
            "Für die Registrierung ist ein Anzeigename erforderlich.",
            "Die Sprachausgabe dauert zu lange. Versuche es erneut.",
            "Sprachwiedergabe ist nicht verfügbar. Du kannst mit dem Lesen der Nachricht fortfahren.",
            "Du hast eine Lektion auf einem anderen Gerät noch nicht beendet. Beende diese Lektion und versuche es erneut.",
            "Aktive Lektion auf einem anderen Gerät",
            "Du hast bereits eine aktive Lektion auf einem anderen Gerät. Um hier fortzufahren, beende zuerst die Lektion auf diesem Gerät.",
            "Lektion auf anderem Gerät beenden und fortfahren",
            "Abbrechen",
            "Die Lektion auf dem anderen Gerät konnte nicht beendet werden. Bitte versuche es erneut."),
        ["it"] = new(
            "Il backend non è disponibile. Avvia il backend locale e riprova.",
            "Impossibile connettersi al server. Verifica che il backend sia in esecuzione.",
            "Questa azione richiede il backend. Riprova quando il server è disponibile.",
            "Il server ha restituito un errore. Riprova.",
            "La richiesta non è stata completata. Controlla i dati e riprova.",
            "La richiesta ha impiegato troppo tempo. Riprova.",
            "Impossibile leggere la risposta del server. Riprova.",
            "Impossibile caricare le impostazioni dal backend. Le impostazioni locali restano disponibili.",
            "Le impostazioni locali sono state salvate, ma il backend non è stato aggiornato.",
            "Accesso non riuscito. Controlla email e password.",
            "Registrazione non riuscita. Controlla i dati e riprova.",
            "Accesso effettuato.",
            "Disconnesso.",
            "Sessione ripristinata.",
            "Sessione scaduta. Uso delle impostazioni locali di sviluppo.",
            "Email e password sono obbligatorie.",
            "Il nome visualizzato è obbligatorio per la registrazione.",
            "La voce sta impiegando troppo tempo. Riprova.",
            "La riproduzione vocale non è disponibile. Puoi continuare leggendo il messaggio.",
            "Non hai ancora terminato una lezione su un altro dispositivo. Termina quella lezione e riprova.",
            "Lezione attiva su un altro dispositivo",
            "Hai già una lezione attiva su un altro dispositivo. Per continuare qui, termina prima la lezione su quel dispositivo.",
            "Termina la lezione su un altro dispositivo e continua",
            "Annulla",
            "Impossibile terminare la lezione sull’altro dispositivo. Riprova."),
        ["pt"] = new(
            "O backend está indisponível. Inicie o backend local e tente novamente.",
            "Não foi possível conectar ao servidor. Verifique se o backend está em execução.",
            "Esta ação precisa do backend. Tente novamente quando o servidor estiver disponível.",
            "O servidor retornou um erro. Tente novamente.",
            "A solicitação não pôde ser concluída. Revise os dados e tente novamente.",
            "A solicitação demorou demais. Tente novamente.",
            "Não foi possível ler a resposta do servidor. Tente novamente.",
            "Não foi possível carregar as configurações do backend. As configurações locais continuam disponíveis.",
            "As configurações locais foram salvas, mas o backend não pôde ser atualizado.",
            "Falha no login. Verifique o e-mail e a senha.",
            "Falha no registro. Revise seus dados e tente novamente.",
            "Sessão iniciada.",
            "Sessão encerrada.",
            "Sessão restaurada.",
            "Sessão expirada. Usando configurações locais de desenvolvimento.",
            "E-mail e senha são obrigatórios.",
            "O nome de exibição é obrigatório para o registro.",
            "A voz está demorando demais. Tente novamente.",
            "A reprodução de voz está indisponível. Você pode continuar lendo a mensagem.",
            "Você ainda não terminou uma lição em outro dispositivo. Termine essa lição e tente novamente.",
            "Lição ativa em outro dispositivo",
            "Você já tem uma lição ativa em outro dispositivo. Para continuar aqui, encerre primeiro a lição nesse dispositivo.",
            "Encerrar a lição em outro dispositivo e continuar",
            "Cancelar",
            "Não foi possível encerrar a lição no outro dispositivo. Tente novamente."),
        ["ru"] = new(
            "Бэкенд недоступен. Запустите локальный бэкенд и попробуйте снова.",
            "Не удалось подключиться к серверу. Проверьте, что бэкенд запущен.",
            "Для этого действия нужен бэкенд. Повторите попытку, когда сервер будет доступен.",
            "Сервер вернул ошибку. Попробуйте снова.",
            "Не удалось выполнить запрос. Проверьте данные и попробуйте снова.",
            "Запрос выполнялся слишком долго. Попробуйте снова.",
            "Не удалось прочитать ответ сервера. Попробуйте снова.",
            "Не удалось загрузить настройки из бэкенда. Локальные настройки всё ещё доступны.",
            "Локальные настройки сохранены, но бэкенд не удалось обновить.",
            "Не удалось войти. Проверьте email и пароль.",
            "Не удалось зарегистрироваться. Проверьте данные и попробуйте снова.",
            "Вход выполнен.",
            "Вы вышли из аккаунта.",
            "Сессия восстановлена.",
            "Сессия истекла. Используются локальные настройки разработки.",
            "Email и пароль обязательны.",
            "Отображаемое имя обязательно для регистрации.",
            "Голос загружается слишком долго. Попробуйте снова.",
            "Воспроизведение голоса недоступно. Вы можете продолжить, прочитав сообщение.",
            "Вы ещё не закончили урок на другом устройстве. Завершите урок на том устройстве и попробуйте снова.",
            "Урок открыт на другом устройстве",
            "У вас уже открыт урок на другом устройстве. Чтобы продолжить здесь, завершите урок на другом устройстве.",
            "Завершить урок на другом устройстве и продолжить",
            "Отмена",
            "Не удалось завершить урок на другом устройстве. Попробуйте ещё раз."),
        ["pl"] = new(
            "Backend jest niedostępny. Uruchom lokalny backend i spróbuj ponownie.",
            "Nie można połączyć się z serwerem. Sprawdź, czy backend działa.",
            "Ta akcja wymaga backendu. Spróbuj ponownie, gdy serwer będzie dostępny.",
            "Serwer zwrócił błąd. Spróbuj ponownie.",
            "Nie udało się ukończyć żądania. Sprawdź dane i spróbuj ponownie.",
            "Żądanie trwało zbyt długo. Spróbuj ponownie.",
            "Nie można odczytać odpowiedzi serwera. Spróbuj ponownie.",
            "Nie udało się załadować ustawień z backendu. Ustawienia lokalne są nadal dostępne.",
            "Ustawienia lokalne zapisano, ale nie udało się zaktualizować backendu.",
            "Logowanie nie powiodło się. Sprawdź email i hasło.",
            "Rejestracja nie powiodła się. Sprawdź dane i spróbuj ponownie.",
            "Zalogowano.",
            "Wylogowano.",
            "Sesja przywrócona.",
            "Sesja wygasła. Używane są lokalne ustawienia deweloperskie.",
            "Email i hasło są wymagane.",
            "Nazwa wyświetlana jest wymagana do rejestracji.",
            "Odtwarzanie głosu trwa zbyt długo. Spróbuj ponownie.",
            "Odtwarzanie głosu jest niedostępne. Możesz kontynuować, czytając wiadomość.",
            "Nie ukończono jeszcze lekcji na innym urządzeniu. Ukończ tę lekcję i spróbuj ponownie.",
            "Aktywna lekcja na innym urządzeniu",
            "Masz już aktywną lekcję na innym urządzeniu. Aby kontynuować tutaj, najpierw zakończ lekcję na tamtym urządzeniu.",
            "Zakończ lekcję na innym urządzeniu i kontynuuj",
            "Anuluj",
            "Nie udało się zakończyć lekcji na innym urządzeniu. Spróbuj ponownie."),
        ["ar"] = new(
            "الخادم الخلفي غير متاح. شغّل الخادم الخلفي المحلي وحاول مرة أخرى.",
            "تعذر الاتصال بالخادم. تأكد من أن الخادم الخلفي يعمل.",
            "يحتاج هذا الإجراء إلى الخادم الخلفي. حاول مرة أخرى بعد توفر الخادم.",
            "أعاد الخادم خطأ. حاول مرة أخرى.",
            "تعذر إكمال الطلب. راجع البيانات وحاول مرة أخرى.",
            "استغرق الطلب وقتًا طويلاً. حاول مرة أخرى.",
            "تعذرت قراءة استجابة الخادم. حاول مرة أخرى.",
            "تعذر تحميل الإعدادات من الخادم الخلفي. لا تزال الإعدادات المحلية متاحة.",
            "تم حفظ الإعدادات المحلية، لكن تعذر تحديث الخادم الخلفي.",
            "فشل تسجيل الدخول. تحقق من البريد الإلكتروني وكلمة المرور.",
            "فشل التسجيل. راجع بياناتك وحاول مرة أخرى.",
            "تم تسجيل الدخول.",
            "تم تسجيل الخروج.",
            "تمت استعادة الجلسة.",
            "انتهت صلاحية الجلسة. يتم استخدام إعدادات التطوير المحلية.",
            "البريد الإلكتروني وكلمة المرور مطلوبان.",
            "اسم العرض مطلوب للتسجيل.",
            "يستغرق الصوت وقتًا طويلاً. حاول مرة أخرى.",
            "تشغيل الصوت غير متاح. يمكنك المتابعة بقراءة الرسالة.",
            "لم تنه درسًا على جهاز آخر بعد. أنهِ ذلك الدرس ثم حاول مرة أخرى.",
            "درس نشط على جهاز آخر",
            "لديك درس نشط بالفعل على جهاز آخر. للمتابعة هنا، أنهِ الدرس على ذلك الجهاز أولاً.",
            "إنهاء الدرس على جهاز آخر والمتابعة",
            "إلغاء",
            "تعذر إنهاء الدرس على الجهاز الآخر. حاول مرة أخرى."),
        ["ja"] = new(
            "バックエンドを利用できません。ローカルバックエンドを起動して、もう一度お試しください。",
            "サーバーに接続できませんでした。バックエンドが実行中か確認してください。",
            "この操作にはバックエンドが必要です。サーバーが利用可能になってからもう一度お試しください。",
            "サーバーでエラーが発生しました。もう一度お試しください。",
            "リクエストを完了できませんでした。入力内容を確認して、もう一度お試しください。",
            "リクエストに時間がかかりすぎました。もう一度お試しください。",
            "サーバー応答を読み取れませんでした。もう一度お試しください。",
            "バックエンドから設定を読み込めませんでした。ローカル設定は引き続き利用できます。",
            "ローカル設定は保存されましたが、バックエンドを更新できませんでした。",
            "ログインに失敗しました。メールアドレスとパスワードを確認してください。",
            "登録に失敗しました。入力内容を確認して、もう一度お試しください。",
            "サインインしました。",
            "サインアウトしました。",
            "セッションを復元しました。",
            "セッションの有効期限が切れました。ローカル開発設定を使用します。",
            "メールアドレスとパスワードが必要です。",
            "登録には表示名が必要です。",
            "音声の準備に時間がかかりすぎています。もう一度お試しください。",
            "音声再生を利用できません。メッセージを読んで続けられます。",
            "別のデバイスでまだ完了していないレッスンがあります。そのレッスンを終了してから、もう一度お試しください。",
            "別のデバイスでレッスンが進行中",
            "別のデバイスでアクティブなレッスンがあります。ここで続けるには、先にそのデバイスのレッスンを終了してください。",
            "別のデバイスのレッスンを終了して続ける",
            "キャンセル",
            "別のデバイスのレッスンを終了できませんでした。もう一度お試しください。"),
        ["ko"] = new(
            "백엔드를 사용할 수 없습니다. 로컬 백엔드를 시작한 뒤 다시 시도하세요.",
            "서버에 연결할 수 없습니다. 백엔드가 실행 중인지 확인하세요.",
            "이 작업에는 백엔드가 필요합니다. 서버를 사용할 수 있을 때 다시 시도하세요.",
            "서버에서 오류가 반환되었습니다. 다시 시도하세요.",
            "요청을 완료할 수 없습니다. 입력을 확인하고 다시 시도하세요.",
            "요청 시간이 너무 오래 걸렸습니다. 다시 시도하세요.",
            "서버 응답을 읽을 수 없습니다. 다시 시도하세요.",
            "백엔드에서 설정을 불러올 수 없습니다. 로컬 설정은 계속 사용할 수 있습니다.",
            "로컬 설정은 저장되었지만 백엔드를 업데이트할 수 없습니다.",
            "로그인에 실패했습니다. 이메일과 비밀번호를 확인하세요.",
            "등록에 실패했습니다. 정보를 확인하고 다시 시도하세요.",
            "로그인되었습니다.",
            "로그아웃되었습니다.",
            "세션이 복원되었습니다.",
            "세션이 만료되었습니다. 로컬 개발 설정을 사용합니다.",
            "이메일과 비밀번호가 필요합니다.",
            "등록하려면 표시 이름이 필요합니다.",
            "음성 준비 시간이 너무 오래 걸립니다. 다시 시도하세요.",
            "음성 재생을 사용할 수 없습니다. 메시지를 읽고 계속할 수 있습니다.",
            "다른 기기에서 아직 끝내지 않은 레슨이 있습니다. 그 레슨을 마치고 다시 시도하세요.",
            "다른 기기에서 진행 중인 레슨",
            "다른 기기에서 이미 활성 레슨이 있습니다. 여기서 계속하려면 먼저 그 기기의 레슨을 종료하세요.",
            "다른 기기의 레슨을 종료하고 계속",
            "취소",
            "다른 기기의 레슨을 종료할 수 없습니다. 다시 시도하세요."),
        ["sr"] = new(
            "Backend nije dostupan. Pokrenite lokalni backend i pokušajte ponovo.",
            "Nije moguće povezati se sa serverom. Proverite da li backend radi.",
            "Ova radnja zahteva backend. Pokušajte ponovo kada server bude dostupan.",
            "Server je vratio grešku. Pokušajte ponovo.",
            "Zahtev nije mogao da bude završen. Proverite podatke i pokušajte ponovo.",
            "Zahtev traje predugo. Pokušajte ponovo.",
            "Odgovor servera nije mogao da se pročita. Pokušajte ponovo.",
            "Nije moguće učitati podešavanja sa backend-a. Lokalna podešavanja su i dalje dostupna.",
            "Lokalna podešavanja su sačuvana, ali backend nije mogao da se ažurira.",
            "Prijava nije uspela. Proverite e-poštu i lozinku.",
            "Registracija nije uspela. Proverite podatke i pokušajte ponovo.",
            "Prijavljeni ste.",
            "Odjavljeni ste.",
            "Sesija je vraćena.",
            "Sesija je istekla. Koriste se lokalna razvojna podešavanja.",
            "E-pošta i lozinka su obavezni.",
            "Ime za prikaz je obavezno za registraciju.",
            "Glasu treba previše vremena. Pokušajte ponovo.",
            "Reprodukcija glasa nije dostupna. Možete nastaviti čitanjem poruke.",
            "Još niste završili lekciju na drugom uređaju. Završite tu lekciju i pokušajte ponovo.",
            "Aktivna lekcija na drugom uređaju",
            "Već imate aktivnu lekciju na drugom uređaju. Da nastavite ovde, prvo završite lekciju na tom uređaju.",
            "Završi lekciju na drugom uređaju i nastavi",
            "Otkaži",
            "Nije moguće završiti lekciju na drugom uređaju. Pokušajte ponovo."),
        ["hr"] = new(
            "Backend nije dostupan. Pokrenite lokalni backend i pokušajte ponovno.",
            "Nije se moguće povezati s poslužiteljem. Provjerite radi li backend.",
            "Ova radnja zahtijeva backend. Pokušajte ponovno kada poslužitelj bude dostupan.",
            "Poslužitelj je vratio pogrešku. Pokušajte ponovno.",
            "Zahtjev nije mogao biti dovršen. Provjerite podatke i pokušajte ponovno.",
            "Zahtjev traje predugo. Pokušajte ponovno.",
            "Odgovor poslužitelja nije se mogao pročitati. Pokušajte ponovno.",
            "Nije moguće učitati postavke iz backend-a. Lokalne postavke i dalje su dostupne.",
            "Lokalne postavke su spremljene, ali backend nije bilo moguće ažurirati.",
            "Prijava nije uspjela. Provjerite e-poštu i lozinku.",
            "Registracija nije uspjela. Provjerite podatke i pokušajte ponovno.",
            "Prijavljeni ste.",
            "Odjavljeni ste.",
            "Sesija je vraćena.",
            "Sesija je istekla. Koriste se lokalne razvojne postavke.",
            "E-pošta i lozinka su obavezni.",
            "Ime za prikaz obavezno je za registraciju.",
            "Glas traje predugo. Pokušajte ponovno.",
            "Reprodukcija glasa nije dostupna. Možete nastaviti čitanjem poruke.",
            "Još niste završili lekciju na drugom uređaju. Završite tu lekciju i pokušajte ponovno.",
            "Aktivna lekcija na drugom uređaju",
            "Već imate aktivnu lekciju na drugom uređaju. Za nastavak ovdje najprije završite lekciju na tom uređaju.",
            "Završi lekciju na drugom uređaju i nastavi",
            "Odustani",
            "Nije moguće završiti lekciju na drugom uređaju. Pokušajte ponovno."),
        ["bg"] = new(
            "Бекендът не е наличен. Стартирайте локалния бекенд и опитайте отново.",
            "Неуспешна връзка със сървъра. Проверете дали бекендът работи.",
            "Това действие изисква бекенд. Опитайте отново, когато сървърът е наличен.",
            "Сървърът върна грешка. Опитайте отново.",
            "Заявката не можа да бъде изпълнена. Проверете данните и опитайте отново.",
            "Заявката отне твърде много време. Опитайте отново.",
            "Отговорът от сървъра не можа да бъде прочетен. Опитайте отново.",
            "Настройките не можаха да се заредят от бекенда. Локалните настройки остават налични.",
            "Локалните настройки са запазени, но бекендът не можа да бъде обновен.",
            "Неуспешно влизане. Проверете имейла и паролата.",
            "Неуспешна регистрация. Проверете данните и опитайте отново.",
            "Влязохте в профила.",
            "Излязохте от профила.",
            "Сесията е възстановена.",
            "Сесията изтече. Използват се локални настройки за разработка.",
            "Имейлът и паролата са задължителни.",
            "Името за показване е задължително за регистрация.",
            "Гласът се подготвя твърде дълго. Опитайте отново.",
            "Възпроизвеждането на глас не е налично. Можете да продължите, като прочетете съобщението.",
            "Все още не сте завършили урок на друго устройство. Завършете този урок и опитайте отново.",
            "Активен урок на друго устройство",
            "Вече имате активен урок на друго устройство. За да продължите тук, първо завършете урока на това устройство.",
            "Завършете урока на друго устройство и продължете",
            "Отказ",
            "Неуспешно завършване на урока на другото устройство. Опитайте отново.")
    };

    public static BackendUxLocalizedText GetText(string? languageId)
    {
        var normalizedLanguageId = InterfaceLanguageOptions.GetById(languageId).Id;
        return TextByLanguageId.TryGetValue(normalizedLanguageId, out var text)
            ? text
            : TextByLanguageId[InterfaceLanguageOptions.EnglishId];
    }
}
