namespace EnglishVoiceTutor.Desktop.Localization;

public sealed record SettingsLocalizedText(
    string Title,
    string Subtitle,
    string InterfaceLanguageTitle,
    string NativeLanguageTitle,
    string NativeLanguageSubtitle,
    string ConnectionTitle,
    string BackendUrlLabel,
    string BackendUrlSubtitle,
    string UserProfileTitle,
    string UserProfileSubtitle,
    string UserDisplayNameLabel,
    string LearningGoalLabel,
    string TutorAvatarTitle,
    string TutorAvatarSubtitle,
    string AvatarProfileTitle,
    string AvatarAgeLabel,
    string AvatarLocationLabel,
    string AvatarRoleLabel,
    string AvatarInterestsLabel,
    string AvatarPersonalityLabel,
    string AvatarSpeakingStyleLabel,
    string LearningStatisticsTitle,
    string LearningStatisticsSubtitle,
    string TotalCompletedLessonsLabel,
    string LessonsTodayLabel,
    string CurrentStreakLabel,
    string LastCompletedLessonLabel,
    string NoCompletedLessonsText,
    string SaveButtonText,
    string BackButtonText,
    string SettingsSavedMessage,
    string AudioInputTitle = "Audio input",
    string MicrophoneLabel = "Microphone",
    string SystemDefaultMicrophoneText = "System default",
    string TestMicrophoneText = "Test microphone",
    string RefreshMicrophonesText = "Refresh microphones",
    string MicrophoneTestCompletedMessage = "Microphone test completed.",
    string NoMicrophoneFoundMessage = "No microphone found.",
    string SelectedMicrophoneUnavailableMessage = "Selected microphone is unavailable. Using system default.",
    string StudyLanguageTitle = "Study language",
    string StudyLanguageSubtitle = "Choose the language you want to practice. This does not change the app UI language.",
    string AccountTitle = "Account",
    string AccountSubtitle = "Sign in or create an account to start lessons. A 7-day trial starts automatically after registration.",
    string AccountEmailLabel = "Email",
    string AccountPasswordLabel = "Password",
    string AccountDisplayNameLabel = "Display name (for registration)",
    string AccountRegisterButtonText = "Register",
    string AccountLoginButtonText = "Login",
    string AccountLogoutButtonText = "Logout",
    string CurrentAccountLabel = "Current account",
    string SettingsSourceLabel = "Settings source",
    string SubscriptionStatusTitle = "Subscription status",
    string SubscriptionPlanLabel = "Plan",
    string SubscriptionPremiumLabel = "Premium",
    string SubscriptionTrialLabel = "Trial",
    string SubscriptionFreeLessonLabel = "Free lesson today",
    string SubscriptionEnforcementLabel = "Enforcement",
    string SubscriptionSourceLabel = "Source",
    string SubscriptionCheckedAtLabel = "Checked",
    string CloseButtonText = "Close",
    string RefreshStatusButtonText = "Refresh status",
    string UpgradeButtonText = "Upgrade",
    string DiagnosticsTitle = "Diagnostics",
    string LearningTabHeader = "Learning",
    string ProgressTabHeader = "Progress",
    string ForgotPasswordTitle = "Forgot password?",
    string ForgotPasswordSubtitle = "Request reset instructions by email, then paste the reset code and choose a new password.",
    string ForgotPasswordButtonText = "Send reset instructions",
    string ResetTokenLabel = "Reset code",
    string NewPasswordLabel = "New password",
    string ConfirmNewPasswordLabel = "Confirm new password",
    string ResetPasswordButtonText = "Reset password",
    string ChangePasswordTitle = "Change password",
    string ChangePasswordSubtitle = "Update the password for the signed-in account.",
    string CurrentPasswordLabel = "Current password",
    string ChangePasswordButtonText = "Change password",
    string ContactsTabHeader = "Contacts",
    string ContactsTitle = "Contacts",
    string ContactsHelperText = "For product support, billing questions, legal requests, or privacy questions, contact us by email or visit the website.",
    string SupportEmailLabel = "Support email",
    string SupportEmailAddress = "support@languagevoicetutor.com",
    string WebsiteLabel = "Website",
    string WebsiteUrl = "https://languagevoicetutor.com");
