using EnglishVoiceTutor.Desktop.Models;

namespace EnglishVoiceTutor.Desktop.Localization;

public static class SettingsLocalization
{
    private static readonly IReadOnlyDictionary<string, SettingsLocalizedText> TextByLanguageId =
        new Dictionary<string, SettingsLocalizedText>(StringComparer.OrdinalIgnoreCase)
        {
            [InterfaceLanguageOptions.EnglishId] = new(
                "Settings",
                "Configure your learning preferences.",
                "Interface language",
                "Native language",
                "Translations will use this language later.",
                "Your profile",
                "This helps your tutor personalize lessons.",
                "Your name",
                "Learning goal",
                "Tutor avatar",
                "Choose who will guide your lesson chat.",
                "Learning statistics",
                "Based on completed lessons on this device.",
                "Total completed lessons",
                "Lessons completed today",
                "Current streak",
                "Last completed lesson",
                "No completed lessons yet.",
                "Save",
                "Back",
                "Settings saved for this session."),
            [InterfaceLanguageOptions.RussianId] = new(
                "Настройки",
                "Настройте параметры обучения.",
                "Язык интерфейса",
                "Родной язык",
                "Переводы будут использовать этот язык.",
                "Ваш профиль",
                "Это поможет наставнику персонализировать уроки.",
                "Ваше имя",
                "Цель обучения",
                "Аватар наставника",
                "Выберите, кто будет вести урок.",
                "Статистика обучения",
                "На основе завершённых уроков на этом устройстве.",
                "Всего завершено уроков",
                "Уроков завершено сегодня",
                "Текущая серия",
                "Последний завершённый урок",
                "Завершённых уроков пока нет.",
                "Сохранить",
                "Назад",
                "Настройки сохранены."),
            [InterfaceLanguageOptions.SpanishId] = new(
                "Ajustes",
                "Configura tus preferencias de aprendizaje.",
                "Idioma de la interfaz",
                "Idioma nativo",
                "Las traducciones usarán este idioma.",
                "Tu perfil",
                "Esto ayuda a tu tutor a personalizar las clases.",
                "Tu nombre",
                "Objetivo de aprendizaje",
                "Avatar del tutor",
                "Elige quién guiará tu clase.",
                "Estadísticas de aprendizaje",
                "Basadas en las clases completadas en este dispositivo.",
                "Clases completadas en total",
                "Clases completadas hoy",
                "Racha actual",
                "Última clase completada",
                "Aún no hay clases completadas.",
                "Guardar",
                "Atrás",
                "Ajustes guardados."),
            [InterfaceLanguageOptions.GermanId] = new(
                "Einstellungen",
                "Konfiguriere deine Lernpräferenzen.",
                "Sprache der Benutzeroberfläche",
                "Muttersprache",
                "Übersetzungen verwenden diese Sprache.",
                "Dein Profil",
                "So kann dein Tutor die Lektionen personalisieren.",
                "Dein Name",
                "Lernziel",
                "Tutor-Avatar",
                "Wähle, wer dich durch die Lektion begleitet.",
                "Lernstatistiken",
                "Basierend auf abgeschlossenen Lektionen auf diesem Gerät.",
                "Abgeschlossene Lektionen insgesamt",
                "Heute abgeschlossene Lektionen",
                "Aktuelle Serie",
                "Letzte abgeschlossene Lektion",
                "Noch keine abgeschlossenen Lektionen.",
                "Speichern",
                "Zurück",
                "Einstellungen gespeichert."),
            [InterfaceLanguageOptions.FrenchId] = new(
                "Paramètres",
                "Configurez vos préférences d’apprentissage.",
                "Langue de l’interface",
                "Langue maternelle",
                "Les traductions utiliseront cette langue.",
                "Votre profil",
                "Cela aide votre tuteur à personnaliser les leçons.",
                "Votre nom",
                "Objectif d’apprentissage",
                "Avatar du tuteur",
                "Choisissez qui guidera votre leçon.",
                "Statistiques d’apprentissage",
                "Basées sur les leçons terminées sur cet appareil.",
                "Leçons terminées au total",
                "Leçons terminées aujourd’hui",
                "Série actuelle",
                "Dernière leçon terminée",
                "Aucune leçon terminée pour le moment.",
                "Enregistrer",
                "Retour",
                "Paramètres enregistrés."),
            [InterfaceLanguageOptions.ItalianId] = new(
                "Impostazioni",
                "Configura le tue preferenze di apprendimento.",
                "Lingua dell’interfaccia",
                "Lingua madre",
                "Le traduzioni useranno questa lingua.",
                "Il tuo profilo",
                "Aiuta il tuo tutor a personalizzare le lezioni.",
                "Il tuo nome",
                "Obiettivo di apprendimento",
                "Avatar del tutor",
                "Scegli chi guiderà la tua lezione.",
                "Statistiche di apprendimento",
                "Basate sulle lezioni completate su questo dispositivo.",
                "Lezioni completate totali",
                "Lezioni completate oggi",
                "Serie attuale",
                "Ultima lezione completata",
                "Nessuna lezione completata.",
                "Salva",
                "Indietro",
                "Impostazioni salvate."),
            [InterfaceLanguageOptions.PortugueseId] = new(
                "Configurações",
                "Configure suas preferências de aprendizagem.",
                "Idioma da interface",
                "Idioma nativo",
                "As traduções usarão este idioma.",
                "Seu perfil",
                "Isso ajuda seu tutor a personalizar as aulas.",
                "Seu nome",
                "Objetivo de aprendizagem",
                "Avatar do tutor",
                "Escolha quem guiará sua aula.",
                "Estatísticas de aprendizagem",
                "Com base nas aulas concluídas neste dispositivo.",
                "Total de aulas concluídas",
                "Aulas concluídas hoje",
                "Sequência atual",
                "Última aula concluída",
                "Ainda não há aulas concluídas.",
                "Salvar",
                "Voltar",
                "Configurações salvas.")
        };

    public static SettingsLocalizedText GetSettingsText(string? interfaceLanguageId)
    {
        var languageId = InterfaceLanguageOptions.GetById(interfaceLanguageId).Id;
        return TextByLanguageId.TryGetValue(languageId, out var text)
            ? text
            : TextByLanguageId[InterfaceLanguageOptions.DefaultLanguageId];
    }
}
