namespace EnglishVoiceTutor.Desktop.Localization;

public sealed record SettingsLocalizedText(
    string Title,
    string Subtitle,
    string InterfaceLanguageTitle,
    string NativeLanguageTitle,
    string NativeLanguageSubtitle,
    string ConnectionTitle,
    string BackendUrlLabel,
    string BackendUrlSubtitle,
    string UserProfileTitle,
    string UserProfileSubtitle,
    string UserDisplayNameLabel,
    string LearningGoalLabel,
    string TutorAvatarTitle,
    string TutorAvatarSubtitle,
    string AvatarProfileTitle,
    string AvatarAgeLabel,
    string AvatarLocationLabel,
    string AvatarRoleLabel,
    string AvatarInterestsLabel,
    string AvatarPersonalityLabel,
    string AvatarSpeakingStyleLabel,
    string LearningStatisticsTitle,
    string LearningStatisticsSubtitle,
    string TotalCompletedLessonsLabel,
    string LessonsTodayLabel,
    string CurrentStreakLabel,
    string LastCompletedLessonLabel,
    string NoCompletedLessonsText,
    string SaveButtonText,
    string BackButtonText,
    string SettingsSavedMessage,
    string AudioInputTitle = "Audio input",
    string MicrophoneLabel = "Microphone",
    string SystemDefaultMicrophoneText = "System default",
    string TestMicrophoneText = "Test microphone",
    string RefreshMicrophonesText = "Refresh microphones",
    string MicrophoneTestCompletedMessage = "Microphone test completed.",
    string NoMicrophoneFoundMessage = "No microphone found.",
    string SelectedMicrophoneUnavailableMessage = "Selected microphone is unavailable. Using system default.");
