using EnglishVoiceTutor.Desktop.Models;

namespace EnglishVoiceTutor.Desktop.Localization;

public static class SubtopicsLocalization
{
    private static readonly IReadOnlyDictionary<string, SubtopicsScreenText> ScreenTextByLanguageId = new Dictionary<string, SubtopicsScreenText>(StringComparer.OrdinalIgnoreCase)
    {
        ["en"] = new("Choose a situation for {0}", "Choose a realistic situation for your short speaking lesson.", "Start Free Conversation", "Talk freely in English within safe and respectful boundaries."),
        ["es"] = new("Elige una situación para {0}", "Elige una situación realista para tu lección oral corta.", "Iniciar conversación libre", "Habla libremente en inglés dentro de límites seguros y respetuosos."),
        ["fr"] = new("Choisissez une situation pour {0}", "Choisissez une situation réaliste pour votre courte leçon orale.", "Démarrer la conversation libre", "Parlez librement en anglais dans un cadre sûr et respectueux."),
        ["de"] = new("Wähle eine Situation für {0}", "Wähle eine realistische Situation für deine kurze Sprechlektion.", "Freies Gespräch starten", "Sprich frei auf Englisch in einem sicheren, respektvollen Rahmen."),
        ["it"] = new("Scegli una situazione per {0}", "Scegli una situazione realistica per la tua breve lezione orale.", "Avvia conversazione libera", "Parla liberamente in inglese con limiti sicuri e rispettosi."),
        ["pt"] = new("Escolha uma situação para {0}", "Escolha uma situação realista para sua aula curta de conversação.", "Iniciar conversa livre", "Fale livremente em inglês com limites seguros e respeitosos."),
        ["ru"] = new("Выберите ситуацию для темы «{0}»", "Выберите реалистичную ситуацию для короткого устного урока.", "Начать свободный разговор", "Говорите свободно на английском в безопасных и уважительных рамках."),
        ["pl"] = new("Wybierz sytuację dla: {0}", "Wybierz realistyczną sytuację do krótkiej lekcji mówienia.", "Rozpocznij swobodną rozmowę", "Mów swobodnie po angielsku w bezpiecznych i życzliwych granicach."),
        ["ar"] = new("اختر موقفًا لـ {0}", "اختر موقفًا واقعيًا لدرسك القصير في المحادثة.", "ابدأ محادثة حرة", "تحدث بحرية بالإنجليزية ضمن حدود آمنة ومحترمة."),
        ["ja"] = new("{0}の場面を選択", "短いスピーキングレッスンのために現実的な場面を選びましょう。", "フリートークを始める", "安全で礼儀正しい範囲で英語を自由に話しましょう。"),
        ["ko"] = new("{0} 상황 선택", "짧은 말하기 수업을 위한 현실적인 상황을 선택하세요.", "자유 대화 시작", "안전하고 존중하는 범위에서 영어로 자유롭게 말하세요."),
        ["sr"] = new("Изаберите ситуацију за {0}", "Изаберите реалну ситуацију за кратку говорну лекцију.", "Започни слободан разговор", "Говорите слободно на енглеском у безбедним и учтивим оквирима."),
        ["hr"] = new("Odaberite situaciju za {0}", "Odaberite realnu situaciju za kratku govornu lekciju.", "Pokreni slobodni razgovor", "Govorite slobodno na engleskom uz sigurne i pristojne granice."),
        ["bg"] = new("Изберете ситуация за {0}", "Изберете реалистична ситуация за краткия си урок по говорене.", "Започни свободен разговор", "Говорете свободно на английски в безопасни и уважителни граници.")
    };

    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, LocalizedDisplayText>> SubtopicDisplayTextByLanguageId = BuildSubtopicDisplayTextByLanguageId();

    public static string GetTitleTemplate(string languageId) => GetScreenText(languageId).TitleTemplate;

    public static string GetSubtitle(string languageId) => GetScreenText(languageId).Subtitle;

    public static string GetFreeConversationTitle(string languageId) => GetScreenText(languageId).FreeConversationTitle;

    public static string GetFreeConversationSubtitle(string languageId) => GetScreenText(languageId).FreeConversationSubtitle;

    public static IReadOnlyDictionary<string, LocalizedDisplayText> BuildSubtopicDisplayText(string languageId)
    {
        var normalizedLanguageId = InterfaceLanguageOptions.GetById(languageId).Id;
        return SubtopicDisplayTextByLanguageId.TryGetValue(normalizedLanguageId, out var localizedText)
            ? localizedText
            : SubtopicDisplayTextByLanguageId[InterfaceLanguageOptions.EnglishId];
    }

    private static SubtopicsScreenText GetScreenText(string languageId)
    {
        var normalizedLanguageId = InterfaceLanguageOptions.GetById(languageId).Id;
        return ScreenTextByLanguageId.TryGetValue(normalizedLanguageId, out var text) ? text : ScreenTextByLanguageId[InterfaceLanguageOptions.EnglishId];
    }

    private static IReadOnlyDictionary<string, IReadOnlyDictionary<string, LocalizedDisplayText>> BuildSubtopicDisplayTextByLanguageId()
    {
        return new Dictionary<string, IReadOnlyDictionary<string, LocalizedDisplayText>>(StringComparer.OrdinalIgnoreCase)
        {
            ["en"] = Map(
                ("Introductions", "Introductions", "Introduce yourself and ask basic personal questions."),
                ("Small talk with a neighbor", "Talk with a neighbor", "Have a short friendly conversation near home."),
                ("Asking for help", "Ask for help", "Ask for help in a simple everyday situation."),
                ("Making plans", "Make plans", "Plan an activity and agree on time and place."),
                ("Talking about your day", "Talk about your day", "Describe your day and daily routine."),
                ("Airport check-in", "Airport check-in", "Check in for a flight and confirm travel details."),
                ("Hotel check-in", "Hotel check-in", "Check in at a hotel and ask common questions."),
                ("Asking for directions", "Ask for directions", "Ask for and understand directions in a new city."),
                ("Ordering transport", "Order transport", "Arrange a taxi or rideshare to your destination."),
                ("Lost luggage", "Lost luggage", "Report lost baggage and explain your situation."),
                ("First meeting", "First meeting", "Introduce yourself in a new work meeting."),
                ("Daily standup", "Daily standup", "Give a short update about your tasks."),
                ("Phone call with a client", "Phone call with a client", "Handle a polite and clear business call."),
                ("Asking for clarification", "Ask for clarification", "Ask follow-up questions to confirm requirements."),
                ("Discussing deadlines", "Discuss deadlines", "Talk about timelines and delivery expectations."),
                ("Tell me about yourself", "Tell me about yourself", "Give a short, relevant interview-style self-introduction."),
                ("Work experience", "Work experience", "Describe previous work, responsibilities, and one result."),
                ("Strengths and weaknesses", "Strengths and weaknesses", "Talk about one strength and one improvement area professionally."),
                ("Why do you want this job?", "Why do you want this job?", "Explain your motivation and connect the role to your skills."),
                ("Asking questions at the end", "Ask questions at the end", "Ask polite, useful questions before the interview finishes."),
                ("Booking a table", "Book a table", "Call or speak to reserve a table."),
                ("Ordering food", "Order food", "Order a meal and ask simple menu questions."),
                ("Asking about ingredients", "Ask about ingredients", "Ask about allergies and dish ingredients."),
                ("Handling a wrong order", "Handle a wrong order", "Politely explain an issue with your order."),
                ("Paying the bill", "Pay the bill", "Ask for the check and complete payment."),
                ("Open conversation", "Open conversation", "Talk freely in English within safe and respectful boundaries.")),
            ["es"] = Map(
                ("Introductions", "Presentaciones", "Preséntate y haz preguntas personales básicas."),
                ("Small talk with a neighbor", "Hablar con un vecino", "Ten una conversación breve y amable cerca de casa."),
                ("Asking for help", "Pedir ayuda", "Pide ayuda en una situación cotidiana sencilla."),
                ("Making plans", "Hacer planes", "Planifica una actividad y acuerda hora y lugar."),
                ("Talking about your day", "Hablar de tu día", "Describe tu día y tu rutina diaria."),
                ("Airport check-in", "Facturación en el aeropuerto", "Factura para un vuelo y confirma los detalles del viaje."),
                ("Hotel check-in", "Registro en el hotel", "Regístrate en un hotel y haz preguntas comunes."),
                ("Asking for directions", "Pedir indicaciones", "Pide y entiende indicaciones en una ciudad nueva."),
                ("Ordering transport", "Pedir transporte", "Organiza un taxi o transporte compartido hasta tu destino."),
                ("Lost luggage", "Equipaje perdido", "Informa de equipaje perdido y explica tu situación."),
                ("First meeting", "Primera reunión", "Preséntate en una nueva reunión de trabajo."),
                ("Daily standup", "Reunión diaria", "Da una breve actualización sobre tus tareas."),
                ("Phone call with a client", "Llamada con un cliente", "Maneja una llamada de negocios clara y cortés."),
                ("Asking for clarification", "Pedir aclaraciones", "Haz preguntas de seguimiento para confirmar requisitos."),
                ("Discussing deadlines", "Hablar de plazos", "Habla sobre tiempos y expectativas de entrega."),
                ("Tell me about yourself", "Háblame de ti", "Da una presentación breve y relevante para una entrevista."),
                ("Work experience", "Experiencia laboral", "Describe trabajos anteriores, responsabilidades y un resultado."),
                ("Strengths and weaknesses", "Fortalezas y debilidades", "Habla profesionalmente de una fortaleza y un área de mejora."),
                ("Why do you want this job?", "¿Por qué quieres este trabajo?", "Explica tu motivación y conecta el puesto con tus habilidades."),
                ("Asking questions at the end", "Preguntas al final", "Haz preguntas útiles y corteses antes de terminar la entrevista."),
                ("Booking a table", "Reservar una mesa", "Llama o habla para reservar una mesa."),
                ("Ordering food", "Pedir comida", "Pide una comida y haz preguntas sencillas sobre el menú."),
                ("Asking about ingredients", "Preguntar por ingredientes", "Pregunta por alergias e ingredientes de los platos."),
                ("Handling a wrong order", "Resolver un pedido incorrecto", "Explica cortésmente un problema con tu pedido."),
                ("Paying the bill", "Pagar la cuenta", "Pide la cuenta y completa el pago."),
                ("Open conversation", "Conversación abierta", "Habla libremente en inglés dentro de límites seguros y respetuosos.")),
            ["fr"] = Map(
                ("Introductions", "Présentations", "Présentez-vous et posez des questions personnelles simples."),
                ("Small talk with a neighbor", "Parler avec un voisin", "Ayez une courte conversation amicale près de chez vous."),
                ("Asking for help", "Demander de l’aide", "Demandez de l’aide dans une situation quotidienne simple."),
                ("Making plans", "Faire des projets", "Planifiez une activité et convenez d’une heure et d’un lieu."),
                ("Talking about your day", "Parler de votre journée", "Décrivez votre journée et votre routine quotidienne."),
                ("Airport check-in", "Enregistrement à l’aéroport", "Enregistrez-vous pour un vol et confirmez les détails du voyage."),
                ("Hotel check-in", "Arrivée à l’hôtel", "Enregistrez-vous à l’hôtel et posez des questions courantes."),
                ("Asking for directions", "Demander son chemin", "Demandez et comprenez des indications dans une nouvelle ville."),
                ("Ordering transport", "Commander un transport", "Organisez un taxi ou un covoiturage jusqu’à votre destination."),
                ("Lost luggage", "Bagage perdu", "Signalez un bagage perdu et expliquez votre situation."),
                ("First meeting", "Première réunion", "Présentez-vous lors d’une nouvelle réunion de travail."),
                ("Daily standup", "Point quotidien", "Donnez une courte mise à jour sur vos tâches."),
                ("Phone call with a client", "Appel avec un client", "Menez un appel professionnel clair et poli."),
                ("Asking for clarification", "Demander des précisions", "Posez des questions de suivi pour confirmer les besoins."),
                ("Discussing deadlines", "Discuter des délais", "Parlez des échéances et des attentes de livraison."),
                ("Tell me about yourself", "Parlez-moi de vous", "Faites une brève présentation pertinente pour un entretien."),
                ("Work experience", "Expérience professionnelle", "Décrivez vos emplois précédents, responsabilités et un résultat."),
                ("Strengths and weaknesses", "Forces et faiblesses", "Parlez d’une force et d’un point à améliorer de façon professionnelle."),
                ("Why do you want this job?", "Pourquoi voulez-vous ce poste ?", "Expliquez votre motivation et reliez le poste à vos compétences."),
                ("Asking questions at the end", "Questions à la fin", "Posez des questions utiles et polies avant la fin de l’entretien."),
                ("Booking a table", "Réserver une table", "Appelez ou parlez pour réserver une table."),
                ("Ordering food", "Commander à manger", "Commandez un repas et posez des questions simples sur le menu."),
                ("Asking about ingredients", "Demander les ingrédients", "Demandez des informations sur les allergies et les ingrédients."),
                ("Handling a wrong order", "Gérer une erreur de commande", "Expliquez poliment un problème avec votre commande."),
                ("Paying the bill", "Payer l’addition", "Demandez l’addition et effectuez le paiement."),
                ("Open conversation", "Conversation ouverte", "Parlez librement en anglais dans un cadre sûr et respectueux.")),
            ["de"] = Map(
                ("Introductions", "Vorstellungen", "Stelle dich vor und stelle einfache persönliche Fragen."),
                ("Small talk with a neighbor", "Mit einem Nachbarn sprechen", "Führe ein kurzes freundliches Gespräch in der Nähe deines Zuhauses."),
                ("Asking for help", "Um Hilfe bitten", "Bitte in einer einfachen Alltagssituation um Hilfe."),
                ("Making plans", "Pläne machen", "Plane eine Aktivität und vereinbare Zeit und Ort."),
                ("Talking about your day", "Über deinen Tag sprechen", "Beschreibe deinen Tag und deine tägliche Routine."),
                ("Airport check-in", "Check-in am Flughafen", "Checke für einen Flug ein und bestätige Reisedetails."),
                ("Hotel check-in", "Check-in im Hotel", "Checke im Hotel ein und stelle übliche Fragen."),
                ("Asking for directions", "Nach dem Weg fragen", "Frage nach dem Weg und verstehe Richtungen in einer neuen Stadt."),
                ("Ordering transport", "Transport bestellen", "Organisiere ein Taxi oder einen Fahrdienst zu deinem Ziel."),
                ("Lost luggage", "Verlorenes Gepäck", "Melde verlorenes Gepäck und erkläre deine Situation."),
                ("First meeting", "Erstes Meeting", "Stelle dich in einem neuen Arbeitsmeeting vor."),
                ("Daily standup", "Tägliches Stand-up", "Gib ein kurzes Update zu deinen Aufgaben."),
                ("Phone call with a client", "Telefonat mit einem Kunden", "Führe ein höfliches und klares Geschäftstelefonat."),
                ("Asking for clarification", "Um Klärung bitten", "Stelle Nachfragen, um Anforderungen zu bestätigen."),
                ("Discussing deadlines", "Fristen besprechen", "Sprich über Zeitpläne und Liefererwartungen."),
                ("Tell me about yourself", "Erzählen Sie etwas über sich", "Gib eine kurze, relevante Selbstvorstellung wie im Interview."),
                ("Work experience", "Berufserfahrung", "Beschreibe frühere Arbeit, Verantwortlichkeiten und ein Ergebnis."),
                ("Strengths and weaknesses", "Stärken und Schwächen", "Sprich professionell über eine Stärke und einen Verbesserungsbereich."),
                ("Why do you want this job?", "Warum möchten Sie diesen Job?", "Erkläre deine Motivation und verbinde die Rolle mit deinen Fähigkeiten."),
                ("Asking questions at the end", "Fragen am Ende stellen", "Stelle höfliche, nützliche Fragen vor dem Ende des Interviews."),
                ("Booking a table", "Einen Tisch reservieren", "Rufe an oder sprich, um einen Tisch zu reservieren."),
                ("Ordering food", "Essen bestellen", "Bestelle eine Mahlzeit und stelle einfache Menüfragen."),
                ("Asking about ingredients", "Nach Zutaten fragen", "Frage nach Allergien und Zutaten von Gerichten."),
                ("Handling a wrong order", "Eine falsche Bestellung klären", "Erkläre höflich ein Problem mit deiner Bestellung."),
                ("Paying the bill", "Die Rechnung bezahlen", "Bitte um die Rechnung und schließe die Zahlung ab."),
                ("Open conversation", "Offenes Gespräch", "Sprich frei auf Englisch in einem sicheren, respektvollen Rahmen.")),
            ["it"] = Map(
                ("Introductions", "Presentazioni", "Presentati e fai domande personali semplici."),
                ("Small talk with a neighbor", "Parlare con un vicino", "Fai una breve conversazione amichevole vicino a casa."),
                ("Asking for help", "Chiedere aiuto", "Chiedi aiuto in una semplice situazione quotidiana."),
                ("Making plans", "Fare programmi", "Pianifica un’attività e concorda ora e luogo."),
                ("Talking about your day", "Parlare della tua giornata", "Descrivi la tua giornata e la routine quotidiana."),
                ("Airport check-in", "Check-in in aeroporto", "Fai il check-in per un volo e conferma i dettagli del viaggio."),
                ("Hotel check-in", "Check-in in hotel", "Fai il check-in in hotel e fai domande comuni."),
                ("Asking for directions", "Chiedere indicazioni", "Chiedi e comprendi indicazioni in una nuova città."),
                ("Ordering transport", "Prenotare un trasporto", "Organizza un taxi o un passaggio fino alla destinazione."),
                ("Lost luggage", "Bagaglio smarrito", "Segnala il bagaglio smarrito e spiega la situazione."),
                ("First meeting", "Primo incontro", "Presentati in una nuova riunione di lavoro."),
                ("Daily standup", "Riunione giornaliera", "Dai un breve aggiornamento sulle tue attività."),
                ("Phone call with a client", "Telefonata con un cliente", "Gestisci una chiamata di lavoro chiara e cortese."),
                ("Asking for clarification", "Chiedere chiarimenti", "Fai domande di approfondimento per confermare i requisiti."),
                ("Discussing deadlines", "Discutere le scadenze", "Parla di tempi e aspettative di consegna."),
                ("Tell me about yourself", "Parlami di te", "Fai una breve presentazione adatta a un colloquio."),
                ("Work experience", "Esperienza lavorativa", "Descrivi lavori precedenti, responsabilità e un risultato."),
                ("Strengths and weaknesses", "Punti di forza e debolezze", "Parla professionalmente di un punto forte e di un’area da migliorare."),
                ("Why do you want this job?", "Perché vuoi questo lavoro?", "Spiega la motivazione e collega il ruolo alle tue competenze."),
                ("Asking questions at the end", "Domande alla fine", "Fai domande utili e cortesi prima della fine del colloquio."),
                ("Booking a table", "Prenotare un tavolo", "Chiama o parla per prenotare un tavolo."),
                ("Ordering food", "Ordinare cibo", "Ordina un pasto e fai semplici domande sul menu."),
                ("Asking about ingredients", "Chiedere gli ingredienti", "Chiedi informazioni su allergie e ingredienti dei piatti."),
                ("Handling a wrong order", "Gestire un ordine sbagliato", "Spiega cortesemente un problema con il tuo ordine."),
                ("Paying the bill", "Pagare il conto", "Chiedi il conto e completa il pagamento."),
                ("Open conversation", "Conversazione aperta", "Parla liberamente in inglese con limiti sicuri e rispettosi.")),
            ["pt"] = Map(
                ("Introductions", "Apresentações", "Apresente-se e faça perguntas pessoais básicas."),
                ("Small talk with a neighbor", "Conversar com um vizinho", "Tenha uma conversa breve e amigável perto de casa."),
                ("Asking for help", "Pedir ajuda", "Peça ajuda em uma situação simples do dia a dia."),
                ("Making plans", "Fazer planos", "Planeje uma atividade e combine horário e lugar."),
                ("Talking about your day", "Falar sobre seu dia", "Descreva seu dia e sua rotina diária."),
                ("Airport check-in", "Check-in no aeroporto", "Faça check-in para um voo e confirme detalhes da viagem."),
                ("Hotel check-in", "Check-in no hotel", "Faça check-in em um hotel e faça perguntas comuns."),
                ("Asking for directions", "Pedir direções", "Peça e entenda direções em uma cidade nova."),
                ("Ordering transport", "Pedir transporte", "Organize um táxi ou carona até seu destino."),
                ("Lost luggage", "Bagagem perdida", "Informe bagagem perdida e explique sua situação."),
                ("First meeting", "Primeira reunião", "Apresente-se em uma nova reunião de trabalho."),
                ("Daily standup", "Reunião diária", "Dê uma breve atualização sobre suas tarefas."),
                ("Phone call with a client", "Ligação com um cliente", "Conduza uma chamada de negócios clara e educada."),
                ("Asking for clarification", "Pedir esclarecimentos", "Faça perguntas de acompanhamento para confirmar requisitos."),
                ("Discussing deadlines", "Discutir prazos", "Fale sobre cronogramas e expectativas de entrega."),
                ("Tell me about yourself", "Fale sobre você", "Faça uma breve apresentação adequada para entrevista."),
                ("Work experience", "Experiência profissional", "Descreva trabalhos anteriores, responsabilidades e um resultado."),
                ("Strengths and weaknesses", "Pontos fortes e fracos", "Fale profissionalmente sobre um ponto forte e uma área de melhoria."),
                ("Why do you want this job?", "Por que você quer este emprego?", "Explique sua motivação e relacione a vaga às suas habilidades."),
                ("Asking questions at the end", "Perguntas no final", "Faça perguntas úteis e educadas antes do fim da entrevista."),
                ("Booking a table", "Reservar uma mesa", "Ligue ou fale para reservar uma mesa."),
                ("Ordering food", "Pedir comida", "Peça uma refeição e faça perguntas simples sobre o menu."),
                ("Asking about ingredients", "Perguntar sobre ingredientes", "Pergunte sobre alergias e ingredientes dos pratos."),
                ("Handling a wrong order", "Resolver um pedido errado", "Explique educadamente um problema com seu pedido."),
                ("Paying the bill", "Pagar a conta", "Peça a conta e complete o pagamento."),
                ("Open conversation", "Conversa aberta", "Fale livremente em inglês com limites seguros e respeitosos.")),
            ["ru"] = Map(
                ("Introductions", "Знакомство", "Представьтесь и задайте простые личные вопросы."),
                ("Small talk with a neighbor", "Разговор с соседом", "Проведите короткую дружелюбную беседу рядом с домом."),
                ("Asking for help", "Попросить о помощи", "Попросите помощи в простой повседневной ситуации."),
                ("Making plans", "Строить планы", "Запланируйте занятие и договоритесь о времени и месте."),
                ("Talking about your day", "Рассказать о своём дне", "Опишите свой день и ежедневный распорядок."),
                ("Airport check-in", "Регистрация в аэропорту", "Зарегистрируйтесь на рейс и подтвердите детали поездки."),
                ("Hotel check-in", "Заселение в отель", "Заселитесь в отель и задайте обычные вопросы."),
                ("Asking for directions", "Спросить дорогу", "Спросите и поймите маршрут в новом городе."),
                ("Ordering transport", "Заказать транспорт", "Организуйте такси или поездку до места назначения."),
                ("Lost luggage", "Потерянный багаж", "Сообщите о потерянном багаже и объясните ситуацию."),
                ("First meeting", "Первая встреча", "Представьтесь на новой рабочей встрече."),
                ("Daily standup", "Ежедневный стендап", "Кратко расскажите о своих задачах."),
                ("Phone call with a client", "Звонок с клиентом", "Проведите вежливый и понятный деловой звонок."),
                ("Asking for clarification", "Попросить уточнение", "Задайте дополнительные вопросы, чтобы подтвердить требования."),
                ("Discussing deadlines", "Обсудить сроки", "Поговорите о сроках и ожиданиях по доставке результата."),
                ("Tell me about yourself", "Расскажите о себе", "Дайте краткое уместное представление для собеседования."),
                ("Work experience", "Опыт работы", "Опишите прошлую работу, обязанности и один результат."),
                ("Strengths and weaknesses", "Сильные и слабые стороны", "Профессионально расскажите об одной сильной стороне и зоне роста."),
                ("Why do you want this job?", "Почему вы хотите эту работу?", "Объясните мотивацию и свяжите роль со своими навыками."),
                ("Asking questions at the end", "Вопросы в конце", "Задайте вежливые полезные вопросы перед завершением собеседования."),
                ("Booking a table", "Забронировать столик", "Позвоните или поговорите, чтобы забронировать столик."),
                ("Ordering food", "Заказать еду", "Закажите блюдо и задайте простые вопросы о меню."),
                ("Asking about ingredients", "Спросить об ингредиентах", "Спросите об аллергиях и ингредиентах блюд."),
                ("Handling a wrong order", "Исправить неверный заказ", "Вежливо объясните проблему с вашим заказом."),
                ("Paying the bill", "Оплатить счёт", "Попросите счёт и завершите оплату."),
                ("Open conversation", "Открытый разговор", "Говорите свободно на английском в безопасных и уважительных рамках.")),
            ["pl"] = Map(
                ("Introductions", "Przedstawianie się", "Przedstaw się i zadaj proste pytania osobiste."),
                ("Small talk with a neighbor", "Rozmowa z sąsiadem", "Przeprowadź krótką, miłą rozmowę blisko domu."),
                ("Asking for help", "Prośba o pomoc", "Poproś o pomoc w prostej codziennej sytuacji."),
                ("Making plans", "Robienie planów", "Zaplanuj aktywność i ustal czas oraz miejsce."),
                ("Talking about your day", "Rozmowa o dniu", "Opisz swój dzień i codzienną rutynę."),
                ("Airport check-in", "Odprawa na lotnisku", "Odpraw się na lot i potwierdź szczegóły podróży."),
                ("Hotel check-in", "Zameldowanie w hotelu", "Zamelduj się w hotelu i zadaj typowe pytania."),
                ("Asking for directions", "Pytanie o drogę", "Zapytaj o drogę i zrozum wskazówki w nowym mieście."),
                ("Ordering transport", "Zamawianie transportu", "Zorganizuj taksówkę lub przejazd do celu."),
                ("Lost luggage", "Zagubiony bagaż", "Zgłoś zagubiony bagaż i wyjaśnij sytuację."),
                ("First meeting", "Pierwsze spotkanie", "Przedstaw się na nowym spotkaniu w pracy."),
                ("Daily standup", "Codzienny stand-up", "Podaj krótką aktualizację o swoich zadaniach."),
                ("Phone call with a client", "Telefon z klientem", "Przeprowadź uprzejmą i jasną rozmowę biznesową."),
                ("Asking for clarification", "Prośba o wyjaśnienie", "Zadaj pytania dodatkowe, aby potwierdzić wymagania."),
                ("Discussing deadlines", "Omawianie terminów", "Porozmawiaj o harmonogramach i oczekiwaniach dostawy."),
                ("Tell me about yourself", "Opowiedz o sobie", "Przedstaw się krótko i trafnie jak na rozmowie kwalifikacyjnej."),
                ("Work experience", "Doświadczenie zawodowe", "Opisz poprzednią pracę, obowiązki i jeden rezultat."),
                ("Strengths and weaknesses", "Mocne i słabe strony", "Profesjonalnie opowiedz o jednej mocnej stronie i obszarze poprawy."),
                ("Why do you want this job?", "Dlaczego chcesz tę pracę?", "Wyjaśnij motywację i połącz rolę ze swoimi umiejętnościami."),
                ("Asking questions at the end", "Pytania na końcu", "Zadaj uprzejme, przydatne pytania przed końcem rozmowy."),
                ("Booking a table", "Rezerwacja stolika", "Zadzwoń lub porozmawiaj, aby zarezerwować stolik."),
                ("Ordering food", "Zamawianie jedzenia", "Zamów posiłek i zadaj proste pytania o menu."),
                ("Asking about ingredients", "Pytanie o składniki", "Zapytaj o alergie i składniki dań."),
                ("Handling a wrong order", "Błędne zamówienie", "Uprzejmie wyjaśnij problem z zamówieniem."),
                ("Paying the bill", "Płacenie rachunku", "Poproś o rachunek i zapłać."),
                ("Open conversation", "Otwarta rozmowa", "Mów swobodnie po angielsku w bezpiecznych i życzliwych granicach.")),
            ["ar"] = Map(
                ("Introductions", "التعارف", "عرّف بنفسك واسأل أسئلة شخصية بسيطة."),
                ("Small talk with a neighbor", "الحديث مع جار", "أجرِ محادثة قصيرة وودية قرب المنزل."),
                ("Asking for help", "طلب المساعدة", "اطلب المساعدة في موقف يومي بسيط."),
                ("Making plans", "ترتيب الخطط", "خطط لنشاط واتفق على الوقت والمكان."),
                ("Talking about your day", "الحديث عن يومك", "صِف يومك وروتينك اليومي."),
                ("Airport check-in", "تسجيل الوصول في المطار", "سجّل لرحلة وأكد تفاصيل السفر."),
                ("Hotel check-in", "تسجيل الوصول في الفندق", "سجّل في فندق واسأل أسئلة شائعة."),
                ("Asking for directions", "طلب الاتجاهات", "اطلب وافهم الاتجاهات في مدينة جديدة."),
                ("Ordering transport", "طلب وسيلة نقل", "رتب سيارة أجرة أو توصيلة إلى وجهتك."),
                ("Lost luggage", "الأمتعة المفقودة", "أبلغ عن الأمتعة المفقودة واشرح موقفك."),
                ("First meeting", "الاجتماع الأول", "عرّف بنفسك في اجتماع عمل جديد."),
                ("Daily standup", "اجتماع يومي قصير", "قدّم تحديثًا قصيرًا عن مهامك."),
                ("Phone call with a client", "مكالمة مع عميل", "أدر مكالمة عمل مهذبة وواضحة."),
                ("Asking for clarification", "طلب توضيح", "اطرح أسئلة متابعة لتأكيد المتطلبات."),
                ("Discussing deadlines", "مناقشة المواعيد النهائية", "تحدث عن الجداول الزمنية وتوقعات التسليم."),
                ("Tell me about yourself", "حدثني عن نفسك", "قدّم تعريفًا قصيرًا ومناسبًا للمقابلة."),
                ("Work experience", "الخبرة العملية", "صِف عملك السابق ومسؤولياتك ونتيجة واحدة."),
                ("Strengths and weaknesses", "نقاط القوة والضعف", "تحدث باحتراف عن نقطة قوة ومجال للتحسين."),
                ("Why do you want this job?", "لماذا تريد هذه الوظيفة؟", "اشرح دوافعك واربط الدور بمهاراتك."),
                ("Asking questions at the end", "أسئلة في النهاية", "اطرح أسئلة مفيدة ومهذبة قبل انتهاء المقابلة."),
                ("Booking a table", "حجز طاولة", "اتصل أو تحدث لحجز طاولة."),
                ("Ordering food", "طلب الطعام", "اطلب وجبة واسأل أسئلة بسيطة عن القائمة."),
                ("Asking about ingredients", "السؤال عن المكونات", "اسأل عن الحساسية ومكونات الأطباق."),
                ("Handling a wrong order", "التعامل مع طلب خاطئ", "اشرح بأدب مشكلة في طلبك."),
                ("Paying the bill", "دفع الفاتورة", "اطلب الفاتورة وأكمل الدفع."),
                ("Open conversation", "محادثة مفتوحة", "تحدث بحرية بالإنجليزية ضمن حدود آمنة ومحترمة.")),
            ["ja"] = Map(
                ("Introductions", "自己紹介", "自己紹介をして、基本的な個人の質問をしましょう。"),
                ("Small talk with a neighbor", "近所の人と話す", "家の近くで短く親しみやすい会話をしましょう。"),
                ("Asking for help", "助けを求める", "簡単な日常の場面で助けを求めましょう。"),
                ("Making plans", "予定を立てる", "活動を計画し、時間と場所を決めましょう。"),
                ("Talking about your day", "一日について話す", "自分の一日と毎日の習慣を説明しましょう。"),
                ("Airport check-in", "空港チェックイン", "フライトのチェックインをして旅行の詳細を確認しましょう。"),
                ("Hotel check-in", "ホテルチェックイン", "ホテルでチェックインし、よくある質問をしましょう。"),
                ("Asking for directions", "道を尋ねる", "新しい街で道を尋ね、案内を理解しましょう。"),
                ("Ordering transport", "交通手段を頼む", "目的地までのタクシーや配車を手配しましょう。"),
                ("Lost luggage", "手荷物の紛失", "手荷物の紛失を報告し、状況を説明しましょう。"),
                ("First meeting", "初めての会議", "新しい仕事の会議で自己紹介をしましょう。"),
                ("Daily standup", "デイリースタンドアップ", "自分のタスクについて短く報告しましょう。"),
                ("Phone call with a client", "顧客との電話", "丁寧で分かりやすいビジネス電話をしましょう。"),
                ("Asking for clarification", "確認を求める", "要件を確認するために追加の質問をしましょう。"),
                ("Discussing deadlines", "締め切りを話し合う", "スケジュールと納期の期待について話しましょう。"),
                ("Tell me about yourself", "自己紹介をしてください", "面接向けに短く関連性のある自己紹介をしましょう。"),
                ("Work experience", "職務経験", "過去の仕事、担当業務、成果を一つ説明しましょう。"),
                ("Strengths and weaknesses", "強みと弱み", "強み一つと改善点一つを専門的に話しましょう。"),
                ("Why do you want this job?", "なぜこの仕事を希望しますか", "志望理由を説明し、役割と自分のスキルを結び付けましょう。"),
                ("Asking questions at the end", "最後に質問する", "面接の終わりに丁寧で役立つ質問をしましょう。"),
                ("Booking a table", "席を予約する", "電話や会話で席を予約しましょう。"),
                ("Ordering food", "料理を注文する", "食事を注文し、メニューについて簡単な質問をしましょう。"),
                ("Asking about ingredients", "材料を尋ねる", "アレルギーや料理の材料について尋ねましょう。"),
                ("Handling a wrong order", "注文違いに対応する", "注文の問題を丁寧に説明しましょう。"),
                ("Paying the bill", "会計をする", "会計を頼み、支払いを済ませましょう。"),
                ("Open conversation", "自由な会話", "安全で礼儀正しい範囲で英語を自由に話しましょう。")),
            ["ko"] = Map(
                ("Introductions", "자기소개", "자신을 소개하고 기본적인 개인 질문을 해 보세요."),
                ("Small talk with a neighbor", "이웃과 대화하기", "집 근처에서 짧고 친근한 대화를 나누세요."),
                ("Asking for help", "도움 요청하기", "간단한 일상 상황에서 도움을 요청하세요."),
                ("Making plans", "계획 세우기", "활동을 계획하고 시간과 장소를 정하세요."),
                ("Talking about your day", "하루 이야기하기", "하루와 일상 루틴을 설명하세요."),
                ("Airport check-in", "공항 체크인", "항공편 체크인을 하고 여행 세부 사항을 확인하세요."),
                ("Hotel check-in", "호텔 체크인", "호텔에서 체크인하고 일반적인 질문을 하세요."),
                ("Asking for directions", "길 묻기", "새로운 도시에서 길을 묻고 안내를 이해하세요."),
                ("Ordering transport", "교통편 요청하기", "목적지까지 택시나 차량 서비스를 준비하세요."),
                ("Lost luggage", "분실 수하물", "수하물 분실을 신고하고 상황을 설명하세요."),
                ("First meeting", "첫 회의", "새 업무 회의에서 자신을 소개하세요."),
                ("Daily standup", "일일 스탠드업", "업무에 대해 짧게 업데이트하세요."),
                ("Phone call with a client", "고객과 전화하기", "정중하고 명확한 비즈니스 전화를 진행하세요."),
                ("Asking for clarification", "명확히 묻기", "요구 사항을 확인하기 위해 추가 질문을 하세요."),
                ("Discussing deadlines", "마감일 논의하기", "일정과 전달 기대 사항에 대해 이야기하세요."),
                ("Tell me about yourself", "자신에 대해 말하기", "면접에 맞는 짧고 관련 있는 자기소개를 하세요."),
                ("Work experience", "업무 경험", "이전 업무, 책임, 성과 하나를 설명하세요."),
                ("Strengths and weaknesses", "강점과 약점", "강점 하나와 개선할 점 하나를 전문적으로 말하세요."),
                ("Why do you want this job?", "왜 이 일을 원하나요?", "동기를 설명하고 역할을 자신의 기술과 연결하세요."),
                ("Asking questions at the end", "마지막에 질문하기", "면접이 끝나기 전에 정중하고 유용한 질문을 하세요."),
                ("Booking a table", "테이블 예약하기", "전화하거나 말해서 테이블을 예약하세요."),
                ("Ordering food", "음식 주문하기", "식사를 주문하고 메뉴에 대해 간단히 질문하세요."),
                ("Asking about ingredients", "재료 묻기", "알레르기와 음식 재료에 대해 물어보세요."),
                ("Handling a wrong order", "잘못된 주문 처리하기", "주문 문제를 정중하게 설명하세요."),
                ("Paying the bill", "계산하기", "계산서를 요청하고 결제를 마치세요."),
                ("Open conversation", "열린 대화", "안전하고 존중하는 범위에서 영어로 자유롭게 말하세요.")),
            ["sr"] = Map(
                ("Introductions", "Упознавање", "Представите се и поставите основна лична питања."),
                ("Small talk with a neighbor", "Разговор са комшијом", "Водите кратак пријатељски разговор близу куће."),
                ("Asking for help", "Тражење помоћи", "Затражите помоћ у једноставној свакодневној ситуацији."),
                ("Making plans", "Прављење планова", "Испланирајте активност и договорите време и место."),
                ("Talking about your day", "Разговор о вашем дану", "Опишите свој дан и дневну рутину."),
                ("Airport check-in", "Пријава на аеродрому", "Пријавите се за лет и потврдите детаље путовања."),
                ("Hotel check-in", "Пријава у хотелу", "Пријавите се у хотел и поставите уобичајена питања."),
                ("Asking for directions", "Питање за правац", "Питајте и разумите упутства у новом граду."),
                ("Ordering transport", "Наручивање превоза", "Организујте такси или превоз до одредишта."),
                ("Lost luggage", "Изгубљен пртљаг", "Пријавите изгубљен пртљаг и објасните ситуацију."),
                ("First meeting", "Први састанак", "Представите се на новом радном састанку."),
                ("Daily standup", "Дневни стендап", "Дајте кратак извештај о својим задацима."),
                ("Phone call with a client", "Позив са клијентом", "Водите љубазан и јасан пословни позив."),
                ("Asking for clarification", "Тражење појашњења", "Поставите додатна питања да потврдите захтеве."),
                ("Discussing deadlines", "Разговор о роковима", "Разговарајте о временским плановима и очекивањима испоруке."),
                ("Tell me about yourself", "Реците ми нешто о себи", "Дајте кратко и релевантно представљање за интервју."),
                ("Work experience", "Радно искуство", "Опишите претходни рад, одговорности и један резултат."),
                ("Strengths and weaknesses", "Снаге и слабости", "Професионално говорите о једној снази и области за побољшање."),
                ("Why do you want this job?", "Зашто желите овај посао?", "Објасните мотивацију и повежите улогу са својим вештинама."),
                ("Asking questions at the end", "Питања на крају", "Поставите љубазна и корисна питања пре краја интервјуа."),
                ("Booking a table", "Резервација стола", "Позовите или разговарајте да резервишете сто."),
                ("Ordering food", "Наручивање хране", "Наручите оброк и поставите једноставна питања о менију."),
                ("Asking about ingredients", "Питање о састојцима", "Питајте о алергијама и састојцима јела."),
                ("Handling a wrong order", "Решавање погрешне поруџбине", "Љубазно објасните проблем са својом поруџбином."),
                ("Paying the bill", "Плаћање рачуна", "Затражите рачун и завршите плаћање."),
                ("Open conversation", "Отворен разговор", "Говорите слободно на енглеском у безбедним и учтивим оквирима.")),
            ["hr"] = Map(
                ("Introductions", "Upoznavanje", "Predstavite se i postavite osnovna osobna pitanja."),
                ("Small talk with a neighbor", "Razgovor sa susjedom", "Vodite kratak prijateljski razgovor blizu kuće."),
                ("Asking for help", "Traženje pomoći", "Zatražite pomoć u jednostavnoj svakodnevnoj situaciji."),
                ("Making plans", "Dogovaranje planova", "Isplanirajte aktivnost i dogovorite vrijeme i mjesto."),
                ("Talking about your day", "Razgovor o vašem danu", "Opišite svoj dan i dnevnu rutinu."),
                ("Airport check-in", "Prijava u zračnoj luci", "Prijavite se za let i potvrdite detalje putovanja."),
                ("Hotel check-in", "Prijava u hotelu", "Prijavite se u hotel i postavite uobičajena pitanja."),
                ("Asking for directions", "Pitanje za smjer", "Pitajte i razumijte upute u novom gradu."),
                ("Ordering transport", "Naručivanje prijevoza", "Organizirajte taksi ili prijevoz do odredišta."),
                ("Lost luggage", "Izgubljena prtljaga", "Prijavite izgubljenu prtljagu i objasnite situaciju."),
                ("First meeting", "Prvi sastanak", "Predstavite se na novom poslovnom sastanku."),
                ("Daily standup", "Dnevni stand-up", "Dajte kratko ažuriranje o svojim zadacima."),
                ("Phone call with a client", "Poziv s klijentom", "Vodite pristojan i jasan poslovni poziv."),
                ("Asking for clarification", "Traženje pojašnjenja", "Postavite dodatna pitanja kako biste potvrdili zahtjeve."),
                ("Discussing deadlines", "Razgovor o rokovima", "Razgovarajte o vremenskim planovima i očekivanjima isporuke."),
                ("Tell me about yourself", "Recite mi nešto o sebi", "Dajte kratak i relevantan uvod za intervju."),
                ("Work experience", "Radno iskustvo", "Opišite prethodni rad, odgovornosti i jedan rezultat."),
                ("Strengths and weaknesses", "Snage i slabosti", "Profesionalno govorite o jednoj snazi i području za poboljšanje."),
                ("Why do you want this job?", "Zašto želite ovaj posao?", "Objasnite motivaciju i povežite ulogu sa svojim vještinama."),
                ("Asking questions at the end", "Pitanja na kraju", "Postavite pristojna i korisna pitanja prije kraja intervjua."),
                ("Booking a table", "Rezervacija stola", "Nazovite ili razgovarajte kako biste rezervirali stol."),
                ("Ordering food", "Naručivanje hrane", "Naručite obrok i postavite jednostavna pitanja o jelovniku."),
                ("Asking about ingredients", "Pitanje o sastojcima", "Pitajte o alergijama i sastojcima jela."),
                ("Handling a wrong order", "Rješavanje pogrešne narudžbe", "Pristojno objasnite problem sa svojom narudžbom."),
                ("Paying the bill", "Plaćanje računa", "Zatražite račun i dovršite plaćanje."),
                ("Open conversation", "Otvoreni razgovor", "Govorite slobodno na engleskom uz sigurne i pristojne granice.")),
            ["bg"] = Map(
                ("Introductions", "Запознаване", "Представете се и задайте основни лични въпроси."),
                ("Small talk with a neighbor", "Разговор със съсед", "Проведете кратък приятелски разговор близо до дома."),
                ("Asking for help", "Молба за помощ", "Помолете за помощ в проста ежедневна ситуация."),
                ("Making plans", "Правене на планове", "Планирайте дейност и уточнете време и място."),
                ("Talking about your day", "Разговор за деня ви", "Опишете деня си и ежедневната си рутина."),
                ("Airport check-in", "Регистрация на летището", "Регистрирайте се за полет и потвърдете подробностите за пътуването."),
                ("Hotel check-in", "Настаняване в хотел", "Настанете се в хотел и задайте обичайни въпроси."),
                ("Asking for directions", "Питане за посока", "Попитайте и разберете упътвания в нов град."),
                ("Ordering transport", "Поръчване на транспорт", "Организирайте такси или превоз до дестинацията."),
                ("Lost luggage", "Изгубен багаж", "Съобщете за изгубен багаж и обяснете ситуацията."),
                ("First meeting", "Първа среща", "Представете се на нова работна среща."),
                ("Daily standup", "Ежедневен стендъп", "Дайте кратка актуализация за задачите си."),
                ("Phone call with a client", "Разговор с клиент", "Проведете учтив и ясен бизнес разговор."),
                ("Asking for clarification", "Искане на уточнение", "Задайте допълнителни въпроси, за да потвърдите изискванията."),
                ("Discussing deadlines", "Обсъждане на срокове", "Говорете за графици и очаквания за доставка."),
                ("Tell me about yourself", "Разкажете за себе си", "Направете кратко и уместно представяне за интервю."),
                ("Work experience", "Професионален опит", "Опишете предишна работа, отговорности и един резултат."),
                ("Strengths and weaknesses", "Силни и слаби страни", "Говорете професионално за една силна страна и област за подобрение."),
                ("Why do you want this job?", "Защо искате тази работа?", "Обяснете мотивацията си и свържете ролята с уменията си."),
                ("Asking questions at the end", "Въпроси накрая", "Задайте учтиви и полезни въпроси преди края на интервюто."),
                ("Booking a table", "Резервация на маса", "Обадете се или говорете, за да резервирате маса."),
                ("Ordering food", "Поръчване на храна", "Поръчайте храна и задайте прости въпроси за менюто."),
                ("Asking about ingredients", "Питане за съставки", "Попитайте за алергии и съставки в ястията."),
                ("Handling a wrong order", "Проблем с грешна поръчка", "Учтиво обяснете проблем с поръчката си."),
                ("Paying the bill", "Плащане на сметката", "Поискайте сметката и завършете плащането."),
                ("Open conversation", "Отворен разговор", "Говорете свободно на английски в безопасни и уважителни граници."))
        };
    }

    private static IReadOnlyDictionary<string, LocalizedDisplayText> Map(params (string Key, string Title, string Description)[] values)
    {
        return values.ToDictionary(value => value.Key, value => new LocalizedDisplayText(value.Title, value.Description), StringComparer.OrdinalIgnoreCase);
    }

    private sealed record SubtopicsScreenText(string TitleTemplate, string Subtitle, string FreeConversationTitle, string FreeConversationSubtitle);
}
