// <auto-generated />
using System;
using EnglishVoiceTutor.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnglishVoiceTutor.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.AdminActionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("AdminUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("SafeMetadataJson")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("TargetUserId", "CreatedAtUtc");

                    b.ToTable("admin_actions", (string)null);
                });


            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentAuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AfterHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("BeforeHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ChangedFieldsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ContentPackId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RequestMetadataJson")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId", "CreatedAtUtc");

                    b.HasIndex("ContentPackId", "CreatedAtUtc");

                    b.ToTable("cms_content_audit_logs", (string)null);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.CmsLessonScenarioEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiTutorPromptInstructionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContextSelectionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ContentPackId")
                        .HasColumnType("uuid");

                    b.Property<string>("ControlledVariationJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConversationFlowJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ExpectedScenarioProgressionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeedbackRulesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FinalMessageAtUserTurn")
                        .HasColumnType("integer");

                    b.Property<string>("HintRulesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LearningGoalJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LessonType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LevelProfilesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OffTopicHandlingJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReciprocalQuestionHandlingJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepetitionLogicJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleplayBeatsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RolesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SetupMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SituationJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SoftWrapUpAfterUserTurn")
                        .HasColumnType("integer");

                    b.Property<string>("StableScenarioKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("SupportedLevelIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetLanguageJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentPackId", "StableScenarioKey")
                        .IsUnique();

                    b.HasIndex("TopicId");

                    b.ToTable("cms_lesson_scenarios", (string)null);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.CmsLessonTopicEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentPackId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StableTopicKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentPackId", "SortOrder");

                    b.HasIndex("ContentPackId", "StableTopicKey")
                        .IsUnique();

                    b.ToTable("cms_lesson_topics", (string)null);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentPackEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseStaticContentVersion")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("cms_content_packs", (string)null);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ContentPackId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PublishedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PublishStatus")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("RestoredFromVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SnapshotHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ValidationSummaryJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContentPackId", "VersionNumber")
                        .IsUnique();

                    b.HasIndex("PublishedByUserId");

                    b.HasIndex("RestoredFromVersionId");

                    b.ToTable("cms_content_versions", (string)null);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.PromptTemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedPlaceholdersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ContentPackId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("integer");

                    b.Property<string>("RequiredPlaceholdersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetStudyLanguageId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContentPackId", "TemplateKey", "TargetStudyLanguageId")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("cms_prompt_templates", (string)null);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.PublishedContentSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SnapshotHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContentVersionId")
                        .IsUnique();

                    b.ToTable("cms_published_content_snapshots", (string)null);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.TutorBehaviorProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommunicationStyleJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ContentPackId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("SafetyNotesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentPackId", "TutorId")
                        .IsUnique();

                    b.ToTable("cms_tutor_behavior_profiles", (string)null);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.BillingEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillingProvider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SafeMetadataJson")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("BillingProvider", "ProviderEventId")
                        .IsUnique();

                    b.ToTable("billing_events", (string)null);
                });


            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.PaddleWebhookEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("InternalPlanId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("InternalUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaddleCustomerId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PaddleEventId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PaddleNotificationId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PaddleSubscriptionId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PaddleTransactionId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SignatureHeader")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("InternalUserId");

                    b.HasIndex("PaddleEventId")
                        .IsUnique();

                    b.HasIndex("PaddleSubscriptionId");

                    b.HasIndex("PaddleTransactionId");

                    b.HasIndex("ProcessingStatus");

                    b.HasIndex("ReceivedAtUtc");

                    b.ToTable("paddle_webhook_events", (string)null);
                });


            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentAuditLogEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentPackEntity", "ContentPack")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ContentPackId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ContentPack");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.CmsLessonScenarioEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentPackEntity", "ContentPack")
                        .WithMany("LessonScenarios")
                        .HasForeignKey("ContentPackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.Cms.CmsLessonTopicEntity", "Topic")
                        .WithMany("LessonScenarios")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContentPack");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.CmsLessonTopicEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentPackEntity", "ContentPack")
                        .WithMany("LessonTopics")
                        .HasForeignKey("ContentPackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContentPack");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentPackEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentVersionEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentPackEntity", "ContentPack")
                        .WithMany("ContentVersions")
                        .HasForeignKey("ContentPackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("PublishedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentVersionEntity", "RestoredFromVersion")
                        .WithMany()
                        .HasForeignKey("RestoredFromVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ContentPack");

                    b.Navigation("RestoredFromVersion");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.PromptTemplateEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentPackEntity", "ContentPack")
                        .WithMany("PromptTemplates")
                        .HasForeignKey("ContentPackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ContentPack");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.PublishedContentSnapshotEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentVersionEntity", "ContentVersion")
                        .WithOne("PublishedSnapshot")
                        .HasForeignKey("EnglishVoiceTutor.Api.Data.Entities.Cms.PublishedContentSnapshotEntity", "ContentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContentVersion");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.TutorBehaviorProfileEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentPackEntity", "ContentPack")
                        .WithMany("TutorBehaviorProfiles")
                        .HasForeignKey("ContentPackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContentPack");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.DailyFreeLessonUsageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LessonSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("StudyLanguage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly>("UsageDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("UserMessageCountAtConsumption")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LessonSessionId");

                    b.HasIndex("UserId", "UsageDate")
                        .IsUnique();

                    b.ToTable("daily_free_lesson_usage", (string)null);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.DailyUsageCounterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChatReplyCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<int>("FeedbackRequests")
                        .HasColumnType("integer");

                    b.Property<int>("HintsUsed")
                        .HasColumnType("integer");

                    b.Property<int>("LessonsCompleted")
                        .HasColumnType("integer");

                    b.Property<int>("LessonsStarted")
                        .HasColumnType("integer");

                    b.Property<string>("StudyLanguage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("TranscriptionSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("TtsSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("UsageDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "UsageDate", "StudyLanguage")
                        .IsUnique();

                    b.ToTable("daily_usage_counters", (string)null);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.DeviceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.EntitlementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntitlementType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId", "Status", "StartsAtUtc", "ExpiresAtUtc");

                    b.ToTable("entitlements", (string)null);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.FeedbackResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrectedText")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CultureTip")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("Explanation")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("FeedbackType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("GrammarTip")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Praise")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("VocabularyTip")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("SessionId");

                    b.ToTable("feedback_results", (string)null);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.LessonEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContentVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LessonContentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SubtopicId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SubtopicTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TopicTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LessonContentId");

                    b.ToTable("lessons", (string)null);
                });


            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.CmsLessonTopicEntity", b =>
                {
                    b.Navigation("LessonScenarios");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentPackEntity", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ContentVersions");

                    b.Navigation("LessonScenarios");

                    b.Navigation("LessonTopics");

                    b.Navigation("PromptTemplates");

                    b.Navigation("TutorBehaviorProfiles");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentVersionEntity", b =>
                {
                    b.Navigation("PublishedSnapshot");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.LessonMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AudioDurationMs")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsValidLessonTurn")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("StudyLanguage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<decimal?>("TranscriptConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("lesson_messages", (string)null);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.LessonSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastHeartbeatAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LessonContentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ModeUsed")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SelectedContextId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SelectedContextTitle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("StudyLanguage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SubtopicId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SubtopicTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TopicTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ValidTurnCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.HasIndex("LastHeartbeatAtUtc");

                    b.HasIndex("UserId");

                    b.ToTable("lesson_sessions", (string)null);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.LessonSummaryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Grammar")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("Improvements")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("MistakesToReview")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("NextSteps")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Strengths")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsefulPhrases")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("Vocabulary")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("WhatToImprove")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("WhatWentWell")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("lesson_summaries", (string)null);
                });


            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.PasswordResetTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.PaymentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long?>("AmountMinor")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("BilledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InternalPlanId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ProviderCustomerId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProviderEventId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("ProviderEventOccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderEventType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderPayloadJson")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<string>("ProviderPaymentId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProviderPriceId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProviderProductId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProviderSubscriptionId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SafeMetadataJson")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderPaymentId")
                        .IsUnique()
                        .HasFilter("\"ProviderPaymentId\" IS NOT NULL");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.PlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlanId")
                        .IsUnique();

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.SubscriptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CurrentPeriodEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CurrentPeriodStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastProviderEventOccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastProviderEventId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LastProviderEventType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ProviderCustomerId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProviderPriceId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProviderProductId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProviderSubscriptionId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ScheduledChangeAction")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ScheduledChangeEffectiveAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("Provider", "ProviderSubscriptionId")
                        .IsUnique()
                        .HasFilter("\"ProviderSubscriptionId\" IS NOT NULL");

                    b.HasIndex("UserId", "Status", "Provider", "ProviderSubscriptionId");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.TrialGrantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceFingerprintHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourcePlatform")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("trial_grants", (string)null);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.UsageEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AudioDurationMs")
                        .HasColumnType("integer");

                    b.Property<long?>("AudioInputTokens")
                        .HasColumnType("bigint");

                    b.Property<long?>("AudioOutputTokens")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<long?>("InputChars")
                        .HasColumnType("bigint");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<long?>("OutputBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("StudyLanguage")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("usage_events", (string)null);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.UserProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentLevel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("NativeLanguage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SelectedTutorId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.UserSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ConversationModeEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExplanationLanguage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("SpeechSpeed")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("SpeechVoice")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("StudyLanguage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.AdminActionEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.UserEntity", "AdminUser")
                        .WithMany("AdminActionsCreated")
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.UserEntity", "TargetUser")
                        .WithMany("AdminActionsReceived")
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminUser");

                    b.Navigation("TargetUser");
                });



            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentAuditLogEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentPackEntity", "ContentPack")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ContentPackId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ContentPack");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.CmsLessonScenarioEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentPackEntity", "ContentPack")
                        .WithMany("LessonScenarios")
                        .HasForeignKey("ContentPackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.Cms.CmsLessonTopicEntity", "Topic")
                        .WithMany("LessonScenarios")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContentPack");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.CmsLessonTopicEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentPackEntity", "ContentPack")
                        .WithMany("LessonTopics")
                        .HasForeignKey("ContentPackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContentPack");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentPackEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentVersionEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentPackEntity", "ContentPack")
                        .WithMany("ContentVersions")
                        .HasForeignKey("ContentPackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("PublishedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentVersionEntity", "RestoredFromVersion")
                        .WithMany()
                        .HasForeignKey("RestoredFromVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ContentPack");

                    b.Navigation("RestoredFromVersion");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.PromptTemplateEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentPackEntity", "ContentPack")
                        .WithMany("PromptTemplates")
                        .HasForeignKey("ContentPackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ContentPack");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.PublishedContentSnapshotEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentVersionEntity", "ContentVersion")
                        .WithOne("PublishedSnapshot")
                        .HasForeignKey("EnglishVoiceTutor.Api.Data.Entities.Cms.PublishedContentSnapshotEntity", "ContentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContentVersion");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.Cms.TutorBehaviorProfileEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.Cms.ContentPackEntity", "ContentPack")
                        .WithMany("TutorBehaviorProfiles")
                        .HasForeignKey("ContentPackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContentPack");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.DailyFreeLessonUsageEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.LessonSessionEntity", "LessonSession")
                        .WithMany()
                        .HasForeignKey("LessonSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.UserEntity", "User")
                        .WithMany("DailyFreeLessonUsages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LessonSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.DailyUsageCounterEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.UserEntity", "User")
                        .WithMany("DailyUsageCounters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.DeviceEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.UserEntity", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.EntitlementEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.PlanEntity", null)
                        .WithMany("Entitlements")
                        .HasForeignKey("PlanId")
                        .HasPrincipalKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.SubscriptionEntity", "Subscription")
                        .WithMany("Entitlements")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.UserEntity", "User")
                        .WithMany("Entitlements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.FeedbackResultEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.LessonMessageEntity", "Message")
                        .WithMany("FeedbackResults")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.LessonSessionEntity", "Session")
                        .WithMany("FeedbackResults")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.LessonMessageEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.LessonSessionEntity", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.LessonSessionEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.UserEntity", "User")
                        .WithMany("LessonSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.LessonSummaryEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.LessonSessionEntity", "Session")
                        .WithOne("Summary")
                        .HasForeignKey("EnglishVoiceTutor.Api.Data.Entities.LessonSummaryEntity", "SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });


            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.PasswordResetTokenEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.UserEntity", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.PaymentEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.UserEntity", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.SubscriptionEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.PlanEntity", null)
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .HasPrincipalKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.UserEntity", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.TrialGrantEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.UserEntity", "User")
                        .WithMany("TrialGrants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.UsageEventEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.LessonSessionEntity", "Session")
                        .WithMany("UsageEvents")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.UserEntity", "User")
                        .WithMany("UsageEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.UserProfileEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.UserEntity", "User")
                        .WithOne("Profile")
                        .HasForeignKey("EnglishVoiceTutor.Api.Data.Entities.UserProfileEntity", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.UserSettingsEntity", b =>
                {
                    b.HasOne("EnglishVoiceTutor.Api.Data.Entities.UserEntity", "User")
                        .WithOne("Settings")
                        .HasForeignKey("EnglishVoiceTutor.Api.Data.Entities.UserSettingsEntity", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.LessonMessageEntity", b =>
                {
                    b.Navigation("FeedbackResults");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.LessonSessionEntity", b =>
                {
                    b.Navigation("FeedbackResults");

                    b.Navigation("Messages");

                    b.Navigation("Summary");

                    b.Navigation("UsageEvents");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.PlanEntity", b =>
                {
                    b.Navigation("Entitlements");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.SubscriptionEntity", b =>
                {
                    b.Navigation("Entitlements");
                });

            modelBuilder.Entity("EnglishVoiceTutor.Api.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("AdminActionsCreated");

                    b.Navigation("AdminActionsReceived");

                    b.Navigation("DailyFreeLessonUsages");

                    b.Navigation("DailyUsageCounters");

                    b.Navigation("Devices");

                    b.Navigation("Entitlements");

                    b.Navigation("LessonSessions");

                    b.Navigation("Payments");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("Profile");

                    b.Navigation("Settings");

                    b.Navigation("Subscriptions");

                    b.Navigation("TrialGrants");

                    b.Navigation("UsageEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
